### ISSUE TITLE
What about composite feature in PDFsam v3?

### ISSUE THREAD

**Issue by gionapoli** [torakiki/pdfsam#102]
The very useful feature to compose a PDF starting from more files is not in V3-M2 release, is it planned in the final release?

Thanks
Giorgio

**Comment by torakiki** [comment]
Hi, it was asked here https://github.com/torakiki/pdfsam/issues/98 
> Hi, visual modules are not included in the current PDFsam Basic v3. We will probably move them to a separate package called PDFsam Visual or something like that with the old visual modules reimplemented to fit the new PDFsam and some other new visual module as well. We are currently working on it.
