### ISSUE TITLE
Failure building PDFsam on eclipse

### ISSUE THREAD

**Issue by saniaalex** [torakiki/pdfsam#108]
I am trying to build pdfSAM on eclipse and installed all required plugins (maven,getText, Java 8) . When I try to build i am getting an error in pdfsam-core. The error is 

"Failed to execute goal on project pdfsam-core: Could not resolve dependencies for project org.pdfsam:pdfsam-core:jar:3.0.0.RELEASE-SNAPSHOT: The following artifacts could not be resolved: org.sejda:sejda-model:jar:2.0.0-alpha13, org.sejda:sejda-conversion:jar:2.0.0-alpha13: Failure to find org.sejda:sejda-model:jar:2.0.0-alpha13 in https://repository.jboss.org/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss has elapsed or updates are forced "

![screenshot 204](https://cloud.githubusercontent.com/assets/15204574/10823978/9a1fb998-7e34-11e5-9043-f505e454c445.png)

I also tried running pdfsam-core/pom.xml separately and error is 
"The POM for org.sejda:sejda-model:jar:2.0.0-alpha13 is missing, no dependency information available
The POM for org.sejda:sejda-conversion:jar:2.0.0-alpha13 is missing, no dependency information available"

Kindly give a sloution.

![screenshot 209](https://cloud.githubusercontent.com/assets/15204574/10823853/fb5d7dcc-7e33-11e5-8593-e671007d7515.png)
![screenshot 208](https://cloud.githubusercontent.com/assets/15204574/10823860/024cdf1a-7e34-11e5-9b63-6bf5f3d15020.png)
![screenshot 206](https://cloud.githubusercontent.com/assets/15204574/10823871/0eb6dc6a-7e34-11e5-9c4f-50a4778ca0bd.png)

**Comment by torakiki** [comment]
Should be fixed now by https://github.com/torakiki/pdfsam/commit/42e279a998dda3d0b40e52cfba6afc6066c6741b
