### ISSUE TITLE
.msi package crashes on Windows XP

### ISSUE THREAD

**Issue by Petrouchka** [torakiki/pdfsam#110]
I can use pdfsam-3.0.0.M4-bin.zip on Windows XP SP3 french version with jre-8u65-windows-i586.exe but the .msi package crashes at the end of the installation, just after opening Mozilla Firefox.
![capture-clone de windows xp professionnel sp3 instantane 1 en fonction - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/3955499/10871589/637a5bc8-80eb-11e5-9b6b-10228cce985b.png)

**Comment by torakiki** [comment]
Could you please make sure .NET framework 2.5 is installed? It is required by the MSI installer.

**Comment by Petrouchka** [comment]
Indeed. I installed .NET 3.5 and it works now, thank you.
It will be difficult to have a multiplatform software now :(

I saw that any others free softwares test if JAVA or .NET are installed and if not, download and install them. It would be interesting to add this feature in the installer.

**Comment by torakiki** [comment]
I already committed a fix for the .NET part. PDFsam doesn't require .NET but the installer does for a non mandatory task, so the installer now verifies if .NET is available and if not it skips the task, terminating without errors with or without .NET.
For the Java part it already informs the user if Java is not available but I agree, it could be a little more user friendly and perhaps install or download Java directly.

**Comment by Petrouchka** [comment]
It would not be easy to automatically download JAVA because I'm not sure the download link will be always the same. If the download fail, a message to inform of it would be necessary.

**Comment by torakiki** [comment]
I think this can be closed. The MSI will not fail now, despite .NET being or not being present. Java presence is verified and an warning message shown to the user asking him to install it. I guess that would work for now.

**Comment by Petrouchka** [comment]
Tested, it works with pdfsam-v3.0.1.RELEASE.msi.

**Comment by torakiki** [comment]
Great, thanks
