### ISSUE TITLE
Add bookmark name to prefix of Split by bookmarks output PDF filenames

### ISSUE THREAD

**Issue by macauley** [torakiki/pdfsam#115]
It would be very useful to enhance the Split by bookmarks feature to add an option in the "File names settings" section to include the bookmark name in the generated PDF document's name prefix. There are many cases when I split a PDF by bookmark where having the name of the bookmark in the filename would be useful to know what is in a given file rather than just the page number at which it was split.

**Comment by torakiki** [comment]
You can use the prefix `[BOOKMARK_NAME]` or `[BOOKMARK_NAME_STRICT]`, if you right click the prefix text field in the SplitByBookmarks module you should see them. There isn't a tutorial for v3 yet but you can find some info [here](http://www.pdfsam.org/wiki/howto-use-prefix/)
