### ISSUE TITLE
Unhelpful Java Exception Messages

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#117]
In both 2.2.4 and 3.0.0.M2, many error messages are simply Java Exception messages, and unless users are familiar with the style of these messages, they aren't particularly useful or helpful. For a better user experience, I would expect a more useful error message explaining the exact problem.  For example, when trying to split a document after page 0, an error message that explains the exact issue would be very helpful.

**Comment by torakiki** [comment]
Talking about v3 which is the current supported version. I tried to give nice and understandable validation errors (on the fields) and notifications (bottom right). It currently gives exceptions with stacktrace only when PDFsam fails hard, meaning that there is an actual problem, something that should probably reported to us. You talked about splitting at page 0 which was bug and I fixed here https://github.com/torakiki/pdfsam/issues/118 
Do you have other example or places where and exception message is shown and a more user friendly message could apply?
