### ISSUE TITLE
Split should report "0" as an invalid split page

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#118]
In the new beta version (3.0.0.M2), when I try to perform a split after page 0, it tells me "No page number given".  I HAD in fact entered a page number, but the program stripped it out because it was invalid. A more useful error message would be something like "Page 0 is not a valid input".

In version 2.2.4, when trying to split after the last page of the document, I get an error message that says it couldn't split BEFORE page N, when really it should have said it couldn't split AFTER page N.

**Comment by torakiki** [comment]
Fixed in v3. Version 2.2.4 is not supported anymore so we don't fix things in there
