### ISSUE TITLE
Alternate Mix progress bar in 2.2.4

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#119]
In 2.2.4, the progress bar for Alternate Mix doesn't show progress, but rather just moves back and forth during the operation. I would expect it to show progress, the same way that other features do. It is particularly inconvenient when mixing very large documents, as they can take quite some time to mix together.

**Comment by torakiki** [comment]
This should not be the case in v3.
Sorry if I'm repeating myself but we are focusing on v3 and we don't fix things on v2
