### ISSUE TITLE
Do not overwrite files option in Split (2.2.4)

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#120]
When "Do not overwrite" is selected in the Split feature of 2.2.4, and the output files already exist, a generic Java Exception message displays, and a temporary file is leftover in the output directory. Technically, the temporary file is per specifications on the Wiki, but it is not something I would expect to have to clean up after the operation.  Also, why does an error message display when I told the program I did not want to overwrite any existing files?  I would expect an indication that new files weren't able to be created, but not an error message.

**Comment by torakiki** [comment]
I don't see a "Do not overwrite" but there is a "Overwrite if already exists" checkbox. Anyway this is different in v3 now, you either select an empty destination folder or you tell PDFsam to overwrite existing files with the same name and this is clearly asked using a popup window
