### ISSUE TITLE
Performance Issues in 2.2.4

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#121]
In 2.2.4, I have seen several performance issues for large files. When I tried splitting large files (500-1000 pages), the performance for the first third or so of the pages was relatively good, but as the number of processed pages increased, the performance got increasingly slower.

Also in 2.2.4, when splitting a file with about 1000 pages, if a split was performed near the beginning of the file, overall performance was terrible.  But if I split the file near the end, performance was great.  Very large difference in processing time.

When these same operations were tried in the beta release 3.0.0.M2, all file operations were lightening fast. It seems all performance issues have been corrected in the latest release.

**Comment by torakiki** [comment]
Version 2 was first released around 2010 and we don't support it anymore. In the past years we focused on v3, [sejda](https://github.com/torakiki/sejda) and on [SAMBox](https://github.com/torakiki/sambox). After few years and a great effort we reached a point where we could drop iText (which is powering v2) and we can now fix and develop at any level, from the UI (PDFsam) to the PDF engine (SAMBox) so we are concentrating our limited resources on v3, Sejda and SAMBox and decided to drop support for v2. 
We are also very happy to know of SAMBox _lightening_ performances, it was quite an effort for us and it's nice to know it's paying off
