### ISSUE TITLE
Split at bookmark level 1 in 3.0.0.M2

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#122]
When trying to do a Split at bookmark level 1 in 3.0.0.M2, I entered a value of 1, and an error message indicated that I had entered an invalid bookmark level. I then clicked the down arrow next to the bookmark level entry, and it presented me with an option of 1 (the same thing I had entered before). When I selected the value from the drop down and tried the operation again, it succeeded this time.  For some reason, it doesn't accept the input value unless selected from the drop down.

**Comment by torakiki** [comment]
This is a regression in the jdk https://bugs.openjdk.java.net/browse/JDK-8136838
