### ISSUE TITLE
Splitting a second file in 2.2.4

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#123]
When trying to split a second file in version 2.2.4, I tried adding the file by dragging and dropping it from an open Windows Explorer window.  The message log at the bottom indicated that the file was successfully added for the operation, but the file selection table at the top still showed the name of the previous file. I performed the split, and the split was performed on the old file, not the new one I had just dragged in.

**Comment by torakiki** [comment]
This is not the case in v3, it seems everything is working as expected there.
