### ISSUE TITLE
Split by size in 2.2.4

### ISSUE THREAD

**Issue by arm3112** [torakiki/pdfsam#124]
When trying to split by size in 2.2.4, I chose to split into 50KB outputs. I know the Wiki says that the outputs will be split into "roughly" the specified size, but I found output file size deviations somewhere between 10-20% larger than specified.  When I tried the same operations in the new beta release 3.0.0.M2, the results were as expected, with the outputs almost exactly 50KB in size.

**Comment by torakiki** [comment]
We don't support v2 anymore so we don't fix things there.
It's nice to know that v3 is performing better even though, given the PDFs structure, "split by size" is a tricky subject and, also with v3, results may be way far from what is expected.
