### ISSUE TITLE
[feature request] add pdf diff/comparision tool

### ISSUE THREAD

**Issue by mattia-b89** [torakiki/pdfsam#130]
IMHO adding a feature like pdf comparison
such as:     - http://www.qtrac.eu/diffpdf.html
                  - https://github.com/momeni/visual-pdf-diff
                  - http://vslavik.github.io/diff-pdf/

would complete pdfsam as whole/global/total/almost-definitive pdf suite

**Comment by torakiki** [comment]
This is actually a nice feature, I had to use diffpdf myself for project this summer.

**Comment by torakiki** [comment]
We moved this to PDFsam Visual, not sure when we will add this but it's a useful feature
