### ISSUE TITLE
Compression performance

### ISSUE THREAD

**Issue by tobijdc** [torakiki/pdfsam#132]
I used pdfsam before to shrink PDF files, as pdfsam was able to more efficiently save the files. (I missused Merge with a single file to do this)
With 3.0.0 the files tend to be bigger than before, even if I discard forms and bookmarks and select compression.
Is this due to the new PDF-Engine you are using?
Is there any room for improvement?
Otherwise one of the most common use cases for me would be lost.

**Comment by torakiki** [comment]
Sure the engine is different so it likely generates PDFs with different (even very different) structure then before. If you could provide some example we will take a look and see if there is room for improvement or maybe the reason why they are bigger then before. If the docs contain private data you can send it to my email or share a link where I can download them and I'll use them only for this task and not share.
We are also working on an task to compress and optimize PDFs, it currently optimize images contained in a PDF but the plan is to also optimize the structure as well, you can try it online here http://www.sejda.com/

**Comment by tobijdc** [comment]
My PDFs are often ones created by Word.
I have created a "Lorem Ipsum" PDF with Word 2007.
I have "Merged" the document (only itself) using pdfsam 3.0.0 and 2.2.4 (No Forms, Compress, v1.7)

The result in this case is not big:

Word 2007 | pdfsam 2.2.4 | pdfsam 3.0.0
------------ | ------------- | ----
157 618 bytes | 142 647 bytes | 143 355 bytes
100% | 90,50% | 90,95%

To make it a little more realistic (Word files are usually not only text), I added random formating + 1 Smart Art.

The results are as follows:

Word 2007 | pdfsam 2.2.4 | pdfsam 3.0.0
------------ | ------------- | ----
871 945 bytes | 839 177 bytes | 840.520 bytes
100% | 96,24% | 96,40%

So all in all we are not talking about a big difference, but maybe there is room for improvement. For the moment I might keep on using 2.2.4, even if 3.0.0 GUI is awesome.

The homepage linked does not compress the PDF because `Sorry, task failed
Your PDF file is already very well compressed`, but a 9% improvement is still something.

[Zipped File with 3 Lorem PDFs](http://www.filedropper.com/loremipsumpdfs)
[Zipped File with 3 Lorem + Formatting PDFs](http://www.filedropper.com/loremformatpdfs)

**Comment by torakiki** [comment]
The engines behind 2.x and 3.x are completely different, on is iText 2.x the other is SAMBox 1.x, and they generate different structure. We might be able to save few byte here and there but I don't think there is much room for improvement and in the end, if we are talking about a 0.something% I don't think it's worth.
Somehow related, we just added an optimization to the split tasks resulting in some cases in smaller output documents, depending on the input PDF structure could be way way smaller.
