### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by aronovgj** [torakiki/pdfsam#135]
I couldn't find any information about silent arguments. Are there any? If not, please consider implementing them.

I'd like to see support for pdfsam v3 on chocolatey.org and for this the installer has to support unattended installation. The last version was easy because it was an msi installer.

**Comment by torakiki** [comment]
There is an MSI installer also for v3 in the release section and here is some documentation about it 
https://github.com/torakiki/pdfsam/blob/master/pdfsam-docs/PROPERTIESnARGS.md

**Comment by aronovgj** [comment]
Totally missed it. Thanks.

**Comment by torakiki** [comment]
no prob
