### ISSUE TITLE
Add option to manually merge PDF files in non-regular order using thumbnails

### ISSUE THREAD

**Issue by tilmaen** [torakiki/pdfsam#141]
Hi,

First i was excited about the new version being out. However i am missing one critical feature in the new version.
in PDFsam 2.2.4 it was possible to merge 2 PDF files manuall, selecting specific pages and rearranging them (thumbnails) via drag/drop.
Either the feature is gone in 3.0 or very hard to find. i would love to see the feature reappear.

greetings
tilmaen

**Comment by Lemalic** [comment]
I do have exactly the same recommandation, dispite the improved interface I think I will comme back to 2.2.4 for this feature !

**Comment by torakiki** [comment]
We released PDFsam Visual http://www.pdfsam.org/pdfsam-visual/
It has modules to rearrange page using thumbnails drag and drop but also Crop, split and other "visual" modules
