### ISSUE TITLE
pdfsam crash in GUI

### ISSUE THREAD

**Issue by Bro-Account** [torakiki/pdfsam#142]
Hi,

on one of my notebooks pdfsam crashes as soon as I click on any of the dropdown controls. It works fine on my other notebook. They have the same Java version installed and are both running Windows 10 x64.

Working on: Windows 10 Pro x64 English
Crashing on: Windows 10 Home x64 German

Here is the information from the preferences screen:
PDF Split and Merge Basic Edition
3.0.1.RELEASE
Java(TM) SE Runtime Environment 1.8.0_65-b17
JavaFX 8.0.65-b17
Maximaler Speicher 455 MB

I don't have this problem with any other Java application or ever had it. It occurred first on 3.0.0.

![2016-01-10_022617](https://cloud.githubusercontent.com/assets/16629127/12219396/bc85c662-b741-11e5-85ab-aead37334606.png)

![2016-01-10_022643](https://cloud.githubusercontent.com/assets/16629127/12219398/c1e945fc-b741-11e5-8c39-0c2b83cda779.png)

**Comment by torakiki** [comment]
First think I'd try upgrading Java, I had another user reporting the same issue on Windows 10 and he solved it by upgrading Java to 1.8.0_66.
If that doesn't solve you could open a shell and run PDFsam using the `bin/pdfsam.bat` and see if there is any error message there

**Comment by Bro-Account** [comment]
I can confirm that they fixed this in u66!
Thanks!
