### ISSUE TITLE
Import of split files

### ISSUE THREAD

**Issue by ChrisMillward** [torakiki/pdfsam#146]
It's not possible to select all the split pages and import them in order. It has to be done in stages 1 to 9, 10 to 99, 100 to 999 etc_. Leading zeros might make it easier, although untidy

**Comment by torakiki** [comment]
Files are added to the selection table in the order they are selected, so if in your Explorer you select the files in the right order and you drag/drop to the selection table, they will appear in the right order.
Split also allow to customize the output file name using placeholders, see http://www.pdfsam.org/customize-file-names/
