### ISSUE TITLE
Page selection in rotate task to rotate specific pages

### ISSUE THREAD

**Issue by yeppa** [torakiki/pdfsam#149]
Hello guys,

I want to thank you first that you made a perfect software which is i am using too much.

These days i need to change the orientation of pages on pdf and i saw that pdfsam has a power to do it but not enough.

I can change all pages, even pages or odd pages. But i need to choose the pages like 1,2,5,7,8. 

Could you consider about it with new update?

Regards

**Comment by torakiki** [comment]
This is currently available in [PDFsam Visual](http://www.pdfsam.org/pdfsam-visual/)... we'll see what we can do to add it to Basic

**Comment by yeppa** [comment]
Dear Vacandio

Thanks for your interest. You are perfect.

**Comment by GoncaloAdao** [comment]
Hi,

First I want congratulation you about this excellent program SAMpdf.

Some times ago, using a SAMpdf Basic and free version, we could view and rotate one or more specific page, not only all pages, or even or odd pages, like in version(ver. 3.0.2.Release)

So, how could I do it now? Or, if it doesn´t exist, my suggestion to you improve the software

Gonçalo Adão de Arruda Santos - Cuiabá-MT, from Brazil.

**Comment by torakiki** [comment]
Hi, see here http://www.pdfsam.org/rotate-pdf/ you can double click the cell "page ranges" and set the page numbers you want to rotate as comma separated numbers (ex 3,4,8,12), you'll need to upgrade to a more recent version, currently 3.2.2.
If you want the visual UI where you can see pages thumbnails and rotate them, that feature has been moved to PDFsam Visual, see here http://www.pdfsam.org/pdfsam-visual/
