### ISSUE TITLE
Silent (/quiet switch) install from .msi opens browser

### ISSUE THREAD

**Issue by jcak** [torakiki/pdfsam#150]
The "Thanks for installing" website still launches, even when an unattended installation is performed using the .msi file

This browser message should not be displayed when performing a silent installation.

Tested with Windows installation, version 3.0.10.0 of PDFSam Basic

**Comment by torakiki** [comment]
Have you tried the SKIPTHANKSPAGE property? https://github.com/torakiki/pdfsam/blob/master/pdfsam-docs/PROPERTIESnARGS.md

**Comment by jcak** [comment]
Thanks, that works. Apologies for not searching better...
install command for others to references:
`msiexec /i pdfsam.msi /qn SKIPTHANKSPAGE=Yes`
