### ISSUE TITLE
[Feature Request] Name of PDF splitted

### ISSUE THREAD

**Issue by rudiexp** [torakiki/pdfsam#153]
Hi

i want to ask if is possible to have a function that in the name field i can choose an area of the pdf.

for example if i've a pdf with 100 pages and i want to split the file every 2 pages i'd like to set as file name an area of the first page which is selectable or marked from a tag. If in the first page of 2 we have, for example, the name of my shirt in the header i'd like to have my shirt name as pdf file name.

Rudi

**Comment by torakiki** [comment]
Hi Rudi,
PDFsam Visual has a split by text module that lets you select an area of the page and splits the document when text in that area changes. You can also use the text found in the area as name of the resulting files, is this you use case?
You can find more details in the [PDF Split by text](http://www.pdfsam.org/pdfsam-visual/) section

**Comment by rudiexp** [comment]
Hi. thank  you for the answer. I'll check it in the tool and than i gonna
reply you question asap.

2016-05-05 13:49 GMT+02:00 Andrea Vacondio <notifications@github.com>:

> Hi Rudi,
> PDFsam Visual has a split by text module that lets you select an area of
> the page and splits the document when text in that area changes. You can
> also use the text found in the area as name of the resulting files, is this
> you use case?
> You can find more details in the PDF Split by text
> <http://www.pdfsam.org/pdfsam-visual/> section
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/torakiki/pdfsam/issues/153#issuecomment-217134870>
>



-- 
*Rudi Picillo*
