### ISSUE TITLE
Feature Request: Option to Discard Bookmarks During Split Operation

### ISSUE THREAD

**Issue by doubletriplezero** [torakiki/pdfsam#155]
It would be nice if the application provided the option to discard bookmarks in files resulting from a split operation. Currently this is only available when merging, but often when splitting a PDF which contains bookmarks, they are no longer necessary and may cause confusion in the resulting files which are output by the operation.

That said, I did devise a quick workaround which can be used in place of native support of discarding bookmarks during the split. A simple script can be used to iterate through the files output by the split and perform a merge on each individual file using the "-b discard" flag. Since the merge operation supports only being passed a single file you can basically just overwrite each one this way with a version without bookmarks.

**Comment by torakiki** [comment]
added to sejda-console https://github.com/torakiki/sejda/issues/231
