### ISSUE TITLE
SPLITPDF WITH A WHITE PAGE SEPARATOR

### ISSUE THREAD

**Issue by Pascal61** [torakiki/pdfsam#156]
Hello,
I shall wish to be able to cut a pdf file according to a white page separator.
The number of pages is not regular, my origin file can contain 4 full pages, 1 blank page in separator, 2 full pages, 1 blank page in separator, and 1 full page, that is in the end 3 separate files.
Do you think that it is possible?
Kind regards

**Comment by stehtimschilf** [comment]
Hi contributers
is there anyone implementing this feature which I find very pleasant/interessting? But according my experience it should be a customizable color page - as some duplex scan do have white pages.

looking forward
Sven

**Comment by capsmet** [comment]
It would be great to add separator pages with the ability to add the same field used to generate the table of contents (such as filename, or document title that follows, etc.).  

This would be a really terrific addition to the project.

**Comment by torakiki** [comment]
This is currently possible with the Extract tool in PDFsam Visual, using white pages as separator.
