### ISSUE TITLE
Print from Outlook giving Custom UI Runtime error

### ISSUE THREAD

**Issue by jim-appnet** [torakiki/pdfsam#157]
PDFSam Enhanced user trying to print to PDF in Outlook 2013
Gets the following error and Outlook crashes:

Custom UI Runtime Error in PDFSam Enhanced Outlook Plugin
The call to GetCustomUI() for RibbonID "Microsoft.Otulook.Explorer" failed.

They had a previous second PDF maker set as a printer. I removed the printer and rebooted the workstation. Outlook stays open now and allows me to do a File:Send and then submit the mail, but I still get the runtime pop-ups.

Any thoughts on how to clear them?

Thanks!

Jim

**Comment by torakiki** [comment]
Hi,
this is the issue tracker for PDFsam Basic, you should write to pdfsam_enhanced@pdfsam.org and the PDFsam Enhanced team will provide support for this.
Thanks
