### ISSUE TITLE
Keep numbering at the same length when splitting

### ISSUE THREAD

**Issue by kofaysi** [torakiki/pdfsam#163]
Currently (PDFsam 3.0.2):
```
1_PDFsam_Scanned...
2_PDFsam_Scanned...
...
9_PDFsam_Scanned...
10_PDFsam_Scanned...
```

Wished feature:
```
01_PDFsam_Scanned...
02_PDFsam_Scanned...
...
09_PDFsam_Scanned...
10_PDFsam_Scanned...
```

So, keeping the same lengths (in number of digits) for the added numbers.

Thank you for listening!

**Comment by torakiki** [comment]
Hi, the feature is already there, file naming in PDFsam is pretty flexible... take a look at this http://www.pdfsam.org/customize-file-names/
