### ISSUE TITLE
[bug] external links don't work

### ISSUE THREAD

**Issue by mattia-b89** [torakiki/pdfsam#164]
I'm on Arch Linux.
If I try to open an external link, nothing happen, or better, I get the below errors in the log.

e.g. using the DOWNLOAD button when a new version is available or simply the github link from the about tab

http://pastebin.com/BXyrqVHE

**Comment by torakiki** [comment]
What Java version are you using?

**Comment by mattia-b89** [comment]
I'm running `openjdk-8.u92`
that is, to be more precise:
`[mattia@arch-xps ~]$ java -version
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (build 1.8.0_92-b14)
OpenJDK 64-Bit Server VM (build 25.92-b14, mixed mode)
`

**Comment by mattia-b89** [comment]
updated to latest version 3.0.3 but I have to same issue

**Comment by torakiki** [comment]
Is it a the package provided by Arch Linux distribution or are you using the zip bundle we provide?

**Comment by mattia-b89** [comment]
I was talking about the package provided by Arch Linux.
anyway, just for debug purpose, I downloaded and tried the universal zip bundle but I get the same problem...
http://pastebin.com/qHpPmgs8

**Comment by torakiki** [comment]
Ok, great, thanks, I'll see if I get the same on my Ubuntu using openjdk
