### ISSUE TITLE
Do not open in full screen

### ISSUE THREAD

**Issue by cemekepirketou** [torakiki/pdfsam#165]
At launch, pdfsam 3.0.2 opens in full screen, I can reduce, but not resize the window. Yet, I have buttons for full screen and resizable window on the top right, but resizable window mode, I can not grasp the edge of the window. OS: win7
![pdfsam-resizable_window_button_at_the_top_right](https://cloud.githubusercontent.com/assets/19364502/15270034/2743bec2-1a12-11e6-8869-ad879d35a918.jpg)

**Comment by torakiki** [comment]
Do you still have this issue? We tested on our Win7 and we could resize it with no prob.. could you give us some more detail about Java version and Windows service pack?

**Comment by cemekepirketou** [comment]
Le 22/08/2016 à 11:25, Andrea Vacondio a écrit :
> Do you still have this issue? We tested on our Win7 and we could resize
> it with no prob.. could you give us some more detail about Java version
> and Windows service pack?

Hello,

No more issue with 3.1.0 totaly different,
ticket closed, thank you
--
Cemeke
