### ISSUE TITLE
Merge removing form field line breaks & format from original document

### ISSUE THREAD

**Issue by willpom** [torakiki/pdfsam#168]
When merging pdfs one document has the form field line breaks (autowrapped from converted LibreOffice Writer doc) and alignment format removed so not all information is displayed. On p3 of merged doc attached. Can't seem to work around this without removing the fields.
Regression: This didn't happen in a previous version (can't remember which I upgraded from but had the old GUI).
[Original.pdf](https://github.com/torakiki/pdfsam/files/297493/Original.pdf)
[Merged.pdf](https://github.com/torakiki/pdfsam/files/297494/Merged.pdf)

**Comment by torakiki** [comment]
Hi, can you please point exactly where this happens? I opened both with Acrobat Reader and I don't see differences in page 3
![forms](https://cloud.githubusercontent.com/assets/3884479/15926237/2e160c18-2e3b-11e6-82f3-469121dd8867.png)

**Comment by willpom** [comment]
I use SumatraPDF to view. It appears to be a function of this program as I've just tested using an online viewer and everything is ok. I'll submit a bug with them.

**Comment by torakiki** [comment]
Ok. Closing.

**Comment by willpom** [comment]
I've editted my last post as I forgot the original with forms displays ok in Sumatra so has PDFsam altered the file structure anyway?
If you think not then I'll submit the bug to Sumatra as well.

**Comment by torakiki** [comment]
Yes, indeed merging PDF docs requires to change some internal structure.. it's not like, let's say text files, where you can just append once thing to the other, PDF has a complex structure and PDFsam has to read the original files and create a new one.

**Comment by willpom** [comment]
Should I submit a bug with SumatraPDF then as integrity is maintained in other readers; even though the original displays ok? Or is it something to look at your end?

**Comment by torakiki** [comment]
Acrobat Reader and Chrome PDF viewer both display the merged file correctly so I'd say the file is correct and the bug is in Sumatra... it doesn't really matter where the PDF comes from, if it's a merged result or an doc found on the internet or anything else.
It could be a PDFsam bug but given that other viewers have no trouble showing the file, in our prospective PDFsam does the correct job and we can't know why Sumatra shows odd forms so I'd say it's Sumatra that has an issue and I'd report it to them.

**Comment by willpom** [comment]
I'll reprot it to them, but I'll also re-iterate the original file un-merged displays as expected in SumatraPDF, only after merging does it display incorrectly. Thanks for help.

**Comment by torakiki** [comment]
Yes, understood... and it could either a bug in PDFsam not generating the PDF according to specs or a bug in Sumatra. If it turns out we are doing something wrong, let us know and of course we'll try to fix it but given that other readers display it correctly, I think it's a Sumatra issue.

**Comment by GitHubRulesOK** [comment]
There still appears to be a SAMBox issue outside SumatraPDF (MuPDF engine)
If I open the merged file above in newer Edge I can see the form entries and re-save as a valid pdf which will view in SumatraPDF
[Merged from edge.pdf](https://github.com/torakiki/pdfsam/files/5059963/Merged.from.edge.pdf)

![image](https://user-images.githubusercontent.com/12754913/89959749-157b4900-dc35-11ea-97be-bb3f6dc4fdb8.png)
If I attempt to add a new entry with sejda it will appear in SumatraPDF but the existing will not even though it is still visible in other viewers
[Merged from sejda.pdf](https://github.com/torakiki/pdfsam/files/5059965/Merged.from.sejda.pdf)

![image](https://user-images.githubusercontent.com/12754913/89959961-7b67d080-dc35-11ea-98c9-7af4bf583f63.png)

If I attempt to add a new entry with edge after sejda all will appear in SumatraPDF
[Merged from edge2.pdf](https://github.com/torakiki/pdfsam/files/5059972/Merged.from.edge2.pdf)

![image](https://user-images.githubusercontent.com/12754913/89960196-3bedb400-dc36-11ea-8806-74752c07b1a7.png)
I have to conclude both sejda and edge can build valid files but the previous SAM merge has had some detrimental effect compared to simply adding a form entry.
