### ISSUE TITLE
PDFsam Downloader fails with "Perform error: 7" on Windows 7

### ISSUE THREAD

**Issue by JThoennes** [torakiki/pdfsam#169]
Just downloaded the PDFsam downloader from the web site and it failed with "Perform error: 7"

![image](https://cloud.githubusercontent.com/assets/164437/15927345/695a501c-2e41-11e6-9920-7c1d93cf64b2.png)

Downloading and installing the MSI worked fine. I guess it may be due to the HTTP proxy configuration.

Any way to get further information on this?

**Comment by torakiki** [comment]
This should be fixed now
