### ISSUE TITLE
[feature request] reduce the PDF size

### ISSUE THREAD

**Issue by mattia-b89** [torakiki/pdfsam#178]
I'd like to have a feature able to reduce the size of a PDF.

for my really limited PDF acknowledge, big PDF files are full of images. Hence I think a good way to shrink the size of a PDF is to reduce the resolution on embedded images. This is just an idea about how to perform this task

**Comment by torakiki** [comment]
We already have the optimize task in our open source engine, it does what you suggested plus other optimizations and it's currently available using the [command line interface](http://www.sejda.org/) or the [web interface](http://www.sejda.com/compress-pdf).
We probably won't add it the the Basic edition but we could add it to Visual.. we'll think about it, thanks for the suggestion.
