### ISSUE TITLE
Installer Service is unavailable

### ISSUE THREAD

**Issue by mystarrocks** [torakiki/pdfsam#181]
Attempting to upgrade PDFsam Enhanced always results in an error:

> Installer Service is unavailable
> CONTACT SUPPORT CLOSE

One wouldn't want to download the latest installer every time and re-install because the upgrade doesn't work.

**Comment by torakiki** [comment]
Hi, could you please contact the PDFsam Enhanced channel here? http://www.pdfsam.org/support-pdfsam-enhanced/
They will try to understand what is the issue
