### ISSUE TITLE
Acroform fields blanked out during merge

### ISSUE THREAD

**Issue by mhlmhl** [torakiki/pdfsam#184]
I filled out an Acrobat form file (using Adobe Acrobat Reader DC 2015 Release Version 2016.017.20053 on Windows 8.1) , then split it into three sections so that I could print one page, sign and scan it, and merge it all back together.  Then I merged it with a bunch of other pdf files to create one big pdf file.  That all worked fine.

Later, I need to make a change to the first pdf file, so used the same version of Acrobat Reader to update a couple of form fields.  Then I ran the big merge again -- and discovered that all the form fields are completely empty in the big pdf file.

To illustrate:
Fill in fields via Reader (v1)-->split-->print, sign, & scan one page-->merge back together (v2)-->merge with other files

then:
Filll in fields in v2 via Reader-->merge with other files ---- and all the form fields are blank!

I avoided the problem by repeating the original steps, filling in the form fields in v1 of the file, splitting and merging that to create a v2', and merging that into all the other files.

Conclusion: a merge of a forms document does not work correctly when that document has previously been split, manually updated, and then merged.  The difference between these two files is the signature page, which is page 12.

I've attached the original document (v1) and the split and then merged version (v2') in case that helps you figure this out.
[2016 Mohansic Trailway Greenway Conservancy Application source.pdf](https://github.com/torakiki/pdfsam/files/462327/2016.Mohansic.Trailway.Greenway.Conservancy.Application.source.pdf)
[2016 Mohansic Trailway Greenway Conservancy Application.pdf](https://github.com/torakiki/pdfsam/files/462329/2016.Mohansic.Trailway.Greenway.Conservancy.Application.pdf)

**Comment by torakiki** [comment]
Fixed in Sejda 2.6 and included in PDFsam 3.2
