### ISSUE TITLE
Alternate Mix Blank Pages

### ISSUE THREAD

**Issue by BobobUnicorn** [torakiki/pdfsam#185]
PDF Split and Merge Basic Edition
3.1.0.RELEASE
Java(TM) SE Runtime Environment 1.8.0_40-b26
JavaFX 8.0.40-b26
Max memory 494 MB

Windows 10 Pro
Version 10.0.14393 Build 14393

[combined.pdf](https://github.com/torakiki/pdfsam/files/468748/combined.pdf)
[even-reversed.pdf](https://github.com/torakiki/pdfsam/files/468749/even-reversed.pdf)
[odd.pdf](https://github.com/torakiki/pdfsam/files/468750/odd.pdf)

When odd.pdf (1st file) & even-reversed.pdf (2nd file) are put into alternate mix with second file reversed, the output is combined.pdf.

Shows blank pages when viewed with:
- Adobe Acrobat Reader DC Ver 2015.017.20053
- Nitro Reader 3.5.6.5
- SumatraPDF v3.0
- Microsoft Edge 25.10586.0.0
- Microsoft Reader App

Does not show blank pages when viewed with:
- Google Chrome 52.0.2743.116 m
- Opera 39.0.2256.71
- PDF.js 1.5.456

**Comment by torakiki** [comment]
Can you constantly reproduce it? I figured what is the issue with the attached `combined.pdf` but I can't manage to reproduce it with the given inputs, either in Linux or Win10

**Comment by BobobUnicorn** [comment]
I originally tried it twice and it produced the same problem. However, now that I try again it produces a file that is readable with all the viewers above.

**Comment by torakiki** [comment]
Ok, please let us know if you manage to reproduce it. I also tried to follow the code and see if I could find a scenario where it happens but I couldn't find any so it's kind of a strange issue
