### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by jean-pierre1** [torakiki/pdfsam#188]
Is there an easy way to delete a page in a PDF file with pdfsam free?
Thank's

**Comment by torakiki** [comment]
You can use the extract module leaving out from the pages selection all the
page numbers you want to delete, so say you want to delete page 5 and 7 you
can use a page selection like 1-4,6,8-

Il 23 set 2016 11:39, "jean-pierre1" <notifications@github.com> ha scritto:

**Comment by jean-pierre1** [comment]
Thank's for the solution
