### ISSUE TITLE
[bug] Retain bookmarks does not preserve "Fit page" zoom view

### ISSUE THREAD

**Issue by georgthegreat** [torakiki/pdfsam#191]
After merging such document all bookmarks remain on their places but zoom the page at maximum zoom (6400% in my pdf viewer)

If you need an example pdf, let me know, though I think bug is reproducible with any document

**Comment by torakiki** [comment]
I closed it here https://github.com/torakiki/sejda/commit/b2c6a2154dfd09ced3e2b8385bb5486dd7ddd051 it will be in PDFsam with the next release

**Comment by georgthegreat** [comment]
Any plans to release this soon? My workflow is somewhat like blocked by this bug :(

**Comment by torakiki** [comment]
It's probably going to be in a month or so. I could make a test release for you as a workaround until the official release is out

**Comment by georgthegreat** [comment]
This would be great.
Thank you!

**Comment by torakiki** [comment]
Here https://www.dropbox.com/s/0pc472pl1rtsrzf/pdfsam-3.2.3.RELEASE-SNAPSHOT-bin.zip?dl=0

**Comment by georgthegreat** [comment]
This version works fine.
Thanks a lot!

**Comment by tdalon** [comment]
Hello. I have the same issue with the 3.3.0 (portable installation).
