### ISSUE TITLE
error 129 opening pdf created from merged pdf files

### ISSUE THREAD

**Issue by ugeots** [torakiki/pdfsam#194]
Merging pdf with SAM. Getting error 129.
Which says:
"There was an error processing a page. The was a problem reading this document (129)."
After hitting CTRL+OK getting - "illegal characters in name message."

I use smallpdf.com for merging same pdfs with no problems.

PDF Split and Merge Basic Edition
3.0.2.RELEASE
Java(TM) SE Runtime Environment 1.8.0_101-b13
JavaFX 8.0.101-b13
Max memory 494 MB

**Comment by torakiki** [comment]
Hi, could you please try the latest PDFsam version? If the issue is still
there could you provide us the PDFsam document? Thanks

Il 17 ott 2016 15:28, "ugeots" <notifications@github.com> ha scritto:

**Comment by ugeots** [comment]
Hi,
Now it works. Thanks. 
Strangely, I updated PDFsam as prompted by program at startup.
The PDFsam version changed after i have restarted computer.
