### ISSUE TITLE
Drop Down Menu Freezing

### ISSUE THREAD

**Issue by Orenji-kun** [torakiki/pdfsam#196]
I just downloaded PDFsam Basic 3.2.2 to rotate a rather large PDF file, and when I go to change the settings from clockwise to counterclockwise or click on any other drop down menus on this page, the program freezes and starts eating up cpu power and ram.

![pdfsam_bug](https://cloud.githubusercontent.com/assets/4706405/19578097/043bfb44-96cf-11e6-8595-840335e2e3dd.png)

There is probably a minor bug in the code for the drop down menu, and I have already tried reinstalling it.

**Comment by torakiki** [comment]
Please try upgrading/reinstalling Java and let us know if the issue is still there

**Comment by torakiki** [comment]
Please try reinstalling/upgrading Java

Il 20 ott 2016 23:14, "Orenji-kun" <notifications@github.com> ha scritto:
