### ISSUE TITLE
pdf filenames are illegible - osx version sierra

### ISSUE THREAD

**Issue by mewes** [torakiki/pdfsam#199]
![image](https://cloud.githubusercontent.com/assets/8017483/19636677/15535f36-99cb-11e6-8617-ac8c1067518c.png)

The problem appears if your pdf filename contains umlauts like äüö.

**Comment by longstone** [comment]
I can't confirm this issue, see image attached, are you still having problems with the latest version?

> longstone$ sw_vers -productVersion 
10.12.1


![image](https://cloud.githubusercontent.com/assets/2110765/20041394/9b7d4e76-a468-11e6-9334-971d79297eaf.png)

**Comment by torakiki** [comment]
Could you try the latest version? Everything seems to work correctly on our Mac and we cannot reproduce this

**Comment by torakiki** [comment]
No feedback
