### ISSUE TITLE
Sequential File Numbering On Split

### ISSUE THREAD

**Issue by RadiatorPie** [torakiki/pdfsam#202]
Hi,

I've only just recently started using PDFsam and I would like to know if there is a way of numbering the output files sequentially. I've seen you can do it using [FILENUMBER] but that starts at 1 and counts up. If there was a way you could state a number (e.g. 48685) which would be the first page and then every subsequent page would be one higher (e.g. page two is 48686, page 3 is 48687 etc.)
Any help would be appreciated

Steven

**Comment by torakiki** [comment]
Yes, you can use `[FILENUMBER48685]`, see here for more details
http://www.pdfsam.org/customize-file-names/
