### ISSUE TITLE
Configure java path

### ISSUE THREAD

**Issue by jano42** [torakiki/pdfsam#204]
It would be very usefull to be able to configure the JavaRuntimeEnvironment (either by command line argument or by configuration file)

On windows, I make it work by adding in "pdfsam.bat" just after ":repoSetup (l65)"

``````
set JAVACMD="path\to\jre\bin\java.exe"
``````

Now I can run PdfSam by running "pdfsam.bat"

**Comment by torakiki** [comment]
That's the idea of the pdfsam.bat and .sh, to be configurable and flexible so users can play with them. So my understanding is that you already managed to configure the Java path, what is exactly that you would like to add to PDFsam? Some way to configure the Java path that is picked up by the pdfsam.exe?
