### ISSUE TITLE
Silent install with "Context menu shortcuts" enabled?

### ISSUE THREAD

**Issue by spirtle1973** [torakiki/pdfsam#212]
Is there a way to do a silent install and have "context menu shortcuts" enabled?  I'm deploying to end-users and everything else works perfectly.

Thank you

**Comment by torakiki** [comment]
I haven't tested myself but I think this has the answer http://stackoverflow.com/questions/246329/wix-how-to-select-features-from-command-line
so you should add `ADDLOCAL=MainAppFeature,AddContextMenu` to your command line.
Reopen this if it doesn't work

**Comment by HellStorm666** [comment]
I know it's old, but is there a MSI property that I can set to enable the context menu?
Or a toggle to enable the context menu after installation?
