### ISSUE TITLE
PDFSAM wont activate enhanced 

### ISSUE THREAD

**Issue by saltracker** [torakiki/pdfsam#216]
Product wont activate 
Help desk don't know whats going on 
Looks like accounts have been scrambled or deleted 

Major bug 

This message was sent to georgeebester@gmail.com in reference to CASE #379362
 
   Audrey - Agent replied (FEB 17, 2017  |  06:40AM EST) 

Dear Realou,
Thank you for contacting PDFSam Customer Service. Our apologies but it seems we are unable to locate an active account for you in our customer database. If you believe that you are a paying member, please provide us with your Order ID number which would have been included in your confirmation email. This email was sent to you after completing the signup process. If you cannot find you order ID, please let us know some additional information that will assist us in locating your account, that is, telephone number, alternative email address, etc.
With this information we will be able to locate your account and provide you with further assistance.
Please reply to this email with any other questions you may have. Our support team will be happy to assist you.
Sincerely,
Audrey
PDFSam
Customer Support Representative
 
   George wrote FEB 15, 2017  |  04:26PM EST

**Comment by torakiki** [comment]
Hi George,
this is a public issue tracker so I removed details regarding your payment receipt.
This is the PDFsam Basic issue tracker so we don't provide support for PDFsam Enhanced here, that kind of support is provided using the form at http://www.pdfsam.org/support-pdfsam-enhanced/ which I assume you used, since you got an answer and a CASE id.
I don't know the details of this particular case but it seems the support team cannot find an order associated to your email address and is asking for more details, have you already sent them those details? 

> please provide us with your Order ID...please let us know some additional information that will assist us in locating your account, that is, telephone number, alternative email address, etc

**Comment by saltracker** [comment]
Hi Andrea

Thanks for the response
I don't seem to be making any progress with your support staff and they are
not reading the emails
*I have supplied them with the order no ( which should be enough across all
my emails that I use )  and I did pay you for a full package *
*This licence system you have does not seem to be working as it continues
to ask me for licences after I activate them *
*I have grown very tired of this too and fro - getting nowhere *
*If this cannot be resolved just give me my money back and Ill buy Adobe -
which i am beginning to think I should have done in the first case *
I tried the OCR  on my bank statements and it was terrible
Got much better results  out of wondershare 6 in 1

seaRCH FOR GEORGEBESTER@ OR GBESTER@

**Comment by torakiki** [comment]
Hi George,
I asked the support team to take care of this, please let me know if this is not the case.

**Comment by saltracker** [comment]
Hi Andrea 


Many thanks 

The most manager gave me a key which unlocked the services I needed 


My best 


George 







georgebester






From: Andrea Vacondio

Sent: Wednesday, 22 February, 10:57 AM

Subject: Re: [torakiki/pdfsam] PDFSAM wont activate enhanced (#216)

To: torakiki/pdfsam

Cc: geb, Author



Hi George,

I asked the support team to take care of this, please let me know if this is not the case.
