### ISSUE TITLE
PDFSAM running but no windows showing - MAC

### ISSUE THREAD

**Issue by kerrynprest** [torakiki/pdfsam#218]
Hi, I've installed PDFSAM, and it shows in the programme dock, but there are no windows showing. 
Can anyone help?
Thanks Kerry

**Comment by torakiki** [comment]
Try this, make sure you only have one monitor connected.
* close/kill PDFsam if it's running
* see if you have the directory ~/Library/Preferences/ and something related to PDFsam in it, files called org.pdfsam.something.... delete them
* start PDFsam

**Comment by kerrynprest** [comment]
Hi - thanks, that worked!

Kerry
