### ISSUE TITLE
Changes Default App setting despite check box at install

### ISSUE THREAD

**Issue by bboorman** [torakiki/pdfsam#219]
PDFSam makes itself the default PDF app in Windows (found on Windows 7 Enterprise) regardless of the checkbox setting at install time.

Steps to Reproduce (on Win7 Ent)
1. Download installer
2. Run installer
3. Uncheck the box for setting PDFSam to be the default PDF app
4. Finish installation.
5. In Windows Explorer, browse to a folder with a PDF file, note the PDFSam Icon for the file
6. Double-Click file - Windows launches PDFSam instead of Adobe Reader XI.

**Comment by torakiki** [comment]
Are you talking about the PDFsam Basic installer that offers to try PDFsam Enhanced? I just tried on a Win 7 box and everything worked as expected, PDFsam Enhanced wasn't set as default application. 
I will ask the team to look into it, can you please confirm if it's the PDFsam Basic downloader or the PDFsam Enhanced installer?
Thanks
