### ISSUE TITLE
Pages left blank after merging

### ISSUE THREAD

**Issue by Andie42** [torakiki/pdfsam#221]
Hello,

I'm having problems when trying to merge two documents. I've tried several times but the result is always the same: some pages in the first document are left blank.

Hope you can help me. I'm attaching the document in question: blank pages from 2 to 8.

Thanks!

[1 List.pdf](https://github.com/torakiki/pdfsam/files/853052/1.List.pdf)

**Comment by Andie42** [comment]
[1 List.pdf](https://github.com/torakiki/pdfsam/files/853039/1.List.pdf)

**Comment by torakiki** [comment]
Could you attach the original documents before merge?

**Comment by Andie42** [comment]
[1 List.pdf](https://github.com/torakiki/pdfsam/files/853458/1.List.pdf)
[2 Read & Writ.pdf](https://github.com/torakiki/pdfsam/files/853460/2.Read.Writ.pdf)

Here they are!

**Comment by torakiki** [comment]
I can see that Acrobat shows only page 1 and 9 while other pages are blank. Opening the doc with other readers shows pages content (PDFium, pdf.js..) while my Ubuntu PDF viewer shows more or less what Acrobat shows. So my first guess is that the first document has some issues and different readers try to overcome those issues with different results. PDFsam is among the ones where data is not read except from page 1 and 9. 
I see also those files are created from PDFsam, one suggestion is to download the latest version and try to re-do the whole process starting from the original document/documents.
I will try to take a closer look.

**Comment by Andie42** [comment]
Yes! (I think I should've told you this...) Both documents were previously merged by pdfsam. 

I'll follow your advice I let you know what happened.

Thanks for your support!

**Comment by Andie42** [comment]
It worked. Thanks again. (Pdfsam is pinned to my taskbar!)
