### ISSUE TITLE
During merging (and maybe even some other operations): Write directly to the output file, not to the temporary one

### ISSUE THREAD

**Issue by georgthegreat** [torakiki/pdfsam#223]
At the time, on Windows, any PDF being merged is first being written to some temporary file (located on `C:\` drive), and then moved to the output file.

This requires file to be written twice when output file is not located on drive `C:\`. That's weird,

**Comment by ediweissmann** [comment]
I guess this is more of a problem when dealing with large files and when the destination is not on the same drive as the temp folder.

**Comment by georgthegreat** [comment]
Yes, I'm dealing with huge PDF files (let's say hundreds of megabytes), and my laptop drive is still HDD, not SSD.
