### ISSUE TITLE
Table of contents in Hebrew language

### ISSUE THREAD

**Issue by talmarsh** [torakiki/pdfsam#226]
Table of contents created from files in Hebrew text is flipped, text coding issue.

Example
> _Expected_
> 03 - 2-ציר הורמון הגדילה
> _Result_
> 03 - 2-הלידגה ןומרוה ריצ

_Otherwise perhaps the most useful and best program for a student._

**Comment by torakiki** [comment]
Would you be available to run some test if we send you a test release to verify this issue is fixed?

**Comment by talmarsh** [comment]
Sure thing.

**Comment by torakiki** [comment]
Here is the link https://www.dropbox.com/s/89ayvtwol3u8gwh/pdfsam-3.3.1-SNAPSHOT-bin.zip?dl=1
It should solve RTL and Bidi text but it doesn't seem to fully fix your case, specifically the `-` symbol seems to create problems...

**Comment by talmarsh** [comment]
- I can confirm that text coding is fixed. This for me turns this feature
from useless -> to immensely useful.

*Samples:*
In case the start of filename has number then *English *it goes *LTR*:
Filename
[image: Inline image 1]
PDF
[image: Inline image 2]

In case the start of filename has number then *Hebrew *it goes *RTL*:
Filename
[image: Inline image 4]
PDF
[image: Inline image 3]

** "Not great" was in the original filename, the program functions great
here IMO :)*

Thanks a lot!

**Comment by torakiki** [comment]
Great, thanks for testing this!
