### ISSUE TITLE
Big files after split

### ISSUE THREAD

**Issue by haukefrahmann** [torakiki/pdfsam#229]
Files after splitting an text pdf with multiple sites are 1MB in minimum file size.
why that? ist just text in there.

**Comment by torakiki** [comment]
It could be embedded fonts or something else, what was the original size? Was PDFsam Basic doing the split?

**Comment by haukefrahmann** [comment]
original size was a few bytes more. 
it's just driving me crazy cause I need the pdfs as small as possible.
split was done with the basic version.

**Comment by torakiki** [comment]
The probable explanation is that the doc has an embedded font that will have to be embedded to each resulting doc from the split task. The doc looks like _just text_ but the PDF format is more complex than that and the files can have resources embedded, fonts in this case.
You can try compressing the resulting files using [Sejda](http://www.sejda.com/compress-pdf) but given they are just text I doubt you will get any improvement.

**Comment by haukefrahmann** [comment]
okay, i will look into it. the original pdf ist created with a php class
