### ISSUE TITLE
Bookmarks change view to 6400%

### ISSUE THREAD

**Issue by tdalon** [torakiki/pdfsam#231]
Issue already reported/fixed? in the past [#191](https://github.com/torakiki/pdfsam/issues/191).
I have this issue with v3.3.0 (portable installation).
When retaining bookmarks, each time I click on a bookmark the view zoom is set to 6400%.

**Comment by torakiki** [comment]
Could you please try to run the task with and without compression and let me know if the issue is always there?

**Comment by tdalon** [comment]
That's it! Without compression no bug. Unfortunately the default option is with compression and there it has the bug.

**Comment by torakiki** [comment]
Ok, then it's fixed here https://github.com/torakiki/sambox/commit/0facaef0b2bbbf3f103b52f0a016241fda16da09 and will be live with the next release.
Thanks for reporting this
