### ISSUE TITLE
Latest version of PDFSam for Java 1.7.x 

### ISSUE THREAD

**Issue by Copones** [torakiki/pdfsam#233]
Hi, 

I've noticed that the 3.3.0 version needs java 1.8 or later to work.

Due to compatibility reasons with another software, I must keep java 1.7 in my computer.

So, what is the latest version that support java 1.7?

Thanks in advance.

**Comment by torakiki** [comment]
It's this https://github.com/torakiki/pdfsam-v2/releases but I would suggest against it, it's quite old and unsupported. One workaround to use version 3 is to find a portable version of Java 8, unzip somewhere and modify the `pdfsam.bat` script (in the `bin` subdirectory) to point to the unzipped Java 8, this way you'd leave Java 7 as default on your computer but PDFsam would use the portable Java 8.
