### ISSUE TITLE
Request to update launchpad

### ISSUE THREAD

**Issue by alanlivio** [torakiki/pdfsam#236]
Hello.
The pdfsam repository in the launchpad[1] only has the deb packages for 1.1.4-3 version.
So, run "apt-get install pdfsam" in a Ubuntu distro only install the 1.1.4-3 version and no the 3 version.
Are maintainers intent add new deb packages in launchpad?
Best regards.

[1] https://launchpad.net/pdfsam

**Comment by torakiki** [comment]
We are not the maintainers of that repo. We create a .deb for each release but I am afraid it won't be accepted in an official Debian repo where they have stricter rules. It's in our TODO list to have PDFsam and Sejda properly debianized and added to the Ubuntu repo but we haven't done that yet. We would be happy to help in case the Launchpad repo maintainer would like to properly debianize the current version.

**Comment by alanlivio** [comment]
It seems that on launchpad the maintainer is Andrea Vacondio[2].

[1] (https://launchpad.net/pdfsam)
[2] (https://launchpad.net/~andrea-vacondio)

**Comment by torakiki** [comment]
Yes but Andrea Vacondio (me) is not the one who built those debs... we use the Launchpad project only for translations and somehow the packages have been synchronized there but I'm not the one who created them.

**Comment by alanlivio** [comment]
I not realize that was you, sorry.
Thanks by the answer.

**Comment by KaKi87** [comment]
Hi,

> It's in our TODO list to have PDFsam and Sejda properly debianized and added to the Ubuntu repo but we haven't done that yet.

How is this going ?

Thanks

**Comment by KaKi87** [comment]
Hi,

A few months ago, I started developing a tool named [dynapt](https://git.kaki87.net/KaKi87/dynapt) to automatically fetch updates through APT for packages that don't provide an APT repository.

As I've been upgrading PDFSam through it for quite some time now, I just published my first pre-release of it, which you can download and set up from [this tutorial](https://gist.github.com/KaKi87/f620788e9901abbfef4978eb7ad358b4).

For PDFSam specifically, replace the following configuration line :

```json
    "apps": []
```

With the following :

```json
    "apps": [
        {
            "name": "PDFsam",
            "github": {
                "repo": "torakiki/pdfsam"
            }
        }
    ]
```

For questions or issues, please submit a comment on the tutorial page.

Thanks
