### ISSUE TITLE
Installer doesn´t apply most msi properties in Windows 10

### ISSUE THREAD

**Issue by STW-Ahartung** [torakiki/pdfsam#239]
I´m about to roll-out pdfsam in my organization, using this installation-string:
msiexec.exe /i pdfsam-v3.3.0.msi /qn /norestart /quiet CHECK_FOR_UPDATES=false CHECK_FOR_NEWS=false PREMIUM_MODULES=false PLAY_SOUNDS=false DONATE_NOTIFICATION=false LOCALE_CODE=de SKIPTHANKSPAGE=yes

Runs on Windows 7 fine. Everything as expected.
Running it on Windows 10 doesn´t apply most msi properties.
In detail.. after installation succeeded the following settings are somehow enabled:
PREMIUM_MODULES, PLAY_SOUNDS, DONATE_NOTIFICATION, CHECK_FOR_NEWS, CHECK_FOR_UPDATES
These two properties get applied correctly:
SKIPTHANKSPAGE, LOCALE_CODE

I´ve also edited the msi properties directly in the msi with orca.
Tried to install the edited msi through double-click.
Same problem - works on Windows7, doesn´t work on Windows10.

**Comment by torakiki** [comment]
There was an issue related to this https://github.com/torakiki/pdfsam/issues/217 it will be released with 3.3.1 but It doesn't seem to be the same thing you are experiencing... given you set everything to false, they should be picked up, I'll make some test on Win10

**Comment by mytrix** [comment]
Any news with this issue? I have the same problem with Windows 10. Most of options are not applied.
MSI transformed via MST (Orca)

**Comment by torakiki** [comment]
This should be fixed. For every property you set through the MSI you should see a corresponding java prop set in the file `pdfsam.l4j.ini`. These are defaults values so, if the user has already a version of PDFsam installed and he already set a value for those settings, user's values have precedence.

**Comment by torakiki** [comment]
This should be fixed. 
A note on existing settings from a previous install, if you run the application once with `--clean` or `-c` it will clean up all the previous settings and pick up the defaults

**Comment by torakiki** [comment]
This was actually fixed here https://github.com/torakiki/pdfsam/commit/19d4433a5432e532a3e05fe3476347bbd2db4e70
