### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by DazSeaton** [torakiki/pdfsam#241]
It would be handy if you could set each function defaults. i.e  in rotate the compress output files is always on by default. If you drop a 1.3 pdf and try and convert it, you get an error, so i tend to turn it off.

Alternatively  if the software could detect an older version file and not try to compress it, that would be even better. i.e. compress if version 1.5 or over.

**Comment by torakiki** [comment]
To achieve something similar to what you asked you can save a workspace with those defaults and set it as default workspace at startup in the Settings panel.
Regarding the specified use case it shouldn't fail, if you open a 1.3 and compression is on, it should generate a compressed 1.5 without any issue, could you provide a sample PDF file I can test? Maybe the issue is something different

**Comment by DazSeaton** [comment]
Hi Andrea,
OK thanks.
Next time it fails I will send a file in. Can’t seem to replicate the error at the moment.
Regards
Darren


Darren Seaton
CAD Draughtsman
[cid:image006.png@01D11DF9.04BCCF80]

Omega Red Group Ltd
Dabell Avenue | Blenheim Industrial Estate | Bulwell | Nottingham | NG6 8WA
T 0115 876 7734 | F 0115 876 7766 | M
E dseaton@omegaredgroup.com<mailto:dseaton@omegaredgroup.com> | W www.omegaredgroup.com<http://www.omegaredgroup.com/>

Please consider the environment before printing this email

**Comment by DazSeaton** [comment]
Hi Andrea,
If I drop this file into SPLIT, it gives an error unless I untick compress. (see attached)

This is what I was referring to before.
Regards,
Darren Seaton
CAD Draughtsman
[cid:image006.png@01D11DF9.04BCCF80]

Omega Red Group Ltd
Dabell Avenue | Blenheim Industrial Estate | Bulwell | Nottingham | NG6 8WA
T 0115 876 7734 | F 0115 876 7766 | M
E dseaton@omegaredgroup.com<mailto:dseaton@omegaredgroup.com> | W www.omegaredgroup.com<http://www.omegaredgroup.com/>

Please consider the environment before printing this email

**Comment by torakiki** [comment]
There is no attachment. If you could verify this is still and issue and in case provide the file we will investigate, thanks
