### ISSUE TITLE
Use leading zeros for file names

### ISSUE THREAD

**Issue by larsen0815** [torakiki/pdfsam#243]
When you split a PDF with 123 pages after every page, you will get files that start with "1_" and continue with "10_". It would be better to have the files start with "001_" in this case so the files get sorted correctly.

**Comment by torakiki** [comment]
Maybe we can improve to autodetect the length but you can use one of the custom prefix to achieve that, here some detail http://www.pdfsam.org/customize-file-names/

**Comment by larsen0815** [comment]
Thx, I hadn't seen this before.

"[FILENUMBER###]" would be a good default IMHO.
