### ISSUE TITLE
Broken pages when merging large PDF files (200+pages)

### ISSUE THREAD

**Issue by joedf** [torakiki/pdfsam#244]
Causes "Error while processing a page" in Adobe Reader DC.
Using PDFsam-Basic v3.3.2

**Comment by torakiki** [comment]
Can you send us the files so we try to reproduce?

**Comment by joedf** [comment]
sadly, I no longer have them. I resorted to https://smallpdf.com/merge-pdf

**Comment by torakiki** [comment]
ok, thanks anyway... I'm afraid we can't do much without the docs
