### ISSUE TITLE
Unable to install into correct destination folder

### ISSUE THREAD

**Issue by mwfidu** [torakiki/pdfsam#245]
While installing pdfsam 3.3.2 i chose advanced options and a non standard destination folder (F:\win7programs), still pdfsam was installed to the default destination folder on C:\programs. (Windows 7 x32)

**Comment by torakiki** [comment]
This was using the MSI? https://github.com/torakiki/pdfsam/releases/download/v3.3.2/pdfsam-v3.3.2.msi

**Comment by mwfidu** [comment]
No, I had used the .exe windows installer I got via www.pdfsam.org/download-pdfsam-basic/ (and double- and triplechecked I didn't do it wrong).
I now tried using the .msi and that one worked just fine! :)

**Comment by torakiki** [comment]
The .exe should work fine too now
