### ISSUE TITLE
"Check for news at startup" is eating up memory

### ISSUE THREAD

**Issue by nicodorn** [torakiki/pdfsam#246]
If the option "Check for news at startup" is checked, PDFsam is endlessly eating up memory until one closes the programme. An example (it won't stop at 2GB):

![leak](https://cloud.githubusercontent.com/assets/14349333/26778496/cd01e3c0-49e1-11e7-8b60-127c05587c70.png)

Unchecking the option and restarting the programme solves the problem. Then PDFsam uses about 190 MB after startup, and about 270 MB after usage (at least on my machine). By the way: "Check for updates at startup" does not trigger the problem.

Environment:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Kubuntu 16.10, Kernel 4.8, 64bit

**Comment by torakiki** [comment]
Does this happens every time you start it with the flag on? 
Please have a try with an more recent JVM

**Comment by nicodorn** [comment]
Yes. (So happy I found the reason. :-))

**Comment by dinagu** [comment]
This Problem still exists in Version 4.0.5 (at least for me). Starting pdfsam with "Check for news at startup" enabled leads to >16GB RAM used within ~20 seconds after starting the program.

**Comment by torakiki** [comment]
And this memory spike doesn't happen if you disable the check for news at
startup, correct? What OS are you using? Are the news pulled correctly when
the check is enabled?

Il giorno lun 2 dic 2019 alle ore 01:17 dinagu <notifications@github.com>
ha scritto:

**Comment by dinagu** [comment]
Correct, if I disable the check for news at startup it behaves normally and does not consume infinite amounts of memory. 
I am using Arch Linux.

> Are the news pulled correctly when the check is enabled?

While testing this I realized, that the problem only occurs if there are unread news(i.e. the "What's new" button is green). That means I can stop the memory leak by clicking on "What's new". 

By reducing the value of
`<entry key="latest.news.id" value="61"/>`
in `.java/.userPrefs/org/pdfsam/user/news/prefs.xml` and restarting pdfsam I can reproduce the memory leak.

**Comment by torakiki** [comment]
Ok, we'll look into it, thanks for the details.

**Comment by dinagu** [comment]
After playing around a bit I found that I could also trigger the leak by provoking an error (by trying to split an invalid pdf file), so that the "Application Messages" button is red and shakes.

I am not sure that the actual leak is in pdfsam, because it only happens when I use the amdgpu driver (I am using a Radeon RX580). Using the vesa driver I was not able to reproduce the problem.

**Comment by torakiki** [comment]
Thanks for investigating this. I will take a look but to be honest there isn't much going on in that area.. just a http call and a json parsing, not much that could lead to a 16GB ram consumption but I'll take a look...

**Comment by dinagu** [comment]
Thanks, but its probably a bug in mesa or something. I found a similar report that obs-studio triggers a memory leak in mesa here: https://gitlab.freedesktop.org/mesa/mesa/issues/1426

**Comment by torakiki** [comment]
Ok, thanks for investigating.
