### ISSUE TITLE
Feature Req: Whiteout Tool Remain Enabled & Keyboard Shortcuts for Common Tools

### ISSUE THREAD

**Issue by CH1NNV** [torakiki/pdfsam#247]
It would be really handy if when using the Whiteout tool that it remained selected/enabled after performing a Whiteout.

Quite frequently, I need to tidy lots of old scanned documentation / engineering drawings and this would drastically reduce the time spent.

Presently the behaviour is such, that once you have selected Whiteout, you can Whiteout one area and then need to select the tool again from the toolbar.

Alternatively (or in addition to this), keyboard shortcuts for what I consider common use tools such as Whiteout & Select Text would be really useful - or programmable keyboard shortcuts?

Currently using the Enhanced 4 v1.7.

**Comment by torakiki** [comment]
Please use this form http://www.pdfsam.org/support-pdfsam-enhanced/ as it goes directly to the PDFsam Enhanced team

**Comment by CH1NNV** [comment]
+1

Cheers Torakiki, realised after I opened the issue I was in the wrong place so closed this straight away.  Sorry for the mix up!
