### ISSUE TITLE
Merge function doesn't remember "Overwrite" check box

### ISSUE THREAD

**Issue by mwalkeden** [torakiki/pdfsam#248]
We have recently got the updated version of PDF Split merge and have noticed that every time go to select the destination file it asks if I want to override it as it already exists.

Even after checking the box it still asks whenever I have something that I am wanting to merge.
And when I close the program, it doesn’t remember that the box was checked.

Can this be looked at?

Thank you!

**Comment by torakiki** [comment]
There is now a setting to drive the initial state of the Overwrite checkbox and, if checked, the application doesn't ask a confirmation
