### ISSUE TITLE
Replace icons with High DPI/Vector Icons

### ISSUE THREAD

**Issue by Masterxilo** [torakiki/pdfsam#249]
PDFSAM looks nice on a high dpi display, except for the icons on the top left and left side which are blurred/interpolated:
![pdfsamblur](https://user-images.githubusercontent.com/2378665/26897244-2acffbbc-4bc8-11e7-91ba-956efd3f6b89.png)

It would be nice if those would look crisp.

**Comment by torakiki** [comment]
This should be fixed in version 5
