### ISSUE TITLE
Sorting in merge function

### ISSUE THREAD

**Issue by HerbieOza** [torakiki/pdfsam#250]
When dragging pages to merge screen, the last page is showing up on top of the list. For example pages 1-100 to merge, page 100 shows up first, followed by 1, 2, 3..............99.

![sam2_2](https://user-images.githubusercontent.com/22058010/26923324-0cc3c8cc-4c42-11e7-8ed2-5522bd7ebde7.JPG)
![sam1_2](https://user-images.githubusercontent.com/22058010/26923323-0cc0ed82-4c42-11e7-8f99-375e61f5d1d5.JPG)

**Comment by marekmatula** [comment]
I had the same problem. It depends on the source of drag and drop. Windows explorer randomly mix file order.
You can use Double Commander/Total Commander instead of Explorer.
It works fine for me.
