### ISSUE TITLE
drag and drop in merge is not working

### ISSUE THREAD

**Issue by ase2003** [torakiki/pdfsam#251]
# drag and drop in merge is not working

**Comment by torakiki** [comment]
Can you give us more details? OS and Java version and what happens?
DnD should work.

**Comment by ase2003** [comment]
all DnD in all Feature is not working
OS: windows 7
Java version : version 8 update 131 (build 1.8.0_131-b11)

**Comment by torakiki** [comment]
Is there any error message in the log window? Could you try starting PDFsam using the `bat` script in the `bin` directory, this will keep a terminal window open, is there any useful message there?

**Comment by ase2003** [comment]
> Is there any error message in the log window? Could you try starting PDFsam using the bat script in the bin directory, this will keep a terminal window open, is there any useful message there?

Hello
This way DnD works perfectly but when i use .exe file it is not working

**Comment by torakiki** [comment]
Ok, and when you in the two different ways, in the Info panel, is the Java version you see the same?

**Comment by ase2003** [comment]
Yes it is the same version 
![1](https://user-images.githubusercontent.com/29523350/28610905-135e8eb8-71fb-11e7-8d5f-5010ce922f4d.jpg)
.bat file 
![2](https://user-images.githubusercontent.com/29523350/28610970-4d8f22a0-71fb-11e7-8af7-6c2dabe6913c.jpg)
.exe file

**Comment by torakiki** [comment]
Could you please verify if this happens with the latest version?
