### ISSUE TITLE
Suggested enhancements to Workspace>Save

### ISSUE THREAD

**Issue by AlisterH** [torakiki/pdfsam#252]
(1) The Workspace>Save feature is what other programs refer to as "Save as" i.e. it always asks what to save the workspace as.  When you have opened an existing workspace it would be good if there was a true "Save" feature, which overwrote the open workspace without you having to specify it.

(2) Also, on Windows the "Save" dialog opens in "This PC".  It would be much better if it opened in the working directory or if you have opened a workspace, in the location of the workspace (I'm guessing this is the same as the working directory).

Note that even if (1) isn't implemented, (2) would make it much quicker to select the same workspace to overwrite it.

**Comment by torakiki** [comment]
I implemented (2) for this. Now `Save` opens the file chooser dialog suggesting the latest loaded workspace (if any). I think this keeps things simple and pretty much solves both (1) and (2).
