### ISSUE TITLE
Normalize page mixes width and height

### ISSUE THREAD

**Issue by dumblob** [torakiki/pdfsam#253]
The tooltip of "Normalize pages size" says it shall resize all pages to have the same **width** as the first page. I have several PDFs (some produced by PowerPoint 2016 and some by Inkscape 0.92) with wildly varying page sizes (no standard A4, nothing like that).

After merging the PDFs, I get an incorrectly normalized PDF - some pages have different width.

It seems though, the pages are normalized according to the height (but I didn't measure it, it's just a guess based on my sight 😉 ).

I would suggest enhancing this feature by offering the choice to normalize according to height or normalize according to width. Both are useful.

**Comment by torakiki** [comment]
Could you provide a couple of PDFs we can test with?

**Comment by dumblob** [comment]
[test00.pdf](https://github.com/torakiki/pdfsam/files/1175853/test00.pdf)
[test15.pdf](https://github.com/torakiki/pdfsam/files/1175854/test15.pdf)
You can add these in this order in the "Merge" list, then select "Normalise page size" and select a destination file and click "Run".

**Comment by torakiki** [comment]
Ok, I've be able to reproduce it with the latest PDFsam 3.3.2 and it's fixed in the latest Sejda 3.2.18 https://github.com/torakiki/sejda/releases/tag/v3.2.18
It will be picked up with the next PDFsam release
