### ISSUE TITLE
Feature request - Split function to include leading zeros in output filenames

### ISSUE THREAD

**Issue by RJMilton** [torakiki/pdfsam#258]
Currently the pdfs are split an numbered:
1_Name
2_Name
...
10_Name

A preferable way to allow sorting of files by filename would be to include leading zeros ie:
01_Name
02_Name
...
10_Name

Thank you for PDFsam, it has been very helpful to me over the past year.

**Comment by torakiki** [comment]
You can use the prefix field to customize the output names, have you looked
at this? http://www.pdfsam.org/customize-file-names/

**Comment by RJMilton** [comment]
Thank you! That is perfect.
