### ISSUE TITLE
Add preview of PDF pages to PDFSam Basic

### ISSUE THREAD

**Issue by yamlfd** [torakiki/pdfsam#264]
Since 3.x the software is no longer showing page previews if you'd like to merge PDF files. It is very important to see a **small** preview image if you merge pages or you cannot order them properly.

Please add this feature back into the basic version.

**Comment by torakiki** [comment]
The feature has been moved to [PDFsam Visual](http://www.pdfsam.org/pdfsam-visual/) where pretty much every task has pages thumbnails

**Comment by yamlfd** [comment]
We do not want to buy pdf visual. This issue was opened for pdfsam basic! Please move the case back.

**Comment by yamlfd** [comment]
Can you reopen the issue, please? This feature is highly important für PDFSam Basic.

**Comment by torakiki** [comment]
That's our business model, visual features are premium at a very affordable price and funds provided by PDFsam Visual allow us to keep the business running and PDFsam Basic free and actively developed. There isn't currently any plan to change this.

**Comment by yamlfd** [comment]
This will not help selling visual version!

I only talk about a small preview images and not these many features visual has.

I cannot invest 30€ x 300 computers = 9000€ only for a small feature that may be worth 1-2€ per device and is only used once per month by users.

I already written your MSI installer and contributed this way.

**Comment by glyons** [comment]
> 
> 
> That's our business model, visual features are premium at a very affordable price and funds provided by PDFsam Visual allow us to keep the business running and PDFsam Basic free and actively developed. There isn't currently any plan to change this.

Our business model!  No Preview in PDFSam is just inconvenience especially when splitting pages. You should re-think that model.  Uninstalling PDFSam :-(
