### ISSUE TITLE
MSI setup registry bug "Software/PDFsam Basic"

### ISSUE THREAD

**Issue by yamlfd** [torakiki/pdfsam#265]
There is a registry key "installed" that will be set, but it cannot set because of a forward slash that should be  a backslash "Software/PDFsam Basic"

![2017-09-29_173258](https://user-images.githubusercontent.com/4450722/31023502-4ed7fa50-a53c-11e7-80bf-1853f7e5ec87.png)

**Comment by DavidHaslam** [comment]
I too noticed that last week.
