### ISSUE TITLE
ClearStatisticsButtonTest failing on build

### ISSUE THREAD

**Issue by doc-E-brown** [torakiki/pdfsam#266]
Hi,
I am following the [build instructions](https://github.com/torakiki/pdfsam/wiki/Build-and-run) and am having issues with ClearStatisticsButtonTest failing.  My desktop environment is as follows:

* Solus Linux
* OpenJDK 8.144 release 11
* Apache-maven 3.5.0  release 3
* PDFSam 3.3.2

When I run:
`mvn clean install -Prelease`

I get the following error about not calling a mock:

-> at org.pdfsam.ui.dashboard.preference.ClearStatisticsButtonTest.eventSent(ClearStatisticsButtonTest.java:59)
Actually, there were zero interactions with this mock.

I have uploaded a copy of the surefire-report for the failure

[TEST-org.pdfsam.ui.dashboard.preference.ClearStatisticsButtonTest.xml.txt](https://github.com/torakiki/pdfsam/files/1366806/TEST-org.pdfsam.ui.dashboard.preference.ClearStatisticsButtonTest.xml.txt)

I am able to successfully build and run pdfsam using
`mvn clean install -Dmaven.test.skip=true -Prelease`

Thanks!

**Comment by torakiki** [comment]
Does this consistently happen? The build seems fine on Travis and AppVeyor and on my ubuntu
https://travis-ci.org/torakiki/pdfsam
https://ci.appveyor.com/project/torakiki/pdfsam
