### ISSUE TITLE
suggestion: generated PDF file name

### ISSUE THREAD

**Issue by vkuwabara** [torakiki/pdfsam#267]
My suggestion is about file name after splitting a PDF. The only option available is to add a number and underline before the prefix you want. For example: 1_pdfsam_FILENAME, 2_pdfsam_FILENAME. I suggest to add a config to this file name thus you can rename as FILENAME_1_pdfsam, or FILENAME_pdfsam_1.

**Comment by torakiki** [comment]
Have you seen this? http://www.pdfsam.org/customize-file-names/

**Comment by vkuwabara** [comment]
Thank you. It was not very user friendly on the software, and I had to mess around with the commands to understand how it works
