### ISSUE TITLE
Cannot read some PDFs, shows "Please wait..." message

### ISSUE THREAD

**Issue by jkister** [torakiki/pdfsam#268]
When splitting or extracting one particular PDF with PDFSam 3.3.3, instead of displaying the document, it will show a message:

> Please wait...
> If this message is not eventually replaced by the proper contents of the document, your PDF
> viewer may not be able to display this type of document.

Adobe Acrobat Reader DC 2017 Release Version 2017.012.20098 can display the document correctly.

Please contact me for dropbox URL or direct email; i cannot attach the PDF here because it has sensitive information on it.

**Comment by torakiki** [comment]
Hi Jeremy,
please send it to info@pdfsam.org and I'll take a look

**Comment by jkister** [comment]
sent, thanks.

**Comment by torakiki** [comment]
Hi Jeremy,
that PDF content is an XFA form, a technology that PDFsam doesn't support and that was deprecated in the PDF version 2.0. I'm afraid we can't help.
