### ISSUE TITLE
PDFSam does not recognize installed Java

### ISSUE THREAD

**Issue by pstrg** [torakiki/pdfsam#273]
Windows 10 64 bit / PDFsam Basic

PDFsam seems not to be compatible with the latest Java 9.0.1 (64 bit) which I have on the machine,
Tried to use the program but PDFsam said "Cannot find Java Runtime Environment / This application requires a Java Runtime Environment 1.8.0" and opened a browser tab to download.

Tried to reinstall PDFsam.
An older version of Java (8 update 60) was downloaded an installed so that I have now two versions of Java on the machine (but PDFsam works).

**Comment by torakiki** [comment]
Is this happening with the latest version of PDFsam Basic?

**Comment by pstrg** [comment]
To answer your question.
On another machine I had *PDFsam Basic 3.3.2* installed and *Java 9.0.1* -
PDFsam *did not run*.

Downloaded the latest PDFsam Basic installer but have had problems after
install:

1) The installer forcedly installed (did not ask) *Java 8 update 60*
(current one is Java 8 *update 151*).
2) As a result, I had then both Java 9.0.1 *and *Java 8 update 60.
3) So that I could check whether PDFsam 3.3.5 ran under Java 9.0.1, tried
to uninstall Java 8 update 60 but that was not possible - the uninstall
process *froze *for hours and I had to manually end it with Task Manager.
4) After having tried a number of times to uninstall the version PDFsam
installed, decided to install Java 8 *update 151* (the current one).
5) The update successfully installed and *removed* the problematic update
60.
6) Next I managed to successfully *uninstall *Java 8 update 151.
7) Started PDFsam Basic and noted that it ran with Java 9.0.1 normally.

Given my painful experience, may I suggest:
- PDFsam should not automatically install Java if a newer version is
already there;
- If for same reason it's not possible to check whether a fitting Java is
installed, at least it should not install a very old version like it did.

I use PDFsam very sparingly but when I used it found it to be very useful
and quite complete.

Best regards,
PB

**Comment by torakiki** [comment]
You can install using the MSI, in this case Java is not installed, it just informs you if it could find a correct version. The downloader will be updated soon to correctly handle the case you described
