### ISSUE TITLE
pdfsam basic is not opening in my windows xp sp3, shows error7

### ISSUE THREAD

**Issue by AmitNagrath** [torakiki/pdfsam#277]
Hello Sir/Madam ! 

Sir/Madam pdfsam basic is not opening in my windows xp sp3, shows error7 ! Thanks

**Comment by torakiki** [comment]
Java 8, the language PDFsam Basic is written, stopped supporting Windows XP in 2014 and we don't support it as well. That said, it _should_ work, is it the installer or the application giving the error message? Have you tried the ZIP bundle? https://github.com/torakiki/pdfsam/releases/download/v3.3.5/pdfsam-3.3.5-bin.zip just unzip and double click the .exe
