### ISSUE TITLE
Split file size is as large as original document size

### ISSUE THREAD

**Issue by screed01** [torakiki/pdfsam#281]
When splitting a PDF document by page, the file size of each page is the running total size of the pages.  For example, splitting a 21MB file with 21 pages, page 1 is 1MB, page 2 is 2MB, page 3 is 3MB... and page 21 is the original file's 21MB.

I cannot find any settings that prevent this from occurring.

**Comment by torakiki** [comment]
We described [here](https://pdfsam.org/pdf-format/i-split-my-pdf-but-the-resulting-files-are-so-big/1910/) why sometimes the resulting files are bigger then expected. What you described looks like a case that we don't handle correctly, if you could provide the file we can take a look.
