### ISSUE TITLE
PDFSAM_JAVA_PATH not working

### ISSUE THREAD

**Issue by sramane** [torakiki/pdfsam#282]
I declare a Windows 7 environment variable:

PDFSAM_JAVA_PATH = C: \ Program Files \ jre1.8.0_161 \ bin

when I run the pdfsam.exe program, I get an error message

"This application requires a Java Runtime Environment 1.8.0"

**Comment by torakiki** [comment]
I should take a look at the code but if I recall correctly you should set it to 
`C:\Program Files\jre1.8.0_161`
have you tried it?

**Comment by torakiki** [comment]
Ok, I'll test it, You are using Windows 7 and the latest PDFsam Basic 3.3.5, correct?

**Comment by sramane** [comment]
Yes, Windows 7 and the latest PDFsam Basic 3.3.5, because worked with the old version 3.3.4.

**Comment by torakiki** [comment]
I just tested on Windows 7 with a portable Java in c:\tmp\Java and everything seems to work as expected... not sure what could be the issue for you

![pdfsam_java_path](https://user-images.githubusercontent.com/3884479/37760027-c7b22dea-2db5-11e8-92e1-d26eb1b1bcfd.png)

**Comment by sramane** [comment]
i used an embedded Java version, with machine Windows system variable, not an user variable

**Comment by torakiki** [comment]
And is it working now using a user variable?
