### ISSUE TITLE
Suggestion: Context menu option > Append

### ISSUE THREAD

**Issue by apostolovski** [torakiki/pdfsam#283]
Add a right-mouse click context "PDF Append" option

After selecting multiple PDF files + right clicking on them + selecting "PDF Append": 
Show the a window where I can sort the files
Append the 2nd, 3rd, 4th etc file in that order to the first file.

**Comment by torakiki** [comment]
There is a contex menu entry in the Send To -> PDFsam where you can select the Merge module and merge the PDF files, does it work for you?
