### ISSUE TITLE
"Cannot Display PDF" on Andorid phone

### ISSUE THREAD

**Issue by madcom13** [torakiki/pdfsam#284]
Hello guys,
I've tried to create a merged PDF files from several seperate files. Some of the files was made using photoshop as an insert to the original document. Then merged the files.
The pdf files open just fine using google chrome on Laptop/Desktop. However it's not the case on Android phone. it says: "Cannot Display PDF" 

 Any ideas why?
![whatsapp image 2018-03-12 at 11 32 42](https://user-images.githubusercontent.com/37017881/37266223-6919c968-25eb-11e8-8e9a-af8000894681.jpeg)

**Comment by torakiki** [comment]
Do all the original PDF files open correctly on Android?
