### ISSUE TITLE
PDFSam for JAVA 7?

### ISSUE THREAD

**Issue by redbob365** [torakiki/pdfsam#285]
PDFSam is a great tool, but we have issues about Java 8. Several working apps here don't work with Java 7. Is there some ancient PDFSam  Version that runs with Java 7?

Thanks

**Comment by torakiki** [comment]
PDFsam requires Java 8. What you can do is to install a [Java portable](https://portableapps.com/apps/utilities/java_portable) so your Java 7 stays the default for the other apps and use the environment variable PDFSAM_JAVA_PATH, you can read about it [here](https://github.com/torakiki/pdfsam/wiki/Properties-and-arguments) and take a look at [this](https://github.com/torakiki/pdfsam/issues/282) to see how to set the variable

**Comment by redbob365** [comment]
Thanks, @torakiki, it worked like a charm! I am able to deploy PDFSAM im my network, just enabling by login script this variable "set PDFSAM_JAVA_PATH", redirecting to a preinstalled Java version within a portable Mozilla :-)
