### ISSUE TITLE
[Feature] Add ability to specify suffix for split

### ISSUE THREAD

**Issue by tomekpiatek** [torakiki/pdfsam#286]
I have a PDF that I want to split. The output files need to have a suffix, for example -rev_B, or similar. There is no way to do that. Please add the ability to specify a suffix in a similar fashion to how we can add a prefix now.

**Comment by torakiki** [comment]
Have you looked at the runtime keywords you can use? https://pdfsam.org/customize-file-names/
Can you give an example of the expected resulting names?

**Comment by tomekpiatek** [comment]
OK, my bad, I didn't realise that there was a basename substitution available. That will do the trick as I can do things like [BASENAME]-some_suffix. Thanks for getting back to me and making this clear. I shall read the docs more carefully next time. Consider my request resolved.
