### ISSUE TITLE
PDFsam Visual 1.1.8 - Merge PDF - Newly Added Files Don't Get "More Options" Check-boxes Applied to Them

### ISSUE THREAD

**Issue by rootMBX** [torakiki/pdfsam#288]
If you add pages using the “Merge” module, modify the features/checkboxes at the bottom (like “Include only specific page ranges”), and then Add More Pages, the newly added pages do not get the same features that are set at the bottom.

![pdfsam visual - merge - bug](https://user-images.githubusercontent.com/911076/39709816-c4152e2e-51cf-11e8-8cbc-3fb937d9af1a.png)

**Comment by torakiki** [comment]
Thanks for reporting, we will address these internally as this is a PDFsam Visual issue while this is the PDFsam Basic issue tracker
