### ISSUE TITLE
PDFsam Visual 1.1.8 - Combine and Reorder Pages - "No Pages Added Yet" Message Does Not Disappear In Certain Cases

### ISSUE THREAD

**Issue by rootMBX** [torakiki/pdfsam#289]
The “No Pages Added Yet” message/icon still appears when using the “Add More Files” button/feature or dragging and dropping from Windows File Explorer after the initially added documents have been cleared.

![pdfsam visual - cosmetic bug](https://user-images.githubusercontent.com/911076/39710315-53b27c20-51d1-11e8-812b-eef5f2dbd342.png)

**Comment by torakiki** [comment]
Thanks for reporting, we will address these internally as this is a PDFsam Visual issue while this is the PDFsam Basic issue tracker
