### ISSUE TITLE
org.pdfsam.guiclient.exceptions.CheckForUpdateException: java.net.UnknownHostException: www.pdfsam.org

### ISSUE THREAD

**Issue by Omcsesz** [torakiki/pdfsam#290]
When starting the program, I get the following error message (see attachment). Any ideas why this is happening?
[PDF SAM error log.txt](https://github.com/torakiki/pdfsam/files/2001801/PDF.SAM.error.log.txt)

OS: Win 7 64-bit
PDF SAM version: 2.2.2.
Java version: Java(TM) SE Runtime Environment 1.8.0_161-b12

**Comment by Omcsesz** [comment]
OS: Win 7 64-bit
PDF SAM version: 2.2.2.
Java version: Java(TM) SE Runtime Environment 1.8.0_161-b12

**Comment by torakiki** [comment]
We don't support that version anymore, it's very old, please update to a recent version.
