### ISSUE TITLE
Providing SHA512 and SHA256 checksums

### ISSUE THREAD

**Issue by einsteinsfool** [torakiki/pdfsam#291]
For now, after I download a file an attacker can intercept it and swap it with a modified malicious file.

It would be cool if for every file both SHA512 and SHA256 sums were provided so users can verify if they have the correct file.

The sums would be preferably both on the pdfsam.org download page and here, on GitHub. So even if pdfsam.org is compromised (hacked), then one can check sum from here.

As a sidenote, both MD5 and SHA1 are breaked and shouldn't be provided because they give false sense of security.

**Comment by torakiki** [comment]
We'll add a detached signature for all the deliverables in the next release
