### ISSUE TITLE
Feature request: Split & paginate

### ISSUE THREAD

**Issue by Unperterbed** [torakiki/pdfsam#292]
I commonly have PDF files of a photo-copied book. Each PDF page is actually two pages of the book, with the spine down the middle. It could be awesome to have a feature where it vertically splits a single page into two and then stacks them so that the new file can be read from the top-down, instead of top-down-side-side.

Just a suggestion!

**Comment by torakiki** [comment]
We have that task already implemented and we will probably add it to the next version o f PDFsam Visual.
Thanks for the suggestion

**Comment by TankBoy77** [comment]
Is the old feature request about splitting an A3 into two A4 pages? If it is a feature like https://www.sejda.com/split-pdf-down-the-middle I have greatly been missing such a program that works without sending my PDFs to the web. It would have been great to have it on the desktop :-)
