### ISSUE TITLE
pdf sam creates pdf files incompatible with okular

### ISSUE THREAD

**Issue by iurisegtovich** [torakiki/pdfsam#294]
Hi, I noticed a problem when annotating pdf files with okular and noticed that it only occurred with the pdf files that I had processed in pdfsam. So I thought it might concern the pdfsam developers. I shall post this issue on the okular issue tracker as well. The problem is described as follows:

* pdf sam versions 3.3.2, when using the Split tool, creates pdf files which okular 0.24.2 can open and annotate in, but okular cannot preserve annotations when using the "save-as" or "export to archive" functions in these files.
* okular worked fine annotating and preserving annotations in the original file, before splitting with pdfsam.
* the problem persisted on updating pdfsam to 3.3.5.

**Comment by haxtibal** [comment]
Hi guys, if you got news on this, would be nice if you leave us a note over there at [Okular bug 395660](https://bugs.kde.org/show_bug.cgi?id=395660).

Basically, our pdf engine poppler has an issue because there's no object 0 in the XRef stream created by pdfsam. ISO 32k gives special meaning to object 0 in old XRef tables, it must be included there. But am unsure if that applies for XRef streams too.

Cheers Tobias

**Comment by torakiki** [comment]
Hi I investigated this and:
* we should probably include the dummy object 0 in the stream, the spec says regarding the xref table:

> The first entry in the table (object number 0) shall always be free and shall have a generation number of 65,535

and about xref streams:

> Each cross-reference stream contains the information equivalent to the cross-reference table

so I guess it's safe to assume that it should be there.
* I tested a couple of other libs (PDFBox and iText) and they both add the dummy object 0
* Our engine is used to generate a gazillion of files every month and I don't have knowledge of any other reader having troubles, we also create a `Index` array accordingly, explicitly saying that the stream contains objects starting from number 1. My 2 cents, the old "..but Acrobat can read it" applies and I think Okular should be able to read the file. 


Anyway, we fixed it and it will be released with the new version, attached the test file generated using the fix, if you could please verify it works as expected that would be great.
Thanks
[SAMBox_Untitled 2.pdf](https://github.com/torakiki/pdfsam/files/2177169/SAMBox_Untitled.2.pdf)
