### ISSUE TITLE
Request for refund initiated - refund not processed

### ISSUE THREAD

**Issue by arpitwalia** [torakiki/pdfsam#296]
I downloaded the pdfsam product for $69.5 and $22 but realized that this is not the product I am looking
so I raised a request for refund for both. However, I have not heard back since then.
my email id I provided for both purchases is arpit.walia@gmail.com
Please advise when can I expect the refund.

**Comment by torakiki** [comment]
This is PDFsam Basic issue tracker, we don't provide support for Enhanced or Visual here. We answered your emails, please provide the order numbers so we can identify the purchase and process the refund.
Thanks

**Comment by arpitwalia** [comment]
Hi Andrea

My order number is UEEHY2PG made on 1st July.

Regards
Arpit

**Comment by torakiki** [comment]
I forwarded it to the PDFsam Enhanced team, please contact us at info@pdfsam.org if there is any issue
