### ISSUE TITLE
How to export the number of pages in multiple PDFs to excel

### ISSUE THREAD

**Issue by GerreLP** [torakiki/pdfsam#301]
I'm interested in your software because I need to get a page count on thousands of PDFs. I know I can drag and drop the PDFs into the window and the filename along with the page count is displayed in the window. How do I get this information into an excel document. If I copy and paste its represented as one line of text and I need this in an excel format with columns. Thanks!

**Comment by torakiki** [comment]
You can select all the files in the table with `ctrl+a` and copy with `ctrl+c`, create an empty file somewhere with .csv extension, say `export.csv`, open it with a text editor, paste the data with `ctrl+v`, save and close the file, open it with Excel. I haven't tested it with Excel but it works with Libre Office, it should work with Excel too.

**Comment by GerreLP** [comment]
Thank you!!!

Gerre L. Poest
Post-Production Manager
713 214 4683
gerre.poest@invesco.com<mailto:gerre.poest@invesco.com>
