### ISSUE TITLE
PDFsam Basic Cannot Be Used macOS 10.13.6

### ISSUE THREAD

**Issue by tengyangxie** [torakiki/pdfsam#303]
I am using MacBook Pro with macOS 10.13.6, and I love PDFsam Basic! However, it cannot be used recently. Actually, it can be just opened, but nothing shows up. I have installed Java 8u181 already, so I am not sure what should I do now. Please help me to figure out what's happened, thank you so much!

**Comment by torakiki** [comment]
Ave you tried the zip bundle instead of the DMG? Is there any error message somewhere?

**Comment by tengyangxie** [comment]
> Ave you tried the zip bundle instead of the DMG? Is there any error message somewhere?

Thank you for your response!

I just tried the zip bundle, it can open the opening window, but then stuck with the message "INFO  16:56:44.552 o.s.c.c.GlobalConfiguration[JavaFX Application Thread] Configuring Sejda 3.2.56" in the terminal. I think that might be a problem from Java, but I reinstalled Java 8 or 10 and still can not solve that.

**Comment by torakiki** [comment]
Could you try the zip bundle with Java 8 and running it with a --clean command line argument?

**Comment by torakiki** [comment]
We just released the new version 4.0.0, we were able to reproduce the issue and it should be fixed now.
