### ISSUE TITLE
PDF not able to load from sever

### ISSUE THREAD

**Issue by tiotrom** [torakiki/pdfsam#305]
Regardless if I optimize a PDF with PDFSam or not, when I add it to my server the file cannot load. Any idea why?

**Comment by torakiki** [comment]
What error do you get? Does Acrobat Reader open it?

Il gio 27 set 2018, 16:57 tiotrom <notifications@github.com> ha scritto:

**Comment by tiotrom** [comment]
No error at all it simply fails to load. It loads any PDF I throw at it but not ones editor through PDFSam. Any PDF editor opens it perfectly. Here is an example of https://www.dropbox.com/s/lkicearb12vfk07/The%20Origin%20of%20Most%20Problems.pdf?dl=0 if you can test it.

**Comment by tiotrom** [comment]
So, to make it clear, the PDF made through PDFSam does not load from my server, but we have tens of PDF files and all load. So it is only an issue with PDFSam and I am wondering what's the issue.

**Comment by tiotrom** [comment]
And one lat thing, here is the PDFSam on the server https://www.tromsite.com/wp-content/uploads/TROM/Books/PDF/The Origin of Most Problems PDFSAM.pdf and you can see it does not load. It redirects to a 404 page, but this does not happen with any of our other PDF files, say this https://www.tromsite.com/wp-content/uploads/TROM/Books/PDF/The%20Origin%20of%20Most%20Problems.pdf

**Comment by torakiki** [comment]
Well.. If any pdf reader opens it I'd say the pdf is correct and the
problem lays on the server... There isn't much we can investigate without
any error message

Il gio 27 set 2018, 17:20 tiotrom <notifications@github.com> ha scritto:

**Comment by tiotrom** [comment]
Ok I figured it out. In Manjaro (that's what I have as my OS) PDFSam exports without any permission for read and write. So I had to manually change that.
