### ISSUE TITLE
Profile "release" doesn't exist when building latest version

### ISSUE THREAD

**Issue by der-eismann** [torakiki/pdfsam#309]
Hello, I wanted to update the repository version of pdfsam for Solus from 3.3.5 to 3.3.7, but the build seems to fail. We use [this script](https://dev.getsol.us/file/data/waw2im5f7xc7gtjejxom/PHID-FILE-jowwoitjkt3mnbzgun6g/package.yml) in our build system. 

The important part ist the `build` stage following the [wiki entry](https://github.com/torakiki/pdfsam/wiki/Build-and-run):
```
mvn -DskipTests=true -Prelease package
```

When I run this with the latest version I get the following warning in maven:
```
[WARNING] The requested profile "release" could not be activated because it does not exist.
```
The build is not really failing, but the resulting *.jar file is only 100 kB instead of ~15 MB. Did the project name change or how can I fix that?

**Comment by torakiki** [comment]
Yes, the profile has been renamed, I updated the documentation.
Post here if there's still some issue with it.

**Comment by der-eismann** [comment]
Works great, thanks for the quick answer!
