### ISSUE TITLE
Making PDFsam compatible with OpenJDK 11 and OpenJFX 11

### ISSUE THREAD

**Issue by apoleon** [torakiki/pdfsam#310]
Hello,

as you probably know Debian will release Debian 10 "Buster" with OpenJDK/OpenJFX 11 as the default Java implementation because it is long-term supported. I have tried to make PDFsam compatible with both of them. I succeeded with the compilation step but PDFsam crashes at runtime. This patch adds the missing build-dependencies:

https://salsa.debian.org/java-team/pdfsam/blob/master/debian/patches/javafx.patch

I also had to upgrade fontawesomefx to version 9.1.2 because it doesn't build with OpenJDK 11 / OpenJFX 11 anymore. I have created another patch for that and I hope it can be included at some point. I haven't had the chance to test it because of the aforementioned crash.

https://salsa.debian.org/java-team/pdfsam/blob/master/debian/patches/fontawesomefx.patch

I immediately get a segmentation fault in JavaThread "GtkNativeMainLoopThread" related to native code outside the JVM. It has something to do with libglassgtk3.so (a JavaFX 11 library) and libx11.so. I have seen the almost exact same error message with MediathekView, another JavaFX application. Version 13.0.6 works with OpenJFX 11 after patching, 13.2.1 does not. This might be a bug in JavaFX, an app should never crash this way, but it could also be some packaging mistake, missing modules, some library not loaded properly. See also Debian bug: https://bugs.debian.org/910764 and this crash log file.

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=910764;filename=hs_err_pid6422.log;msg=37

At the moment I have javafx.base, javafx.controls and javafx.graphics on the CLASSPATH. Adding all JavaFX jars to the CLASSPATH makes no difference. I have also tried the --add-modules approach by patching pdfsam.sh accordingly but this also made no difference.

Do you have any idea what is going wrong? The complete Debian repository of PDFsam can be found at: https://salsa.debian.org/java-team/pdfsam

**Comment by apoleon** [comment]
I changed my javafx.patch accordingly but I still need to patch pdfsam-core/pom.xml, otherwise the build will fail. What OpenJDK/OpenJFX version do you use? Are these the official ones provided by Debian or do you use binaries from the OpenJFX project? Could you push those changes to a different branch?

**Comment by torakiki** [comment]
Yes, true, also pdfsam-core, I've:
```
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
		</dependency>
```
I'm using the binaries Maven downloads from central, I assume the ones from the OpenJFX project.
Sure I'll create a branch for that.

**Comment by apoleon** [comment]
I found a workaround for the segmentation fault. If I pass -Djdk.gtk.version=2 to the start script, it works again. Apparently there is some kind of bug in GTK 3 related native libraries. I will forward this to the OpenJFX devs. I've just uploaded 3.3.7 to Debian unstable.

**Comment by hitam4450** [comment]
i do have the same problem...pdfsam does not start on UBUNTU 18.04 and  OPen-jdk-11-jre !

**Comment by apoleon** [comment]
On Ubuntu 18.04 use OpenJDK 8 to work around it

**Comment by apoleon** [comment]
Thanks for the OpenJDK 11 branch. I try to fix the tests next week. Our
"soft freeze" for Buster is 2019-02-12. So there is plenty of time to
release a new version of PDFsam with OpenJDK 11 support but the sooner
the better of course.

**Comment by alexhass** [comment]
Can you make it compatible with AdoptOpenJDK on Windows, too? You may know Oracle start charging users for using Java 11 on Desktops. So we need to get rid if Oracle Java at all.

**Comment by alexhass** [comment]
@torakiki Our deadline is Oracle Java 8 - End of Support. But I'd like to be ready weeks before the deadline. Any chance that we see a working Windows Version that works without Oracle?

**Comment by torakiki** [comment]
Version 4.0.0 includes a jlinked openjdk 11

**Comment by alexhass** [comment]
Many thanks!

**Comment by torakiki** [comment]
We are rolling out the release files

**Comment by torakiki** [comment]
@apoleon let me know if there's any issue with version 4

**Comment by apoleon** [comment]
Version 4.0.0 works perfectly for me. Thank you very much for all your work and all the best in 2019!
