### ISSUE TITLE
Win10 without JRE installed

### ISSUE THREAD

**Issue by Nono-m0le** [torakiki/pdfsam#312]
Hi there,

Just want to notify you that during the install of the version 3.3.7 (msi for windows), I got this message -even though I do NOT have any JRE installed- : 
![image](https://user-images.githubusercontent.com/3726435/47491099-6d6f7280-d84a-11e8-8860-273c07bc77e9.png)

But when I want to execute the software, I got this message : 
![image](https://user-images.githubusercontent.com/3726435/47490954-0e116280-d84a-11e8-96f6-03fa12e20886.png)

OS: Windows 10 x64 (Version 1803 Build 17134.345)

**Comment by torakiki** [comment]
Version 4.0.0 includes a jlinked openjdk 11
