### ISSUE TITLE
Feature request - Dark theme

### ISSUE THREAD

**Issue by schoenbes** [torakiki/pdfsam#315]
Please consider to provide a dark theme (user interface), like many other applications do nowadays. It's easy on the eyes when spending many hours at a computer screen.

**Comment by muellmaa** [comment]
def. needed. It would be WAY more appealing and pleasant to work with documents.

**Comment by Webblitchy** [comment]
Please !!! It hurt my eyes...

**Comment by zoharl3** [comment]
In high contrast mode it looks a mess.
