### ISSUE TITLE
Portable package with JRE included

### ISSUE THREAD

**Issue by jano42** [torakiki/pdfsam#316]
Is it possible to have a portable package which includes a JRE ?

In fact I'm testing PDFSam for my company. 
Due to another business software I have a very old JRE installed (1.6.x).
I really would like to test it without having to install a new JRE (I don't have admin rights)

I know many softwares which include a JRE into their files; to make it independent.

**Comment by torakiki** [comment]
Version 4.0.0 includes a jlinked openjdk 11
