### ISSUE TITLE
Split not working with Multipage PDF

### ISSUE THREAD

**Issue by Claim47** [torakiki/pdfsam#318]
I am trying to split a pdf that has 4 pages when It loads it shows has only one page when I split the output is only one page and it not viewable anymore in adobe reader it says Pleas wait....
[eimm5669e.pdf](https://github.com/torakiki/pdfsam/files/2637937/eimm5669e.pdf)

**Comment by Claim47** [comment]
[eimm5669e.pdf](https://github.com/torakiki/pdfsam/files/2637934/eimm5669e.pdf)

here is the file

**Comment by torakiki** [comment]
The file contains an [XFA](https://en.wikipedia.org/wiki/XFA) form, a deprecated features in PDF 2.0, we don't support that sorry.
