### ISSUE TITLE
Feature request - Thumbnail preview

### ISSUE THREAD

**Issue by franky37265** [torakiki/pdfsam#320]
Dear DevTeam,

When merging various pdf documents it would be a nice feature to display a preview tumbnail of the pdf document when you hover the mouse over a document row or maybe even display the tumbnail in the rows itself.

Thanks for reading...

**Comment by torakiki** [comment]
This is pretty much what the [Combine and Reorder](https://pdfsam.org/pdfsam-visual/) in PDFsam Visual does. All the "visual" feature are part of PDFsam Visual and we don't really plan to add them to Basic, sorry.
