### ISSUE TITLE
ÁTNEVEZÉS

### ISSUE THREAD

**Issue by Bogdy1** [torakiki/pdfsam#324]
Win7 pro. Intézőben kijelölöm a fájlt, szeretném átnevezni (pl.szkennelés után) de nem engedi mert a betekintő ablakban meg van nyitva!
google: Win7 pro. In Explorer, I select the file, I want to rename it (eg after scanning) but it will not let it open because it is open in the preview window!

**Comment by torakiki** [comment]
This is a PDFsam Enhanced related issue, please use the [contact form](https://pdfsam.org/contact/) and select "PDFsam Enhanced" as package, the support team will come back to you,
