### ISSUE TITLE
Error when launching PDFSam Basic 4.0 on 32-bit machine

### ISSUE THREAD

**Issue by clj84** [torakiki/pdfsam#328]
We're seeing this error on our 32-bit machines when trying to launch PDFSam 4.0 with the latest version of Java:

![image](https://user-images.githubusercontent.com/17562226/50455587-44cc2d80-090c-11e9-8a8c-d9e8302c60f4.png)

**Comment by SelfMan** [comment]
Same here, on Windows 7 Pro. Affected are both the ZIP and the MSI.
The MSI installer installs the application without an error. No complains about the platform. (x86 vs x64) That comes after trying to launch the PDFSAM with the above message.
The 3.3.7 version runs just fine.

**Comment by torakiki** [comment]
Support to 32 bit systems has been dropped since Java 9. With PDFsam Basic 4 we moved to Java 11 so we don't support 32 bits architecture in PDFsam Basic 4. I'm adding an issue to update docs and installer to make it more clear. PDFsam 3.3.7 supports 32 bits since it runs on Java 8.

**Comment by ksorenson** [comment]
@torakiki - Does that mean that Java 8 will no longer suffice and that the system requirements will eventually be updated to reflect the move to Java 11?

**Comment by SelfMan** [comment]
Then the question remains - will the 3.3.x branch continue to maintain the x86 support?

**Comment by torakiki** [comment]
> @torakiki - Does that mean that Java 8 will no longer suffice and that the system requirements will eventually be updated to reflect the move to Java 11?

Version 4 requires Java 11 but it's now bundled in the application so I'd say system requirements are now simplified for the end user

**Comment by torakiki** [comment]
> Then the question remains - will the 3.3.x branch continue to maintain the x86 support?

The latest 3.3.7 is pretty stable and battle tested. I don't know if there's enough request for x86 support  to justify branching and backporting issues from 4 to 3.x.. my idea is to focus on 4.x while users with 32bits arch can stick with 3.3.7 and migrate to 4.x eventually. I'm not against having some 3.x release though if the need arise.. some security issue or some blocker

**Comment by SelfMan** [comment]
> The latest 3.3.7 is pretty stable and battle tested. I don't know if there's enough request for x86 support to justify branching and backporting issues from 4 to 3.x.. my idea is to focus on 4.x while users with 32bits arch can stick with 3.3.7 and migrate to 4.x eventually. I'm not against having some 3.x release though if the need arise.. some security issue or some blocker

That is the point of the maintenance I ment. Not about new features, but about potential bug or security fixes. Thanks for the info.
