### ISSUE TITLE
About Java in 4.0.0 installer

### ISSUE THREAD

**Issue by Sacolevas** [torakiki/pdfsam#329]
Hello, I have the following question (thanks in advance for another release of this wonderful program):

I have OpenJDK 11 (with OpenJ9 as JVM) in my computer. So I feel that having PDFSam Running in its own Java installer could be a little bit unnecessary to me if I already have OpenJDK 11. It is possible to install PDFSam without the Java installers? I already tried to remove the runtime subfolder, but clearly it wasn't the solution, but I am not an expert to come with a better idea at the moment. Any helo would be appreciated. Thanks!

**Comment by torakiki** [comment]
If you remove the `runtime` dir, the .exe will look for a java installation performing a registry search, see [launch4j](http://launch4j.sourceforge.net/) for more details. My guess is launch4j doesn't handle Openj9 installations.
What you can try, assuming you have the OpenJ9 in your `PATH`, is delete/rename the `runtime` directory, start PDFsam using the `pdfsam.bat` in the `bin` subdirectory. 

I thought about adding a `Feature` to the MSI installer to allow the user to decide if he wants the `runtime` installed, but it seemed like something that would complicate things for most users just to please very few of them. This was one of the first problems open on ver 4 so I suppose I was wrong and there are users who, for one reason or another, really want only one washing machine for the whole building.
I'll think about adding a `Feature` to the installer but for the .exe java detection is up to launch4j, I'll try to investigate and understand if they are planning to detect the number of runtimes that are gaining attention (Zulu, Corretto, Openj9..).. to be honest I don't know what's the status here

**Comment by torakiki** [comment]
JavaFX was removed from OpenJDK and OracleJDK as well.. it is now (as of v4) a dependency of the application (you can find its jars in the lib directory). Beside OpenJDK I haven't tested other JDKs but I think PDFsam will work on all of them, at least their OpenJDK 11 equivalent.
