### ISSUE TITLE
Clearly document PDFsam 4 doesn't run on 32 bits

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#331]
PDFsam 4 uses Java 11 where support for 32 bits has been dropped (since Java 9), this should be documented and clear:

- [x] Add a FAQ section explaining that users with 32 bits should stick with PDFsam 3

- [x] Build the MSI installer specifically for x64 architecture, preventing installation on x86

**Comment by torakiki** [comment]
Most likely a week or two

Il giorno lun 31 dic 2018, 13:22 Alexander Hass <notifications@github.com>
ha scritto:

**Comment by alexhass** [comment]
Aside the title of this case should be corrected. Version 4 runs on x64 only and not on x86 if I understood java dependency correctly. The title says the opposite.

**Comment by torakiki** [comment]
Done, the new FAQ section will be released in few days
