### ISSUE TITLE
[Feature Request] Total Files in Filename

### ISSUE THREAD

**Issue by chrjaques** [torakiki/pdfsam#341]
I frequently use the split by size function to reduce reports to sizes that can be uploaded to a federal database. I use the [CurrentFile] prefix to help in naming the produced files but have to manually do back after splitting to add the total number of files to each file name. For example: "Quarter 1 Report Part [CurrentFile] of " and then depending on how many files I have to add the number at the end of each file. I would request the addition of a [TotalFiles] prefix to make it automatic.

**Comment by torakiki** [comment]
closed by https://github.com/torakiki/sejda/commit/e1dddac7ba89d39e564059eecf77105dc536715e
