### ISSUE TITLE
[Ubuntu MATE 18.04] Error at install - Lintian finished with exit status 2

### ISSUE THREAD

**Issue by GenZai** [torakiki/pdfsam#343]
This is the Lintian output we get from the package installer. When we click install nothing happens.

```
md5sum: /opt/pdfsam-basic/bin/pdfsam-basic: No such file or directory
command failed with error code 123 at /usr/share/lintian/collection/md5sums line 60.
warning: collect info md5sums about package pdfsam-basic failed
warning: skipping check of binary package pdfsam-basic

Lintian finished with exit status 2
```

It installs correctly via the command line though
`sudo dpkg -i pdfsam_4.0.1-1_all.deb
`

**Comment by torakiki** [comment]
Yes,
if I list the files in the package I get :
torakiki@torakiki-Lenovo:~/Scaricati$ dpkg -c pdfsam_4.0.1-1_all.deb
drwxr-xr-x root/root         0 2019-01-08 18:54 ./opt/
drwxr-xr-x root/root         0 2019-01-08 18:54 ./opt/pdfsam-basic/
drwxr-xr-x root/root         0 2019-01-08 18:54 ./opt/pdfsam-basic/bin/
-rwxr-xr-x root/root      3200 2019-01-08 18:54
.//opt/pdfsam-basic/bin/pdfsam-basic
drwxr-xr-x root/root         0 2019-01-08 18:54 ./opt/pdfsam-basic/doc/
..............

There is a double / and I think that's what causing md5sum to fail.
Thanks for reporting
Andrea
