### ISSUE TITLE
Split by bookmarks bug

### ISSUE THREAD

**Issue by quickfold** [torakiki/pdfsam#345]
If I add bookmarks to a pdf in Acrobat X Pro 10.1.16 in the way specified below and edit the bookmarks to add characters to the beginning of the bookmark text, PDFSam 4.0.1 ignores the edited bookmarks when splitting by bookmarks. For some reason this only happens when adding characters to the beginning of the bookmark text, not the middle or end.

Steps:
- open file, bookmark pane, select text, click 'new bookmark' icon to add bookmark
- repeat with text on pages 1, 2, and 3
- edit bookmark for page 2 to add character '1' at the beginning of bookmark
- save and close pdf
- use PDFSam to split by bookmarks
- get 2 output files, one two-page file starting on pg 1 and one file starting on pg 3. The pg 2 bookmark is ignored.

It took me over an hour to figure out how to reproduce this very frustrating bug!

e.g. file attached

[pdfsamtest2.pdf](https://github.com/torakiki/pdfsam/files/2995634/pdfsamtest2.pdf)

**Comment by torakiki** [comment]
This was fixed here https://github.com/torakiki/sejda/issues/359 and will be included in the next release
