### ISSUE TITLE
documentation bug at https://pdfsam.org/customize-file-names/

### ISSUE THREAD

**Issue by DJCrashdummy** [torakiki/pdfsam#348]
today i came across a little bug in the "docs", "FAQs" or whatever...:

at https://pdfsam.org/customize-file-names/ it states that using `[FILENUMBER13]` or `[FILENUMBER###13]` as input, generates filenames starting with 13, which is not true. - it starts with 14, which makes even more sense, because if you don't specify any number it starts with 1 and not 0.

i haven't checked it, but perhaps the same may be true for `[CURRENTPAGE13]`.

**Comment by torakiki** [comment]
Yes, fixed, we'll release the new website tomorrow
