### ISSUE TITLE
Make sure Hi-DPI is supported on every OS

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#349]
https://stackoverflow.com/questions/26182460/javafx-8-hidpi-support/26184471#26184471

**Comment by parrenin** [comment]
I was just about to buy a pdfsam license for my work computer, but I discovered this issue which is a stopper for me since I have a 4k screen. I hope the developers can do something about it soon.

**Comment by parrenin** [comment]
I forgot to say that I am on Debian 11 linux bullseye.

**Comment by torakiki** [comment]
For Basic you can just download it and try it to see if there's any issue with your monitor. For Visual pretty much the same, you can try it free for 14 days.

**Comment by parrenin** [comment]
I tried basic but everything is too small on the screen.

**Comment by 21347** [comment]
Workaround for (probably most) Linux distributions: call pdfsam-basic with `GDK_SCALE` variable set to a reasonable amount, e.g.

```bash
GDK_SCALE=2 /opt/pdfsam-basic/bin/pdfsam-basic
```

Stolen from: https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

You can also just edit the script at `/opt/pdfsam-basic/bin/pdfsam-basic` and insert the variable change just before the call to the `java` binary, e.g.

```bash
export GDK_SCALE=2
exec "$JAVACMD" -jar "$JAR_ARG" $JAVA_OPTS -Xmx512M \
  -Dapp.name="pdfsam-basic" \
  -Dapp.pid="$$" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  -Dprism.lcdtext=false \
  org.pdfsam.basic.App \
  "$@"
```
Or tell the `.desktop` file (or just edit the menu entry) to add the variable to the command line, e.g. for Ubuntu/Min derivatives:
```
env GDK_SCALE=2 /opt/pdfsam-basic/bin/pdfsam-basic %F
```

The splash screen is still in dwarf-size mode, but the main Application is usable. I would assume that this is not a permanent fix, though, as setting the scale factor to a fixed value will not work for non HiDPI screens then.

**Comment by parrenin** [comment]
@21347: Thank you for the workaround, that will do it for my use case.

**Comment by torakiki** [comment]
We added an [HowTo](https://blog.pdfsam.org/how-to/how-to-change-the-scale-of-pdfsam-basic/2436/) and a setting for the font size in version 5, this should cover pretty much all the needs
