### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#358]
Hi,

I encountered an issue in the File Sorting by file
name during the merge operation.
Say I have 20 pdf files :
1.pdf
2.pdf
...
10.pdf
11.pdf
...
19.pdf
20.pdf

Here, the program seems include the extension
(.pdf) as well in the sorting machenism, which is
causing the problem to sort the files as the
sorting happens incorrectly.
After sorting the result looks like :

1.pdf
10.pdf
11.pdf
...
...
19.pdf
2.pdf
20.pdf

In my opinion, the file sorting should algorithm
should consider only filename, excluding the
extension. This should resolve the issue.

Hope you would find this suggestion helpful.

Regards,
Bharat Bajaj

**Comment by bharatbjj** [comment]
Hi, It seems the issue is closed.

Does it mean that this bug will be fixed in version 4.0.4 ? 
Will I get a notification when the new version will be released ?

Br,
Bharat

**Comment by torakiki** [comment]
Yes, if you look at the milestone associated with the issue is 4.0.4.
You can follow us on Twitter https://twitter.com/PDFsamOSS where we announce releases.. or the application itself will notify
