### ISSUE TITLE
Merging files with bookmarks Version 4.01

### ISSUE THREAD

**Issue by luisma1955** [torakiki/pdfsam#361]
When merging files that already have bookmarks it have an option to retain the bookmarks on the output file created but the option is not working since the file is created with no bookmarks.
[Merge with bookmarks error.pdf](https://github.com/torakiki/pdfsam/files/3543888/Merge.with.bookmarks.error.pdf)
[(00)-Section 6. Grouping data.pdf](https://github.com/torakiki/pdfsam/files/3543889/00.-Section.6.Grouping.data.pdf)
[(01)-MySQL GROUP BY.pdf](https://github.com/torakiki/pdfsam/files/3543890/01.-MySQL.GROUP.BY.pdf)
[(02)-MySQL HAVING.pdf](https://github.com/torakiki/pdfsam/files/3543892/02.-MySQL.HAVING.pdf)
[(03)-MySQL ROLLUP.pdf](https://github.com/torakiki/pdfsam/files/3543893/03.-MySQL.ROLLUP.pdf)
[PDFsam_merge.pdf](https://github.com/torakiki/pdfsam/files/3543895/PDFsam_merge.pdf)

**Comment by torakiki** [comment]
It's a bug in [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3275). We already reported it and discussed [here](https://github.com/torakiki/sejda/issues/357), I think we will have to end up handling this given it's showing up from time to time.

**Comment by Jaudouard** [comment]
Any news on this subject? Is this a part of the 4.x release?

**Comment by torakiki** [comment]
Closed by https://github.com/torakiki/sejda/commit/8d3d965e07cfc0c851bd0d8273070736500c5860
