### ISSUE TITLE
Question: Merging non-PDF files

### ISSUE THREAD

**Issue by timbuktumor** [torakiki/pdfsam#369]
PDFsam Basic 4.0.4

The merge module will only merge .PDF files.   Are there any plans to allow merging of non-PDF files like images, text files, word, excel, etc. in the basic version?  Is this available in the enhanced version?

**Comment by torakiki** [comment]
We added merge of images to PDFsam Visual in the upcoming version while PDFsam Enhanced can already merge pretty much every format that it can convert to PDF. We don't really plan to add that the the Basic at the moment.
