### ISSUE TITLE
java error after upgrading to version 4.0.4

### ISSUE THREAD

**Issue by arhadrian** [torakiki/pdfsam#375]
At least in the split module, I get an error message. Looking in the log, I see it's a java problem. Could you help me with this? I had no problem with the pre-4.* version. The error also occurs in the portable version. I can post all the log if necessary. Thank you.

**Comment by torakiki** [comment]
Yes please, post the logs

**Comment by arhadrian** [comment]
Yeah... how I hate this :) So, long story, short: I uninstalled the version 4 and installed a 2.something, since I needed the program to work. Now, for the logs, I reinstalled the last version and, surprisingly enought, it worked... Probably some Windows updates, probably something else... Anyway, before uninstalling this last version I tried everything for 10 times or so. Thanks for replying!
