### ISSUE TITLE
pdfsam 4.0 32-bit support through AdoptOpenJDK 11 x86

### ISSUE THREAD

**Issue by txr660** [torakiki/pdfsam#376]
Hi
In issue  https://github.com/torakiki/pdfsam/issues/331
it was said that support for 32 bit has been dropped in Java 11 , but
on the AdoptOpenJDK site , there are x86 builds for version 11 , 12 and 13 .
So why doesn't pdfsam 4.0 support 32-bit ?
![sshot-225](https://user-images.githubusercontent.com/47015103/68311861-17165000-00aa-11ea-8c37-f8e20461f347.png)

**Comment by torakiki** [comment]
When PDFsam moved to openjdk 11 there wasn't a 32bits version, then all sorts of openjdk binaries started to pop up and we moved to AdopOpenJDK which later added support for 32 bits. I think it should work if:
-  we also change OpenJFX to 32 bits (not sure if it's available on Maven)
or
- use some jdk like Zulu which includes OpenJFX and has a 32 bits version **and** remove the OpenJFX dependency from the project

Overall it seemed an effort that's not really worth given the architecture is getting less and less adopted, it would complicate the build/release cycle and we still have the 3.3.7 working on 32bits... anyway I'm willing to accept a PR
