### ISSUE TITLE
pdfsam 4.0.5 - does not start on windows with SRP policy

### ISSUE THREAD

**Issue by chupnik** [torakiki/pdfsam#380]
Problem in windows domains environments with SRP(software restriction policy).
This policy prohibits the user from running programs except those set by the administrator.(outside ProgramFiles or WIndows directory).

When pdfsam starts, it unpacks the DLLs (api-ms-win-core-*)  into a directory
`%userprofile%\.openjfx\cache\13.0.1\`
And SRP policty restricts to run from this directory.
I want to be able to change this path to directory.
How can I change this behavior through the settings(ini.file, command line etc.)?

**Comment by torakiki** [comment]
Hi,
please take a look at this
https://stackoverflow.com/questions/53382810/configure-openjfx-11-to-extract-its-dlls-into-a-different-user-specified-directo
and let me know if it solves the problem.

Il giorno gio 21 nov 2019 alle ore 10:30 Nikolay Chuprina <
notifications@github.com> ha scritto:
