### ISSUE TITLE
Problems with Explorer Preview

### ISSUE THREAD

**Issue by Hengstigal2** [torakiki/pdfsam#381]
Hello,

i have a problem with pdfsam.
Since ive installed pdfsam basic my preview window (in the explorer) doesnt show up anymore. (Picture 1)
I tried installing pdfsam Enhanced but then the preview window doesnt work too.
(Picture 2)
![pdfsam2](https://user-images.githubusercontent.com/58288995/69789271-86babf00-11c0-11ea-8a3e-741ba43bdcdc.PNG)
![pdfsam1](https://user-images.githubusercontent.com/58288995/69789269-85899200-11c0-11ea-9c8a-0b1eb69f9c83.PNG)

**Comment by torakiki** [comment]
This is part of Enhanced and the issue was solved.
