### ISSUE TITLE
Split by size is not working

### ISSUE THREAD

**Issue by 2ool** [torakiki/pdfsam#383]
Hi,
If PDF file contains markups the split by size function is not working, and the parts of the file become larger than the original file.

**Comment by torakiki** [comment]
Can you provide the file? If it's confidential can you send it to info@pdfsam.org ?

**Comment by 2ool** [comment]
> Can you provide the file? If it's confidential can you send it to [info@pdfsam.org](mailto:info@pdfsam.org) ?
Thanks @torakiki 
it is confidential but I will provide another sample.
[MSI Manual.pdf](https://github.com/torakiki/pdfsam/files/3949913/MSI.Manual.pdf)

**Comment by torakiki** [comment]
Ok... after much digging I found the issue. 
Some background:

- A page dictionary can contain a content stream reference (or an array of) in its `/Contents` entry.
- A page dictionary can contain annotations in its `/Annots` entry
- Annotations can contain references to the page they are associated with
Our tasks handle this situation which follows the PDF spec.
Now your file has a `/Annots` entry in the content stream dictionary (where it shouldn't be) and it references the page, and our tasks basically brings in a lot of other data starting from there.
I will investigate what others do in this case but the bottom issue is your editor creating a file not conforming to the PDF spec.

**Comment by torakiki** [comment]
I investigated other splitters and they either remove non compliant keys (remove the stream `/Annots` key) or handle the annotations page reference. Acrobat handles the annotations page refs even if the annotations are not in the expected place but I'd go for the keys removal, it's easier and faster.

**Comment by kiwikern** [comment]
I'm encountering the same problem with the latest version 4.1.1 which should include the fix. Could this be a different problem? Should I open a new issue?


[input.pdf](https://github.com/torakiki/pdfsam/files/4366112/input.pdf) (one page with text + two blank pages, 2.80 MB)
[1_output.pdf](https://github.com/torakiki/pdfsam/files/4366108/1_output.pdf)
[2_output.pdf](https://github.com/torakiki/pdfsam/files/4366110/2_output.pdf)
[3_output.pdf](https://github.com/torakiki/pdfsam/files/4366111/3_output.pdf) (2.80 MB)
