### ISSUE TITLE
how to stop pop up ad

### ISSUE THREAD

**Issue by scotchletters** [torakiki/pdfsam#384]
as the subject states please

**Comment by torakiki** [comment]
This is a PDFsam Enhanced issue but you can find a HowTo here https://support-enhanced.pdfsam.org/hc/en-us/articles/360025094451-How-do-I-disable-the-Popup-that-appears-when-I-login-to-my-computer-

**Comment by SEI-John** [comment]
Can the popup be disabled for PDFSam basic? It's giving an ad once a day that can't be turned off in settings.
