### ISSUE TITLE
Buggy Behavior/Merged PDF

### ISSUE THREAD

**Issue by chansen1979** [torakiki/pdfsam#385]
After I merge pdf documents and save them as a pdf to email to my employee's they see something like this when they open it. The pdf's open fine on my computer and so do the pdf's before merging them. What in the world is going on? Multiple employee's have the same issue. 
![image](https://user-images.githubusercontent.com/59661542/72000954-9b4b9780-3201-11ea-8ed4-b82ab84cfffc.png)

**Comment by torakiki** [comment]
Is it confidential or can you share the file? What PDF viewer are they using?

**Comment by chansen1979** [comment]
They are using Bluebeam which makes it buggy. Using just adobe is fine though. Not sure what the incompatibility with bluebeam is. I can’t share the file unfortunately.

Christine Hansen » www.dcengineering.net<http://www.dcengineering.net/>
Direct » 406.218.2189 | chansen@dcengineering.net<mailto:chansen@dcengineering.net>

**Comment by torakiki** [comment]
Have you tried with other viewers like the one in Chrome, in Firefox.. if you have a Mac maybe the one in MacOS.. if they all show the file correctly I'd point to some issue in Bluebeam. Anyway, if you want to share it privately sending an email at info@pdfsam.org I can take a look.. without the file it's hard to figure what could be the issue

**Comment by chansen1979** [comment]
Thanks. I think the issue is in bluebeam as it seems to open fine elsewhere. Unfortunately I can’t share the info anywhere outside the company. Sorry, I know that is not helpful to you but maybe its at least helpful to know that BB has an issue. I will advise my guys to make sure and not use BB for the files. They might get their noses out of joint but its not the end of the world, lol. I appreciate your response.

Christine Hansen » www.dcengineering.net<http://www.dcengineering.net/>
Direct » 406.218.2189 | chansen@dcengineering.net<mailto:chansen@dcengineering.net>
