### ISSUE TITLE
Feature: Add DESKTOPSHORTCUT to MSI Installer

### ISSUE THREAD

**Issue by darim92** [torakiki/pdfsam#388]
Please add DESKTOPSHORTCUT property to the MSI-Installer. 

DESKTOPSHORTCUT=true
DESKTOPSHORTCUT =false  // No shortcut on Desktop

Keep up the great work!

**Comment by torakiki** [comment]
It's already a `Feature` in the MSI and you don't need a property. If you are trying to enable/disable that feature during a silent install take a look [at this](https://stackoverflow.com/questions/246329/how-to-select-features-from-command-line) on how to select the feature you want to install.
The features available in the PDFsam installer are `MainAppFeature`, `AddContextMenu` and `AddContextMenudesktopShortcut` where the last one (badly named) is the one that creates the desktop shortcut.
