### ISSUE TITLE
Mac dmg notarization

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#392]
With Catalina non notarized  applications gets a scary dialog saying that Apple was not able to check for malicious software and it doesn't install it. This can be workedaround by right clicking on the dmg and selecting the flag to proceed anyway (flag that is not shown unless you right click) but who knows when/if they will decide they need even more control.
We should get the application notarized and maybe ready for the app store... at some point they will tell users that apps outside the store are spooky and dangerous and only apps from the store will run.. so better be ready.
https://bugs.openjdk.java.net/browse/JDK-8223671
http://kothar.net/macos_catalina_java_11

**Comment by Pyth-n** [comment]
Hi,

I installed the application correctly on the latest Catalina release (10.15.3). When I launched the application, the OS prompted if whether I want to allow "Input Monitoring" from this application which "allows the app to monitor input from your keyboard even while using other apps." 

Is this normal? If it is, why is it needed?
