### ISSUE TITLE
One-Time sponsoring without credit card

### ISSUE THREAD

**Issue by lucidBrot** [torakiki/pdfsam#393]
Hi! I just used pdfsam for the first time and am amazed by the fact that it actually just works, with a perfectly streamlined GUI on top of that. I would like to pay a small amount to show appreciation, but not repeat that payment every month and I have not connected a credit card to paypal - which somehow is required for github sponsors.

Is there another way one could pay you some 5-10$?

**Comment by torakiki** [comment]
Hi,
thanks for supporting. We have a donation page here https://pdfsam.org/donate/
We basically accept some crypto currency and donations to the PayPal account info@pdfsam.org

**Comment by lucidBrot** [comment]
Wonderful! I suggest adding that link to the list of sponsoring options on github as well. Because paypal on your site accepts payment without credit card deposited in the paypal account, but the paypal option on github sponsors does not.
