### ISSUE TITLE
Update bundled OpenJDK 11.0.7

### ISSUE THREAD

**Issue by stondino00** [torakiki/pdfsam#399]
Please update to 11.0.7 when released in next 72ish hours.

**Comment by stondino00** [comment]
They have released openjdk 11.0.7.

Is it possible for us to upgrade this bundled binary manually or do you have to recompile the program?

Can we replace java.exe and java.dll in C:\Program Files\PDFsam Basic\runtime\bin?

**Comment by torakiki** [comment]
You can set an env variable `PDFSAM_JAVA_PATH` pointing to a jdk path that you keep updated and run the application with the script in the `bin` directory. 
As an alternative I would replace the whole `runtime` content with the new jdk but I'm not sure what will happen then when you try to uninstall.
The best would be to have the `PDFSAM_JAVA_PATH` variable to be picked up by the `.exe` but it's not currently available.

**Comment by stondino00** [comment]
Ok no worries.  We'll wait until you are able to update the application. Thanks
