### ISSUE TITLE
pdfsam basic version does not open on windows 10 (white screen)

### ISSUE THREAD

**Issue by haakon-e** [torakiki/pdfsam#400]
Hi, I recently found this tool and was happy to use it instead of the alternative non-open source options. However, it seems to not work.

That is:
* I navigate to the downloads page: https://pdfsam.org/download-pdfsam-basic/
* I use the "Windows downloader (.exe)" and install without making any adjustments.
    * That is, I get the most recent version as of April 23 2020.
* I run PDFsam basic from my computer. I have attached an image which shows what I see. That is, nothing is happening. Black and white window.
![bilde](https://user-images.githubusercontent.com/45243236/80076776-f2753e00-854c-11ea-97d7-7bd72121ee20.png)

Please let me know if I can provide any additional information which would be useful to debug this issue.

### OS details
* OS: Microsoft Windows 10 Home
* Version: 10.0.18363 Build 18363
* Misc: x64 system type, Intel Processor i7-8809G CPU @ 3.10GHz, 32GB RAM, 1TB available storage

#### Open
* #364: This issue concerns 32-bit systems, mine is 64-bit so not relevant.
#### Closed
* #351: I'm using the official website, so this is not relevant.

**Comment by torakiki** [comment]
Can you please give this a try? https://blog.pdfsam.org/bug-fix/white-screen-running-pdfsam-basic-on-windows/1980/

**Comment by haakon-e** [comment]
It worked perfectly, thank you for your quick assistance!
