### ISSUE TITLE
MacOS non full screen start

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#402]
> Can I configure the program to open as a window that is not full-screen size

**Comment by torakiki** [comment]
Closed by f111eaf35e63244b2d359b6c7a5a5b6e0a323d92

**Comment by ew98** [comment]
Good job fixing the main screen. 4.1.4 now retains its last size for each new application start in MacOS. 

Opening the Log Register dialog however (comment bubble icon with exclamation mark on top right title bar of main window) opens initially in full screen. If I manually adjust its size, then close it and reopen it, I get a very reduced size window for the Log Register. All other options seem to open in the main app windows (awesome).

This is just FYI - not using Log Register for much, so no urgency in fixing.
