### ISSUE TITLE
motd maven plugin

### ISSUE THREAD

**Issue by pavanyogi** [torakiki/pdfsam#406]
[ERROR] Unresolveable build extension: Plugin kr.motd.maven:os-maven-plugin:1.6.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for kr.motd.maven:os-maven-plugin:jar:1.6.1 @

**Comment by pavanyogi** [comment]
java --version
java 12.0.2 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
pavany@u-16:~/.../pdfsam$

ubuntu-16.04

**Comment by torakiki** [comment]
Could you try the latest version and see if the issue is still there? 
Master branch requires jdk 19
