### ISSUE TITLE
Text in drag and drop field is garbage

### ISSUE THREAD

**Issue by milotype** [torakiki/pdfsam#407]
Please see screenshot. The shaded text is completely strange.
I guess it should be the text for `Drag and drop PDF files here`

It seems to be a language independant bug.
MacOS X 10.11.6
PDFSAM 4.1.3

![Drag-drop field](https://user-images.githubusercontent.com/43657314/82919769-bb90ae80-9f76-11ea-9dc3-af64c0826236.png)

**Comment by milotype** [comment]
@torakiki Just wondering why you closed this issue and #417. My reported issue still exists in PDFSAM Basic version 4.1.4.

**Comment by torakiki** [comment]
This issue is not closed

**Comment by milotype** [comment]
I probably got confused with the `Closed` button … please excuse …

**Comment by torakiki** [comment]
If you go to the About section, is it all correctly localized or do you see gibberish? Do you see wrong characters somewhere else?

**Comment by milotype** [comment]
The About section is fine!

![screenshot-about-section](https://user-images.githubusercontent.com/43657314/94254865-a8dbb580-ff27-11ea-8594-807e08a295f5.png)

The gibberish shows up only in the following sections: Merge, Rotate, Extract, Alternate Mix

**Comment by milotype** [comment]
@torakiki Just to remind you that this issue still exists in the **PDF Split and Merge Basic Edition**, version **4.2.10** on my MacOS X 10.11.6

**Comment by torakiki** [comment]
Yes I know, I have few users reporting this from time to time but I didn't manage to find a reason or a workaround yet

**Comment by milotype** [comment]
Closing the issue as it seems to be resolved! Thank you.
See screenshots below on:
MacOS X 15.1.5
PDFSAM 5.2.9

**ENGLISH LANGUAGE**
<img width="1006" alt="screenshot-en" src="https://github.com/user-attachments/assets/732326ce-57d7-4380-932b-83a42585d6c2">

**CROATIAN LANGUAGE**
<img width="1005" alt="screenshot-hr" src="https://github.com/user-attachments/assets/eb9e6939-ff6f-407d-95dd-9e6a5300a037">
