### ISSUE TITLE
Add ability to enable/disable commenting for PDF

### ISSUE THREAD

**Issue by camdecoster** [torakiki/pdfsam#41]
Currently only Acrobat Pro can enable/disable this feature from my research. It would be a very useful feature to have so that I could make markups on PDF's without having to bother (or wait for) someone with Acrobat Pro to help me.

**Comment by torakiki** [comment]
If you are talking about setting the right permission like explained here https://forums.adobe.com/thread/910129 the feature is available in PDFsam Visual and Enhanced but there is no plan to add it to PDFsam Basic
