### ISSUE TITLE
Editing destination file/directory path triggers hotkey action

### ISSUE THREAD

**Issue by eXpl0it3r** [torakiki/pdfsam#411]
Hopefully I didn't miss a report on this, as I'm a bit surprised that nobody has reported this issue, given that it's quite annoying to work with. 😄 

## Description

Trying to change the output file or directory by clicking on the path and then typing a different name, doesn't really work, because certain keys trigger an action. For example if you press `a` it will open the file browser, so you can't write a word that has an `a` in it. Or if you press `c` it will clear the list, so you can't type words with `c` in it either. More may exist.

## Information

PDF Split and Merge Basic Edition
4.1.3
OpenJDK Runtime Environment 11.0.7+10
Vendor: AdoptOpenJDK
Java runtime path: C:\Program Files\PDFsam Basic\runtime
JavaFX runtime version 14.0.1+1
Max memory 512 MB

OS: Windows 10
Installed via Chocolatey
Keyboard layout: Swiss German
Language: English (United Kingdom)

## Steps to Reproduce

- Start PDFSAM
- Select "Merging"
- Add a few PDFs of your choice
- Under "Destination file" click inside the textbox with the path
- Try entering your custom filename
- Try the keys `a` and `c`

## Actual Behavior

Certain keys like `a` and `c` trigger actions.

## Expected Behavior

Pressing any character key while having the focus on the path text box, should add the corresponding character to the text box and not trigger any actions.

![image](https://user-images.githubusercontent.com/920861/84696346-a4792700-af4c-11ea-80a8-6546af7d6566.png)

**Comment by torakiki** [comment]
Those keys are accelerator and should only be triggered if the ALT key is
pressed. Could you confirm the ALT key is not pressed?
We had few other reports but those who answered were also using the ALT.

Il lun 15 giu 2020, 21:09 Lukas Dürrenberger <notifications@github.com> ha
scritto:

**Comment by eXpl0it3r** [comment]
The ALT key is *not* pressed indeed. The odd part is, that *sometimes* - was unable to narrow down in which cases - the keys actually work when typing. Looks like some state tracking gone rouge.

**Comment by torakiki** [comment]
Unfortunately the same happened with other reports like this, users weren't able to narrow down what was causing it. I suspect it has something to do with the JavaFX update because we had zero reports before that but it's hard to figure what is causing it.

**Comment by eXpl0it3r** [comment]
So you can't reproduce it locally?

**Comment by torakiki** [comment]
No, it works fine in my windows box

**Comment by torakiki** [comment]
see #424
