### ISSUE TITLE
New module "Delete pages"

### ISSUE THREAD

**Issue by larsen0815** [torakiki/pdfsam#414]
I use a scanner to create PDFs of correspondence that I get from which I want to delete one or two pages. At the moment, I have to use "extract" and specify e.g. "1-5,7-10,12-16,18-".

Would be more convenient to simply use a new "Delete pages" to specify "6,11,17".

**Comment by torakiki** [comment]
Hi, we have a Delete pages task but it's part of PDFsam Visual
https://pdfsam.org/delete-pdf-pages/

Il mer 17 giu 2020, 09:24 larsen0815 <notifications@github.com> ha scritto:

**Comment by larsen0815** [comment]
Would be great to have this included in PDFsam (without visual stuff), just  specifying a PDF file and the pages to delete from.

**Comment by torakiki** [comment]
We added this to our PDFsam VIsual backlog. A quick way to specify pages to be deleted.
I don't think we will add a Delete pages module to Basic since we consider it a premium module.
Thanks for the feedback
