### ISSUE TITLE
Merge - Add PDF list from text/csv file - Page ranges not imported

### ISSUE THREAD

**Issue by drghughes** [torakiki/pdfsam#418]
Being able to copy (to the clipboard) the list of PDFs that you have created in the merge function, and then reload them, is great - see #338.

However, any page ranges that have been set up aren't included when I copy the list, and if I manually edit the list in the csv file, they aren't imported.

Could you please update the export/import of the list so that the page ranges are included.

Thanks!

**Comment by torakiki** [comment]
CSV import/export is meant more as mean to integrate PDFsam with other system that can export to CSV or require a CSV as input.
For your case save/load of a workspace seems more appropriate, you can find in the top right menu. Feel free to reopen this if the feature doesn't fit your needs.
