### ISSUE TITLE
Flatten and Merge Bug (Fillable Forms)

### ISSUE THREAD

**Issue by rvdjr** [torakiki/pdfsam#423]
Hello All, 

When I fill out a "fillable" PDF form and then "flatten and merge" the fillable form with a "non-fillable" (a.k.a. typical) PDF document, I then see the error message "an error exists on this page..." when I open the newly "merged" PDF file in Adobe Reader and then click the "page down" key on my keyboard or scroll up and down through it with the Adobe Reader scroll bar. 

However, the error message seems unnecessary, as the new PDF file looks fine to me after I click the "OK" button of the error message and then scroll through the newly merged file in Adobe Reader (or via the "page down" key).

Here is my environment:

PDF Split and Merge Basic Edition
4.1.4
OpenJDK Runtime Environment 11.0.8+10
Vendor: AdoptOpenJDK
Java runtime path: C:\Program Files (x86)\PDFsam Basic\runtime
JavaFX runtime version 14.0.2+1
Max memory 492 MB

Is this a known issue?

Thanks,

Ray
San Francisco

**Comment by torakiki** [comment]
It's not an know issue, it could be we generate the files with some error and Acrobat Reader automagically fix it. Have you tried other readers? Like the one in Chrome or the one in Firefox?
If you can attach the original and the resulting file we can take a look. You can also send them to us at info@pdfsam.org if you don't want to share them with the public

**Comment by rvdjr** [comment]
Hello Torakiki,

Here are the files:

[File 1.pdf](https://github.com/torakiki/pdfsam/files/5320442/File.1.pdf)
[File 2.pdf](https://github.com/torakiki/pdfsam/files/5320444/File.2.pdf)
[Merged File.pdf](https://github.com/torakiki/pdfsam/files/5320445/Merged.File.pdf)

Just merge File 1 and File 2 to get Merged File in PDFsam basic. Then, scroll up and down in the Merge File. Then, click anywhere in the Merged File. Then hit the page up and page down keys a few times. You should see the error message pop up.

Thank you,

Ray

**Comment by torakiki** [comment]
What version of Acrobat Reader are you using? I just tested with Acrobat Reader DC 2019 on Windows, PDFjs and Chrome embedded viewer and they all render the file without any issue or error message.
Also please try the latest version of PDFsam.
Andrea

**Comment by rvdjr** [comment]
Hello Andrea,

I am using Acrobat Reader DC 2021 (the latest version.)

PDFSam basic 4.2

The bug can be challenging to reproduce. One needs to click a random area
of the first page of the flattened PDF after said file is opened, and then
tap the "page-down" button, in order to reproduce the bug.

- Ray

**Comment by torakiki** [comment]
Ok, I'll try again tomorrow with that version. I used 2019 Acrobat DC and also run a preflight analysis and it reported no syntax errors and no warnings in the "Compatible with Acrobat 7" profile
