### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by milotype** [torakiki/pdfsam#438]
The link in the "Translations" chapter https://github.com/torakiki/pdfsam#translations in the ReadMe file at GitHub points to https://translations.launchpad.net/pdfsam/pdfsam-v3, which is not the current/planned/upcoming version.

**Suggestions:**

1. Update translation files at "launchpad".
2. If possible, think about using a more modern translation platform like [Weblate](https://weblate.org/hr/). (This is just my personal preference as a translator!)

**Comment by torakiki** [comment]
Yes, the `v3` in the link is a bit misleading but that's the correct place where translations are kept up to date. Launchpad feels a bit outdated but it's open source, does the job and it's used by projects like Ubuntu so it should be more then enough for PDFsam too. I see Weblate is free for open source projects too, with some limitation though.. I'll take a look but to be honest it doesn't feel like something I want to invest time, anyway, thanks for the suggestion.
