### ISSUE TITLE
Fonction CHOIX des pages a fusionner dans plusieurs PDF

### ISSUE THREAD

**Issue by Cadete60200** [torakiki/pdfsam#445]
Bonjour,
J'aimerais voir une fonction de FUSION de PDF, mais avec le choix possible des pages à fusionner.
Par exemple, dans nu  lot de 1000 fichiers PDF, je voudrais fusionner dans un seul fichier PDF les pages 1 de chaque fichier PDF.
Il serait même mieux de pouvoir choisir le nombre de pages (exe 3 premières pages de chaque fichier)

Merci.

**Comment by torakiki** [comment]
That's already possible using the "Page ranges" column in the selection table
