### ISSUE TITLE
Size limit in pdfsam basic?

### ISSUE THREAD

**Issue by Coachmn** [torakiki/pdfsam#447]
Hi,
I seem to be unable to merge 2 or more pdf files that result in a file bigger than 1GB. Is this a bug or 'feature'?

**Comment by torakiki** [comment]
Unable how? What happen? What version? What operating system?

**Comment by Coachmn** [comment]
Okay, here is the detail.  V4.2.3 running on up-to-date Windows 10.
I had 5 sets of scans. The first had 8 pages and the other four 32 pages of a4 scanned at 300dpi. I merged all 4 and when I try to load the resulting file using SumatraPDF I get 'Error loading file file _name_'.
I tried various combinations merging 2 and 3 scans and ended up with 2 files of 1.26GB and 1.4GB that when I load to PDFsam report as 1GB each but again will not produce a file I can open.
Please note that the scans are of Kelly's directories and contain thousands of words. I'm not clear how a pdf stores OCR information and if that is a factor in the problem.
Whilst I've been typing this I produced another merged file from the two detailed above and tried to load it into the Firefox pdf reader. I gave up on it after about 5 mins of Firefox 'not responding'. Again SumatraPDF gave 'Error loading file'

**Comment by torakiki** [comment]
There is no explicit limit in PDFsam and it should handle big files. Is there any error message in the Logs Viewer during the merge task?
If you try to load the resulting PDF in pdfsam (in the Merge task selection table for example) does it work or do you get any error?
Have you tried Chrome to open the resulting file?

**Comment by Coachmn** [comment]
No error 'INFO   [12:00:01]: Task (org.sejda.impl.sambox.MergeTask@2c0c6044) executed in 1 minute 11 seconds'.
Resulting file will load into PDFsam without error 'INFO   [12:01:38]: Kelly's Lincoln 1965 Pt0.pdf loaded'.
Yes it will load into Chrome (after I download Chrome!). Saved out of Chrome it will still not load into SumatraPDF.
I download Adobe Acrobat Reader DC and it loads into that okay as well so it must be SumatraPDF (and Firefox) at fault.
Thanks for your help and sorry to waste your time.

**Comment by torakiki** [comment]
No problem.
It's not unusual with such a big file to have some reader that cannot properly handle it.
