### ISSUE TITLE
How to disable "search for an update now" option

### ISSUE THREAD

**Issue by BKyllian** [torakiki/pdfsam#450]
Hi ! 

As part of my job, I have to deploy PDFSam in my company.

I want to disable the options (in command line or by deleting files): Check for updates at startup and Check for update now.

Thanks for your feedback. 

Best regards.

![Capture](https://user-images.githubusercontent.com/25460039/115036941-3edc2b00-9ece-11eb-928e-bcd90ef6dbb4.PNG)

**Comment by torakiki** [comment]
There isn't an option for that. At the moment you can only disable the whole settings panel, see https://github.com/torakiki/pdfsam/wiki/Properties-and-arguments
