### ISSUE TITLE
Menu in PDF

### ISSUE THREAD

**Issue by PhilippeChauvin** [torakiki/pdfsam#452]
Dear all,

In attachment, two sources PDF file.
On the PDFSource1.pdf and PDFSource1.pdf when I click on "R?" a menu appears.
![Menu](https://user-images.githubusercontent.com/6859760/115983893-59846300-a5a4-11eb-9898-36c80dc64d28.png)
However, after merged the two PDF (PDFsam_merge.pdf), nothing happens when I click on "R?". Do you know what happens?
I tested to change the version of the PDF (1.5, 1.6 and 1.7) without success.

Tested on 4.2.4 version.

Best regards
Philippe

[PDFSource2.pdf](https://github.com/torakiki/pdfsam/files/6371403/PDFSource2.pdf)
[PDFsam_merge.pdf](https://github.com/torakiki/pdfsam/files/6371404/PDFsam_merge.pdf)
[PDFSource1.pdf](https://github.com/torakiki/pdfsam/files/6371405/PDFSource1.pdf)

**Comment by torakiki** [comment]
Hi Philippe,
it's likely a Javascript embedded in the PDF file and we currently don't support that, sorry. Ave you tried with a paid product like Acrobat? I'm not sure they support it either..
