### ISSUE TITLE
minor permission issue files on the linux tarball

### ISSUE THREAD

**Issue by truatpasteurdotfr** [torakiki/pdfsam#454]
https://github.com/torakiki/pdfsam/releases/download/v4.2.4/pdfsam-4.2.4-linux.tar.gz
some of the files are not word readable and some are group writable. :P
```
$ tar tzvf pdfsam-4.2.4-linux.tar.gz | cut -d ' ' -f 1| sort | uniq -c
     46 drwxrwxr-x
     33 lrwxrwxrwx
     23 -r--r--r--
      9 -rw-r--r--
     32 -rw-rw----
     81 -rw-rw-r--
      5 -rwxrwxr-x
      1 -rwxr-xr-x
```
imho, 755 for folders and executables, 644 for all the files, nothing to change for the soft links.
Maybe something like:
```
find  pdfsam-4.2.4-linux -type d -print0 | xargs -0 chmod 755
find  pdfsam-4.2.4-linux -type f -print0 | xargs -0 chmod 644
chmod 755 pdfsam-4.2.4-linux/bin/pdfsam.sh
```
before making the tarball?

**Comment by torakiki** [comment]
This should be fixed in the latest 5.x
