### ISSUE TITLE
feature request: provide .jar in release

### ISSUE THREAD

**Issue by ivysrono** [torakiki/pdfsam#457]
I have installed JDK11 in system, so I'd like to launch .jar directly.

**Comment by torakiki** [comment]
Please see https://github.com/torakiki/pdfsam/wiki/Properties-and-arguments at the bottom. We bundled the jdk11 runtime but you can just delete the runtime subdirectory and provide your JDK path using the `PDFSAM_JAVA_PATH` env variable
