### ISSUE TITLE
Table of contents (TOC) does not reflect reordering of merged files

### ISSUE THREAD

**Issue by fisketjon** [torakiki/pdfsam#461]
Table of contents (TOC) does not reflect reordering of merged files. 
Example: Add some pdf files to be merged. Use drag & drop to reorder. Generating TOC from file names use initial sequence of merged files.

**Comment by torakiki** [comment]
What version are you using? I just tested the latest version and it seems to work fine

**Comment by fisketjon** [comment]
I'm using version 4.2.5. Tested again now, but unable to replicate the error now - no matter how hard I try :) Useful tool! Thank you!
