### ISSUE TITLE
Problem building the project

### ISSUE THREAD

**Issue by kkathpal153** [torakiki/pdfsam#462]
I tried building the tool using IntelliJ ide.
I am not a professional at this but it seems like it needs some files which are not even there.
[log.txt](https://github.com/torakiki/pdfsam/files/6542753/log.txt)

**Comment by torakiki** [comment]
From what I can see it failed trying to build the MSI installer.
Have you tried to manually run the C:\Users\kunal_kathpal\IdeaProjects\pdfsam\pdfsam-basic\target\msi\Build.cmd script?
