### ISSUE TITLE
Split files with annotations are big

### ISSUE THREAD

**Issue by Junkyver** [torakiki/pdfsam#463]
When I split pages that have annotations the output file its big like the original
I did a few tests, you can extract any page without annotations and don't have any a problem, not matter if the selected pages are in between annotations pages, but if you select just one page with annotations the output file will be of the same size.
Version 4.2.5

Anyway, thank you so much for the app, is very useful.

**Comment by torakiki** [comment]
I need to look at the file but what you described is not unusual. PDF format is not like a text file where if you cut the file in half you can expect roughly half the size. PDF is a complex graph of objects pointing to other objects and so on and optimizing it during the split is not a perfect science.
If you can attach the file I'll take a look, maybe there is something that can be done better
