### ISSUE TITLE
Merge function delete the content of the fist page

### ISSUE THREAD

**Issue by SoyClara** [torakiki/pdfsam#464]
Hi everyone! the merge option in Basic Edition delete only the content of the first page (not the phisical page), but the color marks on this first page remains.
The rest of the content it is OK

INFO   [00:12:54]: Starting PDFsam
INFO   [00:13:00]: Configuring Sejda 4.2.5
INFO   [00:13:03]: Iniciado el 9 seconds

![Sin título](https://user-images.githubusercontent.com/85090414/120135602-03a86980-c1a7-11eb-87c3-7981972b0c30.png)
![Sin título2](https://user-images.githubusercontent.com/85090414/120136010-cee8e200-c1a7-11eb-8f0e-af08a41599ab.png)
![Sin título3](https://user-images.githubusercontent.com/85090414/120136174-2d15c500-c1a8-11eb-93a1-56de4bdc2d82.png)

**Comment by torakiki** [comment]
Hi,
what PDF viewer are you using and have you tried other PDF viewers?
Can you provide the PDF files so we try to reproduce?
