### ISSUE TITLE
W10, pdfsam unpinnable on taskbar

### ISSUE THREAD

**Issue by carloswm85** [torakiki/pdfsam#468]
The option is not offered in my W10 (*MINGW64_NT-10.0-19043*) system when I right-click on the taskbar.

![image](https://user-images.githubusercontent.com/29048235/129920516-f579d159-8cb6-4f0a-a61a-a60921c0d7ce.png)

The text says "Close window".

I installed pdfsam from the official website, using the msi installer. I'm behind a proxy, so that's the only installation alternative I could use.

**Comment by mara004** [comment]
Could you try pinning PdfSam from the start menu, maybe?

**Comment by carloswm85** [comment]
> Could you try pinning PdfSam from the start menu, maybe?

It somewhat worked... ?

This is what I got.
![image](https://user-images.githubusercontent.com/29048235/130305436-8dcd2d4b-9426-4a72-9318-b8d181aff8c2.png)

But when I click it...
Image 1.
![image](https://user-images.githubusercontent.com/29048235/130305458-9cb57320-9f2f-4963-b753-327d12517cb0.png)

Image2.
![image](https://user-images.githubusercontent.com/29048235/130305468-deb8f23e-2b39-4081-a936-a3f884d50b99.png)


Working, but not really working.
