### ISSUE TITLE
Create RPM package

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#47]
Add scripts to create an RPM package

**Comment by Fale** [comment]
You can assign it to me, even if I can not grant you that it will be ready for 3.0.0.M2. I'm looking into it and I hope it will be ready before 3.0.0 :)

**Comment by NuxRo** [comment]
Hello, any SRPMS or spec files available?

**Comment by torakiki** [comment]
Not yet, as PDFsam v3 is still on development there's no installation package yet, just the zip bundle. Once the software is stable enough I'll start looking at the installation bundles.

**Comment by NuxRo** [comment]
Understood, thanks.
Any chance you can share the v2 SRPM/spec, btw?

**Comment by torakiki** [comment]
There's no Linux package for version 2.. at least none maintained by me.

**Comment by vinyanalista** [comment]
I know how to build RPM packages and I'm trying to do that. But I'm stuck at #352...

**Comment by vinyanalista** [comment]
There is one RPM built for v3.3.7 at [build.opensuse.org](https://build.opensuse.org/package/show/home:Sauerland/pdfsam), but since networking is not allowed in OBS (thus it is difficult to use Maven), the packager actually just repacked the zip archive downloaded from the PDFsam website (that RPM file was not built from source using Maven).

**Comment by vinyanalista** [comment]
I created a `pdfsam-basic` RPM package at [build.opensuse.org](https://build.opensuse.org/package/show/home:kamarada:15.1:dev/pdfsam-basic).

The most important file is the [`pdfsam-basic.spec`](https://build.opensuse.org/package/view_file/home:kamarada:15.1:dev/pdfsam-basic/pdfsam-basic.spec?expand=1), analogous to a `control` file for a DEB package.

For the same reason, my package was not built from source, but just a repacking of the v4.0.1 zip archive.

I'm working on an alternative spec file ([`pdfsam-basic.spec.alternative`](https://build.opensuse.org/package/view_file/home:kamarada:15.1:dev/pdfsam-basic/pdfsam-basic.spec.alternative?expand=1)) that could be built locally from source using Maven and [rpmbuild](https://linux.die.net/man/8/rpmbuild).

Please let me know if you want me to do a pull request.

**Comment by vinyanalista** [comment]
Right now anyone using a RPM distribution can install the RPM package I built running:

```
# rpm -Uvh https://download.opensuse.org/repositories/home:/kamarada:/15.1:/dev/openSUSE_Leap_15.1/x86_64/pdfsam-basic-4.0.1-lp151.1.1.x86_64.rpm
```

[openSUSE](https://www.opensuse.org/) users can run:

```
# zypper ar -f -K -n "Linux Kamarada" https://download.opensuse.org/repositories/home:kamarada:15.1:dev/openSUSE_Leap_15.1/ kamarada
# zypper ref
# zypper in pdfsam-basic
```

**Comment by torakiki** [comment]
We already provide a .deb and a portable package. There is some rpm out there, not maintained by us. I don't think we will implement this, mostly given the rising popularity of packaging like flatpack or snap. I'm more include to investigate and implement those.
