### ISSUE TITLE
[Feature] Add compress pdf "standalone"

### ISSUE THREAD

**Issue by kintaro1981** [torakiki/pdfsam#471]
Hello, I saw that is possibile to automatically compress pdf during the save process, and is working very well.

How about adding another button in the dashboard to simply compress PDF?

**Comment by torakiki** [comment]
Some tasks do automatically optimize the output files, meaning they discard unused resources. The compress task, which involves compressing images, possibly removing undesired internal data, possibly convert to B/W images etc.. it's available in PDFsam Visual as a premium feature so we are not planning to bring it Basic
