### ISSUE TITLE
Can't verify packages, GPG keys return no user ID

### ISSUE THREAD

**Issue by trevor33trevor** [torakiki/pdfsam#472]
In the website it is told that we can verify files after retrieving the key with:
`gpg --search-keys BF019D784ED7F785`

which now returns:

```
gpg: data source: https://keys.openpgp.org:443
(1)	  4096 bit RSA key BF019D784ED7F785, created: 2018-12-20
Keys 1-1 of 1 for "BF019D784ED7F785".  Enter number(s), N)ext, or Q)uit > 1
gpg: key BF019D784ED7F785: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```
I"ve also checked the displayed keyserver with:
`gpg --keyserver https://192.146.137.98:443 --search-keys BF019D784ED7F785`

But again no results. This has to be fixed.

**Comment by torakiki** [comment]
I get this using different key server:
```
$ gpg --keyserver keyserver.ubuntu.com --search-keys BF019D784ED7F785
gpg: data source: http://162.213.33.9:11371
(1)	Sober Lemur S.a.s. <info@pdfsam.org>
	  4096 bit RSA key BF019D784ED7F785, creata: 2018-12-20

$ gpg --keyserver pgp.mit.edu --search-keys BF019D784ED7F785
gpg: data source: http://pgp.mit.edu:11371
(1)	Sober Lemur S.a.s. <info@pdfsam.org>
	  4096 bit RSA key BF019D784ED7F785, creata: 2018-12-20
```

**Comment by trevor33trevor** [comment]
Alright thanks. I did try with another server but it was my fault for not checking the popular "keyserver.ubuntu.com". I'd suggest updating the site where you may give a full script like:
`gpg --keyserver keyserver.ubuntu.com --search-keys BF019D784ED7F785`
or maybe suggesting the ubuntu server so that others don't also replicate my dumb mistake.

Oh and... THANKS for the great program. I really do love it.
