### ISSUE TITLE
Update Bundled OpenJDK Q4 Security Release

### ISSUE THREAD

**Issue by stondino00** [torakiki/pdfsam#474]

**Comment by stondino00** [comment]
Just a reminder about this bundled security update.  Thanks

I'd upgrade the \runtime\folder manually if I knew where you get that bundled fx from.

**Comment by stondino00** [comment]
How can I simply download an updated version of the runtime folder from somewhere and just replace that directory on my Windows installs with the latest version?

**Comment by torakiki** [comment]
The one we is the one provided by Eclipse https://adoptium.net/ but you can use any JRE.

**Comment by stondino00** [comment]
Thanks so much for updating the build.  I appreciate it!  Keep up the good work!
