### ISSUE TITLE
Silent Installs and Web Page

### ISSUE THREAD

**Issue by damon-atkins** [torakiki/pdfsam#476]
Silent installs fail with browser being sent due to the https://pdfsam.org/thanks/ page.  As a web page can only be open if a user logged onto the desktop runs the silent install.

Thanks for the tool

**Comment by torakiki** [comment]
See here https://github.com/torakiki/pdfsam/wiki/Properties-and-arguments there is a `SKIPTHANKSPAGE` property you can use.
