### ISSUE TITLE
Any plan to support Mac M1 natively ?

### ISSUE THREAD

**Issue by ivaquero** [torakiki/pdfsam#482]

**Comment by torakiki** [comment]
There isn't any plan. From what I can see it shouldn't be a problem, both Java and JavaFX are available for that architecture. I'm planning to rework the release process with some more automation, maybe it can be added there but I don't really have a plan for that at the moment

**Comment by ivaquero** [comment]
Thank you so much for your reply. I understand that there aren't enough motivation as PDFsam currently works well under Rosetta 2. 

Really appreciate your work, thanks again.

**Comment by Teko012** [comment]
@torakiki Do you happen to have any update about this?

**Comment by Teko012** [comment]
@ivaquero I don't think this was completed, was it?

**Comment by ivaquero** [comment]
> @ivaquero I don't think this was completed, was it?

Oh, sorry, I clicked close by accident.

**Comment by Teko012** [comment]
@ivaquero Does it let you reopen it?

**Comment by ivaquero** [comment]
Unfortunately, I don't find the reopen choice. Sorry, I cleaned my issue list by updated date.
