### ISSUE TITLE
PDFsam - how to etst a new localiation file (.po)?

### ISSUE THREAD

**Issue by bovirus** [torakiki/pdfsam#487]
@torakiki 

When I created a new translation file how can test using latest version of PDFsam?

Thanks.

**Comment by torakiki** [comment]
There is no easy way to do that.. if you are familiar with Java development I could guide you on how to create a test release.
Another option could be (I think) to convert the .po to a .properties with GetText and replace the one in the pdfsam-i18n jar.. it's a bit hackish but it should work
