### ISSUE TITLE
how to update pdfsam

### ISSUE THREAD

**Issue by waess** [torakiki/pdfsam#495]
I installed pdfsam on Linux mint 19.3 some times ago.
LM Software Manager offers still the old vulnerable version 4.0.1, so the update manager does not update. PDFsam.org recommends to download version 4.2.12, but does not give any instructions how to proceed. After unpacking the download file 
pdfsam-4.2.12-linux.tar.gz 
the subdirectories of pdfsam-4.2.12-linux do  not contain any information how to proceed, no README-file, nothing, and the ./configure command does not work
Running the pdfsam.sh file (date 20.1.2022) in terminal opens the program, but is still the old version recommending the update to version pdfsam-4.2.1.
What is wrong?

**Comment by torakiki** [comment]
One workaround is to completely uninstall the Software Manager version and download the .deb we provide (or use the tar.gz you already have).
I'm not sure what could be the issue, I just tried the same steps (I'm on Mint 20.3) and everything worked, the latest version runs from the command line script even if an old version is installed via software manager.
```
torakiki@torakiki-lenovo:~/Scaricati/pdfsam-4.2.12-linux/bin$ ./pdfsam.sh 
Mar 04, 2022 12:07:15 PM com.sun.javafx.application.PlatformImpl startup
AVVERTENZA: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3969f471'
INFO  12:07:16.082 o.p.PdfsamApp[JavaFX-Launcher] Starting PDFsam
INFO  12:07:17.320 o.s.c.c.GlobalConfiguration[JavaFX Application Thread] Configuring Sejda 4.2.11
INFO  12:07:17.889 o.p.PdfsamApp[JavaFX Application Thread] Avviato in 1 second
```
