### ISSUE TITLE
Transforms to disable updates

### ISSUE THREAD

**Issue by danxavy** [torakiki/pdfsam#500]
Hi! This is a great tool which we want to deploy to some users who require pdf merging, rotating and splitting. I have been creating the configuration settings ready to deploy to some test users but unable to find the switch setting to disable the updates button. We can't have users update manually as we like to keep the updates controlled by our software deployment team.
Is there a switch command to disable the update button?
Thanks
Br
Dan

**Comment by danxavy** [comment]
I know we can disable the whole of the setting panel but we would like at least to leave the language option available so don't want to go down that route. Just need to grey out the "Check for updates now" button
Thanks

**Comment by torakiki** [comment]
Do you need to disable the ability to update the software (there is no autoupdate at the moment so this is not an issue I think), or disable the the ability to just verify if an update is available?
