### ISSUE TITLE
Install PDFsamBasic

### ISSUE THREAD

**Issue by HappyPony** [torakiki/pdfsam#501]
Hello,

I have downloaded and installed the file PDFsamBasic7Installer.exe here https://pdfsam.org/download-pdfsam-basic/. In the process I notice that PDFsam basic has been replaced by PDFsam Enhanced 7 on my PC. Is it a desired behavior of the program file PDFsamBasic7Installer.exe or a bug?

**Comment by JackAndersen** [comment]
I believe there is a checkbox in the installation proces, that installs the Enhanced version for trial. You might have checked that box.
