### ISSUE TITLE
PDF from text/csv fails when path includes comma

### ISSUE THREAD

**Issue by caligari87** [torakiki/pdfsam#505]
Simplified example 
```
Z:\Jobs\Job Name, With a Comma\Coversheet.pdf, 8181, 1
Z:\Datasheets\Equipment ABC.pdf, 12574, 8
Z:\Datasheets\Equipment XYZ.pdf, 94177, 4
Z:\Datasheets\Equipment HAL.pdf, 722474, 24
```
In the example above, the file `Coversheet.pdf` will fail to load because the path to the file contains a comma.

My recommendation would be to have file paths escaped with quotes when copied from the file list in PDFSam. 
```
"Z:\Jobs\Job Name, With a Comma\Coversheet.pdf", 8181, 1
"Z:\Datasheets\Equipment ABC.pdf", 12574, 8
"Z:\Datasheets\Equipment XYZ.pdf", 94177, 4
"Z:\Datasheets\Equipment HAL.pdf", 722474, 24
```
At least on Windows, the quotes character is not supported in file/folder names. On Linux the situation might be more complicated (not sure on Mac), but there individual path characters are typically escaped with `\` so quote characters within a file path could be handled thusly:
```
"/home/username/Jobs/\"Job Name\", With a Comma and Quotes/Coversheet.pdf", 8181, 1
```

**Comment by caligari87** [comment]
Relatedly, it would be helpful to get an error or warning notification when the imported file list has an error. Right now, it just fails silently.

**Comment by chucklu** [comment]
It seems the path with space in it, can not work

> \OneDrive - Company\
