### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by G-Wellman** [torakiki/pdfsam#507]
Hello, I am using portable exe version 4.3.0 of PDF-SAM Basic in Windows 10 Pro 64 bit. 
1.  When drag & drop files (pdfs) from windows explorer into the Merge Tab (and probably other tabs too, I just haven't tried it), the new item gets placed at the bottom of the list that is already there.  It can then be dragged into a higher position.  Is it possible to make it so that the location where you drop the new file is where it slots into the list to save the second step?  This would be especially useful when the list extends beyond 1 page view.  You would then be able to scroll through the list and then drag & drop the new file where required.  
As a second improvement:
2.  The current behavior unfortunately only allows you to drag from the bottom to the top of the visible items on screen, then drop it, then scroll the view further up, then select the file again and drag to the top of the visible items on screen, then drop it again, and so on until you find the final location.   Could you change it so that dragging further than the top (or Bottom) of the screen causes the list to either scroll or page up/down?

**Comment by IdelsTak** [comment]
The behavior is also apparent on `ver 5.2.1-SNAPSHOT` also: 

https://github.com/torakiki/pdfsam/assets/46872727/77fcbaa4-297a-41bd-bac4-b1aaf1e1ff0a
