### ISSUE TITLE
Sort issue reported by a user

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#516]
Secondly, files are automatically sorted
alpabetically, and as I'm norwegian, I use files
names with norwegian characters. Our alphabet is
similar to the english with tre additional letters
at the end: XYZÃÃÃ, in this order.
However, PDFsam sorts Ã as an A, which it is not.
Finder handles this correctly, and it would be
good for a pdf program to have support for
international alphabeths.

**Comment by KVolker** [comment]
In German we have the same issues often the other way around: we have umlauts (äöüß) and some programs sort them to the end (they just use the ANSI codes for sorting, I suppose), which is against the sorting rule in German, which is to "overlook" the umlaut (ß is treated as "ss"). The same is true for French and Spanish, where á or ñ go along as a and n. So for some languages to fall back to "ANSI-sorting" would be a downgrade.
