### ISSUE TITLE
Request: Can you create keyboard shortcuts for the Select PDF en Run buttons on the Split by Bookmark screen?

### ISSUE THREAD

**Issue by sprunkys** [torakiki/pdfsam#522]
There are a lot of mouse movements when having to bookmark-split multiple files
and keyboard shortcuts would drastically limit the distance to move across the screen

Thanks for considering this request and have a great day!

(check paypal of today)

**Comment by torakiki** [comment]
For the Select button there's a `ALT+s` shortcut, if you press `ALT` the letter should underline, while in every tool the `CTRL+x` shortcut will trigger the Run button.... maybe I can add a shortcuts summary somewhere
