### ISSUE TITLE
java heap memory error

### ISSUE THREAD

**Issue by chinche33** [torakiki/pdfsam#523]
hi, i tried to read the documentation about this error, i have pdfsam 4.3.3, when i open the ini file to change the size of memory allowed, i dont have the row. see: 
# add here runtime options, one per line
-Dprism.lcdtext=false
-Dorg.pdfsam.default.checkforupdate=true
-Dorg.pdfsam.default.donate.notification=true
-Dorg.pdfsam.default.locale=en_GB
-Dorg.pdfsam.default.checkfornews=true
-Dorg.pdfsam.default.play.sounds=true
-Dorg.pdfsam.default.fetch.premium.modules=true

Maybe that can help: 
PDF Split and Merge Basic Edition
4.3.3
OpenJDK Runtime Environment 11.0.16+8-LTS
Fournisseur : BellSoft
chemin d'accès à Java runtime : C:\Program Files (x86)\PDFsam Basic\runtime
JavaFX runtime version 17.0.2-ea+3
Mémoire maxi. 247 MB

-Dorg.pdfsam.default.compression=true
-Dorg.pdfsam.default.output.overwrite=false

What shoudl i do?

**Comment by torakiki** [comment]
To increase the available memory add this row to the pdfsam.l4j.ini:
`-Xmx2G`
This will give 2 Gb to PDFsam, you can set different amounts and use `M` in case of MegaBytes, like `-Xmx512M`

**Comment by chinche33** [comment]
Thank you a lot ❤️

Le mar. 22 nov. 2022, 12:37, Andrea Vacondio ***@***.***> a
écrit :
