### ISSUE TITLE
Drag and Drop closes GUI in Windows

### ISSUE THREAD

**Issue by claudioweiler** [torakiki/pdfsam#526]
When dragging a PDF file to the PDFsam Basic window, the GUI is closed. Java process still running and needs to be force finished in task manager.

Running with pdfsam.bat changes nothing, and no logs are shown in console. Log levels are set to ALL.

- Windows 10
- PDFSam 4.3.4
- Internal JDK BellSoft 11.0.17

---
**edit 1**

Behavior is not consistent:

- It can, sometimes, work flawless
- It can fail when dragging 1 PDF
- It can fail when dragging multiples PDFs
- It can fail when dragging more PDFs after a successful PDF added

**Comment by torakiki** [comment]
Can you please try version 5? https://github.com/torakiki/pdfsam/releases/tag/v5.0.0.M1
It's not the stable release yet but that's where development effort is focused now

**Comment by claudioweiler** [comment]
Hi @torakiki, sorry for delay.
Just tried version 5-M1 with same behavior. I do not removed version 4.

**Comment by torakiki** [comment]
Ok @claudioweiler  thanks for testing it. If there is no error message or log or anything I'm not sure how I to investigate this. I'll try to set up a Windows 10 machine and see if I can reproduce it

**Comment by claudioweiler** [comment]
Sure @torakiki, I understand it.
If I can help with something more, let me know!

**Comment by torakiki** [comment]
Is there any error message or stacktrace or anything that we can investigate? Maybe starting from the command line?

**Comment by av1ctor** [comment]
Hi, @torakiki. 

Just tried that and the log shows nothing new after the window closes (when a file is dragged over it): 

![image](https://user-images.githubusercontent.com/35101441/223764390-98fe0b73-c197-4c9f-847b-fa69cef7e2ca.png)

The process still running in the background:

![image](https://user-images.githubusercontent.com/35101441/223764978-e71fd466-ac83-4507-8da9-47530f7ef14a.png)

**Comment by claudioweiler** [comment]
I don't know if it can help somehow, but...

Here a dump of events collected by [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) in the very moment when dragging a file to the UI:

[pdfsam.log](https://github.com/torakiki/pdfsam/files/10923352/pdfsam.log)

**Comment by claudioweiler** [comment]
Also, I'm not aware of JavaFX, but there is any way to receive (hook) close events generated by the UI? If possible, maybe some additional logging can be enabled.

**Comment by av1ctor** [comment]
I think I found the reason.. It was TOPAZ OFD/Warsaw, a rootkit that the brazilian banks require you to install to be able to use their online banking.

I just removed TOPAZ OFD/Warsaw (you have to reboot first) and the drag & drop began to work again on pdfsam.

@claudioweiler, as your are from Brazil too, I guess you probably have some of those installed also.

**Comment by claudioweiler** [comment]
Hi @av1ctor!
 
Yes, I have Warsaw ($%# you Banco do Brasil/Caixa)! Unfortunately I can't uninstall him, so I can't confirm this will solve the problem, but too much coincidence for it.

**Comment by torakiki** [comment]
Great, thanks for finding the cause, I could have never find out. Nothing I can do about it but at least I can point other users here in case they have the same issue.

**Comment by claudioweiler** [comment]
Opened an issue on Topaz OFD. Hoping they solve this...
