### ISSUE TITLE
5.0.2 default working directory not functioning

### ISSUE THREAD

**Issue by bigben386** [torakiki/pdfsam#532]
Hi,
The default working directory setting does not appear to be working in 5.0.2 on windows. Users have set the default directory and have the output directory set to manual in pdfsam settings.  If you just type a filename into the destination box, then the operation fails with a permission denied error. If you click browse, pdfsam defaults to the _This PC_ folder.

**Comment by torakiki** [comment]
The output folder for the split tasks is now automatically populated with the default working dir.
I tested on Windows and Linux and all the Browse buttons open pointing to the working dir... what is your OS? Because from my tests it works as expected.
What I couldn't fix is when you type the output file name without the absolute path. In theory is fixed (the sys property user.dir is set) but in practice Java seems to ignore it, I have to investigate further or workaround this.

**Comment by bigben386** [comment]
Hi @torakiki ,

Here is a video of what is happening on 5.1.3. Default working directory is set. Add some files to the merge window. Notice the destination file is not created in the specified default folder. Also if you click the browse button, it defaults to "This
[google_screen_recording_2023-10-26T13-09_23.604Z.webm](https://github.com/torakiki/pdfsam/assets/9749364/7bac1b2b-01bb-4573-b466-84995dd3ea57)
 PC" and not the specified default working directory. This was recorded on win11.

**Comment by torakiki** [comment]
From what I can see from the video, what you get is the expected behavior because you have selected "Use the selected PDF document directory as output directory", try select "Manually selected"

**Comment by bigben386** [comment]
OK. I set it to "manually selected." Like you said, just entering a file name does not behave as expected. I did find that if you open the merge module and immediately click "Browse," you are taken to the default working directory. However, if you add the files first and then click "Browse," it is still defaulting to "This PC" for me and not the default working directory.

**Comment by torakiki** [comment]
Yes, that's what I was saying I couldn't fix. In the next version I added what should be a fix for that, I set the `user.dir` property to the user defined working directory but it seems it's ignored by Java and, when a file without the absolute path is created, it's not placed into the proper directory

**Comment by bigben386** [comment]
Yeah I understand what you are saying about the relative file path but the browse button also does not work after you add files to the merge module. The browse button only opens to the default working directory if you click it before adding files.
Clicking browse before adding files:
![image](https://github.com/torakiki/pdfsam/assets/9749364/a98e6728-71f1-4061-a98a-1a2fca76ad6c)
clicking browse after adding files to merge module:
![image](https://github.com/torakiki/pdfsam/assets/9749364/3811c057-77e0-4f10-aadf-e6784510b790)
