### ISSUE TITLE
msi parameters not working with 5.0.2

### ISSUE THREAD

**Issue by bigben386** [torakiki/pdfsam#533]
Hi,
We have also noticed the msi parameters are not working with 5.0.2. 
Here are the parameters we set:
CHECK_FOR_UPDATES=false DONATE_NOTIFICATION=false SKIPTHANKSPAGE=Yes CHECK_FOR_NEWS=false PREMIUM_MODULES=false
but here are the settings in pdfsam
![image](https://user-images.githubusercontent.com/9749364/216627263-451acd2c-be83-4f21-ae4a-a44622fec839.png)
Thanks

**Comment by torakiki** [comment]
Can you take a look at the file `app/pdfsam.cfg` and see if the system properties associated with those parameters are set?

**Comment by bigben386** [comment]
No. There is no reference to those settings.
`[Application]
app.mainmodule=org.pdfsam.basic/org.pdfsam.basic.App

[JavaOptions]
java-options=-Djpackage.app-version=5.0.2
java-options=--enable-preview
java-options=-Dprism.lcdtext=false
java-options=-splash:$APPDIR\..\splash.png
java-options=--module-path
java-options=$APPDIR\mods
`

**Comment by torakiki** [comment]
We released version 5.0.3, it's fixed there
