### ISSUE TITLE
Make variables [CURRENTPAGE] and [FILENUMBER] available with trailing zeros

### ISSUE THREAD

**Issue by KVolker** [torakiki/pdfsam#534]
It would be helpful to have in the "split" dialog in the "file name prefix" field variables [CURRENTPAGE] and [FILENUMBER] available with trailing zeros, e.g. as [CURRENTPAGE_000] and [FILENUMBER_000]. It would help to have the files in an ordered sequence in Explorer or file dialogs etc. in case you configure the filenames to be "[BASENAME]_[CURRENTPAGE]" for example.

**Comment by torakiki** [comment]
Hello,
see here https://pdfsam.org/customize-file-names/ it's already available

**Comment by KVolker** [comment]
Thanks a lot for this hint, that helps a lot because it does the thing I need. May I change the change request to: "The help tooltip ('?') at the file name input field shall mention this possibility or put a link to this help page right beside it"? I mean, to be honest, who reads the manual? (OK, yes I know, but...)

;-)

Anyways, thanks for the work you put into this program, I am a developer also, and I know what that means. Donation donated.
