### ISSUE TITLE
Issues with software restriction policies - please move dll/executable files and scripts to Program Files on windows

### ISSUE THREAD

**Issue by mkuzmanis** [torakiki/pdfsam#535]
Hi,

I was testing PDFSam for deployment in environment with software restriction whitelisting policies (which should be enabled in most active directory environments), and it looks like it has quite a lot of dll files under %userprofile%\.openjfx
Please move these to program files, so that all executables/scripts are located in place where user has no write access by default.

Thanks

**Comment by torakiki** [comment]
Hello,
that's not PDFsam specific but it where JavaFX caches dlls (and perhaps other files) so every JavaFX application stores files there.
You can use the javafx.cachedir sytem property to modify the default directory to something that meets your deployment needs, see here https://stackoverflow.com/questions/53382810/configure-openjfx-11-to-extract-its-dlls-into-a-different-user-specified-directo
You can add a java option to the `pdfsam.cfg` text file in the PDFsam Basic `app` subdirectory, find the `[JavaOptions]`section and add a row `java-options=-Djavafx.cachedir=c:\somewhere`

**Comment by mkuzmanis** [comment]
Hi,
Regarding this and issue #543 - we are using multiple other java based applications like Libre office that store these files in %programfiles%, and users can't modify them. Is it possible to move these files or sign them with certificate?

**Comment by torakiki** [comment]
With the solution mentioned here you can set the directory for the JavaFX dlls so I think you can place them wherever you want.. can you clarify what is not working with this solution?

**Comment by mkuzmanis** [comment]
Currently tested it by adding folder "cache" under PDFsam Basic\app folder and copying cached data to that and added line:
java-options=-Djavafx.cachedir=$APPDIR\cache  
to pdfsam.cfg file.
It looks like it launches even if user is unable to write to that folder, as long as dll files are located there.
Can this probably be added as option to installer? If user is unable to write to cache folder, I don't think it's necessary to sign those dlls. This would also save space in multi user environments.
