### ISSUE TITLE
Field names in form not unique after merge multiple of same form

### ISSUE THREAD

**Issue by CosBanFool** [torakiki/pdfsam#540]
I was completing a US tax return that required multiple Form 5472 (https://www.irs.gov/pub/irs-pdf/f5472.pdf).
I filled out the PDF form online using Google and downloaded 3 variations. I then merged the 3 variations into 1 document.
After the merge, I opened the new file to check the information.
The check box in Part V of the form acted across all 3 merged versions of the document. If I check the box in one place, all 3 check boxes became checked.

[f5472.pdf](https://github.com/torakiki/pdfsam/files/10975687/f5472.pdf)

**Comment by torakiki** [comment]
That's the expected behavior if you just merge the existing fields but I don't see this behavior if the appropriate "merge renaming existing fields" policy is selected.
