### ISSUE TITLE
PDFsam Enhanced/FinePrint incompatibility

### ISSUE THREAD

**Issue by ALNRYAN** [torakiki/pdfsam#550]
FYI I won't be reinstalling or using PDFsam Enhanced and have no interest in the resolution of the issue following. But you may wish to investigate?

After installing PDFsam Enhanced, using FinePrint 6.13 (yes I know) consistently produced the message "internal error - ... unable to launch the dispatcher" every time I tried to print.  I rebooted/uninstalled/rebooted/reinstalled FinePrint/rebooted  all to no effect.

I have now uninstalled PDFsam Enhanced and immediately and so far permanently FinePrint is working normally again.

cheers
A

**Comment by torakiki** [comment]
Thanks for reporting
