### ISSUE TITLE
Option to set default output PDF version

### ISSUE THREAD

**Issue by opusforlife2** [torakiki/pdfsam#555]
Hi, the default PDF version is set to 1.5, the minimum available. If the user wants to use a newer version, they have to adjust it every time the application is used. Could this be made an option in settings, so that we can set the default version to 2.0, for example?

**Comment by AndreaBaldeschi** [comment]
I have the same question/request/suggestion (put as default output version to 2.0) n, more, I would ask if shall be possible to set as default "discard bookmarks" too.
tks
![pdfsam](https://github.com/torakiki/pdfsam/assets/146051491/fe69c32f-5fd1-4a42-ae7e-acd7ec33b1b0)
