### ISSUE TITLE
Does not  display Arabic letters properly on Ubuntu 23.04

### ISSUE THREAD

**Issue by bader-nasser** [torakiki/pdfsam#557]
The app shows weird boxes in extract and split sections. It's hard to know the files!
![Screenshot from 2023-09-10 00-35-15](https://github.com/torakiki/pdfsam/assets/135460713/0d6232d9-1134-49da-b7c8-1b5a8edff184)
It should be displayed as:
![Screenshot from 2023-09-10 00-34-58](https://github.com/torakiki/pdfsam/assets/135460713/3a7980da-1485-46f2-85ca-69b81ab6830d)

Also, the dialog "Directory not empty" is not displayed properly, I just see a small black rectangle:
![Screenshot from 2023-09-10 00-52-31](https://github.com/torakiki/pdfsam/assets/135460713/faaf0fff-ac47-4463-a7d2-442bd1d78b37)

Side question: Can I use the app completely from the command line?

**Comment by torakiki** [comment]
I tried with brand new virtual machine using the Ubuntu 23.04 ISO file, installed PDFsam Basic, run it and it seems to load the files correctly, arabic letters shown properly:
![immagine](https://github.com/torakiki/pdfsam/assets/3884479/dbe70503-1d23-46aa-b09b-16a5ddd6fa09)
It seems to me it's something in your system configuration, not sure what it might be... maybe a missing font? Have you tried running the application form the command line?
There is no way to execute the tasks from command line, if that's what you mean by "completely from command line". We have a CLI at https://sejda.org but it's not open source.
