### ISSUE TITLE
windows 10 license problem

### ISSUE THREAD

**Issue by feiltom** [torakiki/pdfsam#559]
Hello 
i have a problem on windows 10 compteur.
we try to instal a pdfsam [v4.3.4](https://github.com/torakiki/pdfsam/releases/tag/v4.3.4) with a license.
License is not apply and ask at each start.
we have test also with a fresh Windows 10 install with no succes.
We have make many test and one have a strange result: we can'not open the pdfsam website on edge browser on windows 10 ( OK with windows 11 or with chrome )

have a recommandation ?

**Comment by torakiki** [comment]
Hi,
you don't need any license in PDFsam Basic, it's free and open source and it should just work. Regarding the website and other issues, can you please send an email to support@pdfsam.org ? Maybe attaching a screenshot
