### ISSUE TITLE
[request] Unique files list window for all tools

### ISSUE THREAD

**Issue by HektorStG** [torakiki/pdfsam#566]
Hello,

Could be nice to have one unique files list window common for all tools.

That is to say, sometimes, I drag files in the window before having choosen the right tool (oops !). So I have to click the tool and drag the files again in the window of the tool.
If the were a unique window, one could be able to change of tool without having to drag files one more time.

Files windows are quite similar. Some options columns differ, but I think the differences can be managed with gray columns if not needed by the chosen tool.
Some tools haven't a files window, only one file name. The first file of the list can be used, the others changed into gray.

Thanks for all.
HektorStG

**Comment by torakiki** [comment]
Hello,
thanks for the suggestions but I don't think I'm going to follow that route. I always tried to keep tools simple and well defined. The UI, at least for some of the tools, is already quite busy and it would become even more confusing if I start adding grayed out fields or columns.
Talking about your issue, if I understood correctly, you can drop the files on the tool description:

![Peek 07-12-2023 09-41](https://github.com/torakiki/pdfsam/assets/3884479/148cb5c5-6004-4d20-bd26-bed7eaf4449a)
