### ISSUE TITLE
Upgrade bundled jdk

### ISSUE THREAD

**Issue by stondino00** [torakiki/pdfsam#571]
Oracle releasing first quarter java updates today for security fixes.

**Comment by stondino00** [comment]
Just a reminder on this.  Thanks

**Comment by stondino00** [comment]
I'm still seeing the old java bundled in 5.2.2.

![image](https://github.com/torakiki/pdfsam/assets/54154986/158227df-e584-4c9f-90e4-dbf7b77a0eda)

**Comment by torakiki** [comment]
Yes, sorry about that. I update the release, please download the MSI again and it should be fixed

**Comment by stondino00** [comment]
Thanks so much!
