### ISSUE TITLE
PDFsam Enhanced - > merge  -> Folder browser 

### ISSUE THREAD

**Issue by SerhiiLeshchenko** [torakiki/pdfsam#590]
Please make it possible to paste a folder address and remember lastly added folder
![image](https://github.com/torakiki/pdfsam/assets/74424188/4bb0c3fd-40f1-46e5-b485-dd4a146aaa8b)
![image](https://github.com/torakiki/pdfsam/assets/74424188/38ccde46-da11-44d2-9a9f-fb1db38db8e9)

**Comment by torakiki** [comment]
Please use the Contact Us button on the support center here https://support-enhanced.pdfsam.org/hc/en-us
This issue tracker is only for the OSS version, PDFsam Basic
