### ISSUE TITLE
Merge PDF only with selected pages

### ISSUE THREAD

**Issue by nscQPL** [torakiki/pdfsam#593]
In the version PDFsam Enhanced 6 there was an option to choose the pages that should be included when merging PDFs. In PDFsam Enhanced version 7 I can only select the files to be merged, but I cannot exclude single pages anymore. This option is crucial for me and that is why I downgraded to version 6 again.

**Comment by torakiki** [comment]
For PDFsam Enhanced please write to support_enhanced@pdfsam.org
