### ISSUE TITLE
Page selection in Merge module not fully functional

### ISSUE THREAD

**Issue by jmiller123** [torakiki/pdfsam#61]
just downloaded the latest version of v3 (thanks!!) but the split/merge module does not delete pages not included in the page selection field. if I try to combine a 3-page document with a 1-page document, and specify pages 1-2 for the first document (cutting off page 3), the merge simply combines the two documents resulting in a 4-page document instead a pages 1-2 of the first document plus page 1 of the second document. Same thing, if I specify something like "1-5,9-10" of a multipage document. All pages are included, instead of eliminating pages 6-8 (per my example).

**Comment by torakiki** [comment]
The thing here is that an Enter key press is needed to commit the page selection to the selection table, so basically type your selection, hit enter, hit run and everything works as expected. What is missing is the commit of the changes on focus lost (type your selection, hit run and you would expect your selection take into account) and this is Java bug https://bugs.openjdk.java.net/browse/JDK-8089514 
I'll look for a workaround as I understand it's a "must have" feature.

**Comment by jmiller123** [comment]
Thanks for following up. I will try the latest beta, being sure to click “enter” even though that is counter-intuitive. Agree that there should be some kind of work-around since the Java bug is not being fixed by the Java developers. Maybe an on-screen reminder, or something that keeps the cursor in the data field until the user clicks enter, or both. . .

**Comment by jmiller123** [comment]
3.0.0M2 working ok with the added instruction to press enter to commit the changes to the page selection. As I understand it, this is a java bug, that moving a cursor out of a text entry area does not effect a commit, but instead only [ENTER].

**Comment by torakiki** [comment]
Yes, correct. I'll try to find a workaround before the final release
