### ISSUE TITLE
Update to latest on Winget

### ISSUE THREAD

**Issue by tEctutoRIt** [torakiki/pdfsam#613]
I wanted to kindly request that the latest version of pdfsam (v5.2.4) be updated on Winget. The current version available on is v5.2.3. Keeping Winget updated with the latest version ensures that users can enjoy the most recent features and improvements. Thank you for all your hard work and for providing such a great application!

**Comment by torakiki** [comment]
https://github.com/microsoft/winget-pkgs/pull/166612
