### ISSUE TITLE
"Output PDF version: Same as the input document" does not work logically

### ISSUE THREAD

**Issue by fmgst** [torakiki/pdfsam#71]
Using split function, opened source PDF via Browse button, selected "Output PDF version: Same as the input document", and it worked as expected.

Upon opening a second source PDF from a different folder, however, results in: (a) Destination directory continues to show first folder, (b) resulting files are written to first folder but using new source basename. 

So, program does the right thing but it writes the files to a folder that is NOT "Same as the input document".

PDF Split and Merge Community Edition
3.0.0.M1
Java(TM) SE Runtime Environment 1.8.0_31-b13
JavaFX 8.0.31-b13
Max memory 494 MB

**Comment by torakiki** [comment]
I think there's a bit of confusion here
* _Output PDF version: Same as the input document_ is referred to the PDF version of the generated documents so, if the input is a PDF 1.5, generated documents will be PDF 1.5
* The destination directory field is automatically set to the directory containing the source PDF document if the destination directory field is empty **AND** _Use the selected PDF document directory as output directory_ is selected in the settings. It can be set manually any time by clicking _Browse_ or right clicking on the source file and select _Set destination_ from the context menu.

Feel free to reopen the issue if I misunderstood
