### ISSUE TITLE
Split individual PDF pages

### ISSUE THREAD

**Issue by stefanclark** [torakiki/pdfsam#72]
Option to split individual pages into separate pages vertically down the centre. (e.g. PDF with A3 landscape pages into PDF with A4 portrait pages)

**Comment by Maxiride** [comment]
For PDFs not resembling the ISO\DIN standards it would be a big step forward to have the ability to set the millimeters offset of the cut from each side, both to split and\or trim away blank space from scans smaller than the scanned surface.

**Comment by torakiki** [comment]
This feature is available in Sejda https://www.sejda.com/split-pdf-down-the-middle and will be added to PDFsam Visual with the next release

**Comment by stefanclark** [comment]
can you advise whether this has been added and where it can be found
