### ISSUE TITLE
OS X Yosemite: "This disk image is damaged. You should eject it now"

### ISSUE THREAD

**Issue by aareet** [torakiki/pdfsam#74]
On OS X Yosemite, when I try to open the disk image for 2.2.4 basic from Github or SourceForge, I get the error that the disk image is damaged and am prompted to eject. I get a similar error when I try to double click on the app.

I'm using the binary at http://downloads.sourceforge.net/project/pdfsam/pdfsam/2.2.4/pdfsam-2.2.4.dmg?r=http%3A%2F%2Fsourceforge.net%2F&ts=1427126086&use_mirror=softlayer-dal

**Comment by torakiki** [comment]
This should solve the issue: http://www.pdfsam.org/pdf-split-and-merge/support/mac-os-x-pdfsam-is-damaged-and-cant-be-opened/552/

**Comment by aareet** [comment]
It worked, thank you!
