### ISSUE TITLE
Run Button - New Position.

### ISSUE THREAD

**Issue by tobiashochguertel** [torakiki/pdfsam#77]
Improvement to the Gui of v.3.0m1, the Run Button is hard to find. That's annoying, I notice everytime an stress increase when I want to run my configurated action like split or merge - but where is the "run" button. I run the Gui in Maximize mode. ... I attached an Screenshot to illustrate what I notice when using pdfsam. 

![2015-04-03 09_35_26-greenshot](https://cloud.githubusercontent.com/assets/3332669/6981183/c1266536-d9fd-11e4-9310-31bbe5c84f0e.png)

**Comment by torakiki** [comment]
I'm going with something like this
![schermata del 2016-01-19 11 55 02](https://cloud.githubusercontent.com/assets/3884479/12416780/bbcce03e-bea3-11e5-8a51-c63f14000a9f.png)
