### ISSUE TITLE
preview window for Unisci interface

### ISSUE THREAD

**Issue by jeffhawke** [torakiki/pdfsam#79]
I realize this is quite the big modification but I'm making this suggestion all the same since I feel it would be a nice touch.

In the "Unisci" interface, it would be quite appreciated to have a simple preview window that could show the file selected in the table, if any. 

Another big help in the same interface could be a window similar to the old Visual Reorder from where to select the page ranges in a visual way.

**Comment by torakiki** [comment]
All the "visual" features (combine and reorder, visual split, crop, etc..) have been moved/added to PDFsam Visual which is now released. In PDFsam Basic you can right click and open a file using the system default PDF reader but I'm not planning to add any feature that requires the PDF to be rendered. My experience with previous version of PDFsam where we had thumbnails and our current PDF engine, is that rendering a PDF with Java can be quite slow and resources eager so I prefer to delegate to the system PDF reader
