### ISSUE TITLE
PDFSam (merge) doesn't remove signature information properly

### ISSUE THREAD

**Issue by helpcrypto** [torakiki/pdfsam#82]
Consider the following scenario:
  -  first.pdf (normal pdf document with 1 page)
  - second.pdf (signed/certified document with Acroform signature information+annotation on last page[due to named signature] which also includes signature information)

When you merge first+second on "merged.pdf", the Acroform section is removed __but not the reference on the last page__, so having a "corrupted" document.

If you query the document for signatures (using itext), on "merged" it will say 0.
If you sign "merged" once, querying for signatures will say 2 (!?), showing the document is corrupted.

This problem is easy to be debugged using *analize tool* with PDFEditor.
This issue will probably happen with split or with other PDFSam tools.

PDFSam information:
Version: 2.2.4
Console version: 2.4.3e
Build date: 25-Jun-2014

**Comment by torakiki** [comment]
This was closed by https://github.com/torakiki/sejda/issues/190 and by moving the latest task (merge) form iText to SAMBox. It will be released soon with the new tasks implementations based on SAMBox.

**Comment by helpcrypto** [comment]
Thx. Awaiting for release.
