### ISSUE TITLE
Context Sensitive Menue for PDF Files.

### ISSUE THREAD

**Issue by tobiashochguertel** [torakiki/pdfsam#83]
For me it would be an help, if I can right click in Windows Explorer to an PDF File and show an PDFSAM Menue entry which let me fast choose betwen common task:

- Split File | Opens pdfsam in Split View Dialog window with the selected pdf-file already loaded into.
- Merge Selected Files | Opens pdfsam in Merge View Dialog window with all selected pdf-files already  loaded into.
- Rotate File | Opens pdfsam in Rotate View Dialog window with the selected pdf-file already loaded into.
- Split by Size  | Opens pdfsam in Split View Dialog window with the selected pdf-file already loaded into.

The above List with Option-Names and Options it-self could be named better but to show the idea it should be sufficient.

I'm not sure if I could do such an operation already via some command-line arguments of pdfsam. Please tell me if I can open the split / merge / etc dialog with an file already loaded by running pdfsam 
from command-line.

**Comment by torakiki** [comment]
This is interesting and needs to be investigated. I already had few requests for something like this and I think it would be a valuable addition. 
There isn't currently any feature to do that, the only thing slightly related is the concept of workspace that you can save, load and set as default to be loaded when PDFsam starts up.

**Comment by tobiashochguertel** [comment]
Is it possible to start pdfsam with an workspace file from command-line?

**Comment by torakiki** [comment]
No, only from the application settings

**Comment by tobiashochguertel** [comment]
How do you think is the estimated expenditure to implement the command-line argument to set the workspace-file from command-line?

` --workspace-file <file> Absolute Path to an existing workspace file.`

**Comment by torakiki** [comment]
It doesn't look too complicated, if you can open another issue just for that I'll make sure to implement it in PDFsam v3. I can't tell when I'll be able to work on it, we are currently working/experimenting on a PDFBox fork to use as engine for PDFsam and Sejda but once we are done with that, focus will shift back to PDFsam itself.

**Comment by tobiashochguertel** [comment]
Additional issue #84 created.

**Comment by torakiki** [comment]
This is going to be addressed here #167 
The idea is to have a "open with PDFsam" context menu entry and when PDFsam starts, a dialog asks the user which tasks he wants to perform on the selected docs (merge, split, rotate etc).
