### ISSUE TITLE
small display bug in 3.0.0.M1

### ISSUE THREAD

**Issue by orish1** [torakiki/pdfsam#85]
When in fullscreen mode, the PDF select dropdown is truncated. The only way to view/select further down the list is to switch to windows mode.

![pdfsamdisplaybug](https://cloud.githubusercontent.com/assets/13717719/9154902/907285ce-3ece-11e5-9d91-9dbcd041ae52.jpg)

**Comment by torakiki** [comment]
I'm closing this since I cannot reproduce it, feel free to reopen if you have further input.
