### ISSUE TITLE
Merging file with speech information gets corrupted after merge operation

### ISSUE THREAD

**Issue by Robbedoes3** [torakiki/pdfsam#86]
To support my (dyslectic) daughter's studying we acquired special software.
This software is able to add speech to pdf files by means of OCR.
However it is limited due to the fact that one must finish the OCR function in one go (no save option or anything; quite annoying, since overall this is a lengthy operation, that requires a lot of manual corrections before the entire operation can be completed ...)

I hoped pdfSam would help, since I can now split my originals into files containing only one page (or a few pages if desired). This way I am able to work in batches and use pdfSam to merge the results into manageable files afterwards (e.g. containing one chapter of a course book).

Alas, this does not work, because the speech information gets corrupted.
For instance:
After OCR the single files "read" columns as expected (first everything under "A", followed by "B"):

<TABLE>
<TR> <TH COLSPAN="3" ALIGN="LEFT">(1) Column A</TH> <TH></TH> <TH COLSPAN="3" ALIGN="LEFT">(11) Column B</TH> </TR>
<TR> <TD ALIGN="RIGHT"> (2) a1</TD> <TD ALIGN="RIGHT"> (3) a2</TD> <TD ALIGN="RIGHT"> (4) a3</TD> <TD></TD>
     <TD ALIGN="RIGHT">(12) b1</TD> <TD ALIGN="RIGHT">(13) b2</TD> <TD ALIGN="RIGHT">(14) b3</TD></TR>
<TR> <TD ALIGN="RIGHT"> (5) a4</TD> <TD ALIGN="RIGHT"> (6) a5</TD> <TD ALIGN="RIGHT"> (7) a6</TD> <TD></TD>
     <TD ALIGN="RIGHT">(15) b4</TD> <TD ALIGN="RIGHT">(16) b5</TD> <TD ALIGN="RIGHT">(17) b6</TD></TR>
<TR> <TD ALIGN="RIGHT"> (8) a7</TD> <TD ALIGN="RIGHT"> (9) a8</TD> <TD ALIGN="RIGHT">(10) a9</TD> <TD></TD>
     <TD ALIGN="RIGHT">(18) b7</TD> <TD ALIGN="RIGHT">(19) b8</TD> <TD ALIGN="RIGHT">(20) b9</TD></TR></TABLE>

After merging however, it "reads" row by row:

<TABLE>
<TR> <TH COLSPAN="3" ALIGN="LEFT">(1) Column A</TH> <TH></TH> <TH COLSPAN="3" ALIGN="LEFT">(2) Column B</TH> </TR>
<TR> <TD ALIGN="RIGHT"> (3) a1</TD> <TD ALIGN="RIGHT"> (4) a2</TD> <TD ALIGN="RIGHT"> (5) a3</TD> <TD></TD>
     <TD ALIGN="RIGHT"> (6) b1</TD> <TD ALIGN="RIGHT"> (7) b2</TD> <TD ALIGN="RIGHT"> (8) b3</TD></TR>
<TR> <TD ALIGN="RIGHT"> (9) a4</TD> <TD ALIGN="RIGHT">(10) a5</TD> <TD ALIGN="RIGHT">(11) a6</TD> <TD></TD>
     <TD ALIGN="RIGHT">(12) b4</TD> <TD ALIGN="RIGHT">(13) b5</TD> <TD ALIGN="RIGHT">(14) b6</TD></TR>
<TR> <TD ALIGN="RIGHT">(15) a7</TD> <TD ALIGN="RIGHT">(16) a8</TD> <TD ALIGN="RIGHT">(17) a9</TD> <TD></TD>
     <TD ALIGN="RIGHT">(18) b7</TD> <TD ALIGN="RIGHT">(19) b8</TD> <TD ALIGN="RIGHT">(20) b9</TD></TR></TABLE>

This is not an issue for any human reading the document.
But you can imagine it is a problem for any automatic reading; this requires directions.
You would help a lot of people if you could fix this.
If you need example files, please contact me.

**Comment by torakiki** [comment]
Can you share the document so we can take a look?

**Comment by Robbedoes3** [comment]
It is copyrighted, I have tried to reply from my e-mail account by attaching the files.
If it did not reach you, please send me an e-mail on how to reach you, and I can provide the documents.

**Comment by torakiki** [comment]
You can send it to info@pdfsam.org.
Thanks

**Comment by Robbedoes3** [comment]
Just for the record, I sent you the files.

**Comment by Robbedoes3** [comment]
I will try again with the new version (because it has a new engine...)
But I expect the same outcome...
I will let you know!

**Comment by torakiki** [comment]
These documents use a PDF feature called "Logical Structure" and unfortunately PDFsam is not yet capable of handling it so it is discarded. In the tests files there is also a data structure called `Sprintinfo` and I assume it's related to the software you use to edit these documents and it would also need to be take care of. In the end it seems quite complex and difficult to make it right, also considering the `Sprintinfo` data structure which seems quite specific to the software. To be honest I don't think we are going to implement this (I'm very happy to accept/review PRs though)
