### ISSUE TITLE
Resize PDF

### ISSUE THREAD

**Issue by ejmonkey** [torakiki/pdfsam#87]
Be able to custom size a pdf file. This would be wonderful.

Thanks
EJ

**Comment by torakiki** [comment]
What size are you referring? Could you please elaborate the use case for this?
Thanks

**Comment by ejmonkey** [comment]
I'm sorry I made this an issue. It's more of a feature suggestion. I would like to custom size the width and height of the pdf file.  If you add this feature to the enhanced version, I would gladly make another donation.

Thanks
EJ

**Comment by torakiki** [comment]
That's fine, this is also the place for suggestions. Say you make the page bigger, would you expect the content to scale?

**Comment by ejmonkey** [comment]
Thank you so much for taking the time to reply. If possible, let the user decide.

Thanks
EJ

**Comment by torakiki** [comment]
It was implemented and added to the `sejda-console` by this https://github.com/torakiki/sejda/issues/250 , it will soon be added to [sejda.com](http://sejda.com) and we may add it to PDFsam Visual but it won't be added to PDFsam Basic.

**Comment by flaneurette** [comment]
Needing to crop a PDF with keeping all margins and padding in tact. When I resize it in PDF Sam enhanced, it places all elements off the page... I cannot use the Sedja version because it has more than 200 pages....

How do I do this?
