### ISSUE TITLE
Riordino visuale (pdfsam 3.0.0.M2)

### ISSUE THREAD

**Issue by arusan73** [torakiki/pdfsam#98]
Ciao!

Ho sempre usato la versione 2 di pdfsam e ho provato a testare la nuova beta 3.
Sbaglio o la sezione "Riordino visuale" (che permetteva di modificare l'ordine delle pagine all'interno di un file pdf grazie a dei thumbnails delle pagine) manca del tutto nella nuova versione del programma?
Io la ritenevo una funzione molto utile e mi piacerebbe se fosse implementata in una futura release del programma.

Grazie!

**Comment by torakiki** [comment]
Hi, visual modules are not included in the current PDFsam Basic v3. We will probably move them to a separate package called PDFsam Visual or something like that with the old visual modules reimplemented to fit the new PDFsam and some other new visual module as well. We are currently working on it.
Ciao i moduli visuali non sono inclusi nella versione corrente di PDFsam Basic v3. Probabilmente li sposteremo in un pacchetto separato chiamato PDFsam Visual o qualcosa del genere che conterrà i vecchi moduli reimplementati per il nuovo PDFsam e anche alcuni nuovi moduli visuali. Ci stiamo lavorando.

**Comment by arusan73** [comment]
Ciao grazie mille!

**Comment by nath5394** [comment]
Hello,

Thanks for this app, PDF SAM ! I just discovered the v3, automatically updated by chocolatey ;) But the visual feature is so useful for me, I will downgrade to v2. 

Nath'
