### ISSUE TITLE
wrong page size when merge pdfs and I want even page

### ISSUE THREAD

**Issue by mattia-b89** [torakiki/pdfsam#99]
I get wrong odd page size when I merge PDFs and I select the "Add a blank page if page number is odd" option.

INFO:

PDF Split and Merge Basic Edition
3.0.0.M2
Java(TM) SE Runtime Environment 1.8.0_60-b27
JavaFX 8.0.60-b27
Max memory 494 MB

**Comment by torakiki** [comment]
Hi, could you provide some more detail and clarify what is the behaviour and what is expected instead? It would also be helpful if you could provide the PDF documents, if they cannot be shared you could send me a dropbox link or something like that, I'll keep them private, use for tests and delete them.

**Comment by mattia-b89** [comment]
sure! I created two simple PDFs with LibreOffice 5 (one A4 page each).
then I've merged it but the added pages are not A4 (they are bigger).

I share Dropbox links:
https://www.dropbox.com/s/ccbi89m88doyfml/PDFsam_merge.pdf?dl=0
https://www.dropbox.com/s/yif9fo9bgpr13gu/Untitled%201.pdf?dl=0
https://www.dropbox.com/s/csb55ftdz2767wt/Untitled%203.pdf?dl=0

**Comment by torakiki** [comment]
Yes, got it and understood the issue, thanks

**Comment by torakiki** [comment]
closed by https://github.com/torakiki/sejda/issues/201
